// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (linux && arm64)

package flexcc

import (
	"unsafe"

	"modernc.org/libc"
)

type _blksize_t = int32

// C documentation
//
//	// ADD and SUB set C to opposite senses -- a carry for one, a borrow for the
//	// other -- so exchanging one for the other with a negated immediate computes the
//	// same value and a different C. That is only safe when nothing reads the C it sets.
func s__CarryOutUsed(tls *libc.TLS, cc *CC, ir uintptr) (r uint8) {
	return libc.BoolUint8(x__InstrSetsFlags(tls, cc, ir, uint32(_FLAG_WC)) != 0 && s__FlagsUsedAt(tls, cc, (*_IR)(unsafe.Pointer(ir)).Fnext, uint32(_FLAG_WC)) != 0)
}

func s__OptimizeAddSub(tls *libc.TLS, cc *CC, irl uintptr) (r int32) {
	var change, val int32
	var ir1, ir_next, prev uintptr
	var v1 uint8
	var v3 bool
	_, _, _, _, _, _, _ = change, ir1, ir_next, prev, val, v1, v3
	change = 0
	ir1 = (*_IRList)(unsafe.Pointer(irl)).Fhead
	for ir1 != 0 {
		ir_next = (*_IR)(unsafe.Pointer(ir1)).Fnext
		for ir_next != 0 && x__IsDummy(tls, cc, ir_next) != 0 {
			ir_next = (*_IR)(unsafe.Pointer(ir_next)).Fnext
		}
		if !(ir_next != 0) {
			break
		}
		if v3 = (*_IR)(unsafe.Pointer(ir1)).Fopc == int32(_OPC_ADD) || (*_IR)(unsafe.Pointer(ir1)).Fopc == int32(_OPC_SUB); v3 {
			v1 = libc.BoolUint8(uint32(0) != libc.Uint32FromInt32((*_IR)(unsafe.Pointer(ir1)).Fflags)&uint32(_FLAG_KEEP_INSTR))
			goto _2
		_2:
		}
		if v3 && !(v1 != 0) {
			prev = s__FindPrevSetterForReplace(tls, cc, ir1, (*_IR)(unsafe.Pointer(ir1)).Fdst)
			if prev != 0 && ((*_IR)(unsafe.Pointer(prev)).Fopc == int32(_OPC_ADD) || (*_IR)(unsafe.Pointer(prev)).Fopc == int32(_OPC_SUB)) {
				// Merging deletes prev and changes the flags ir sets, so neither
				// may have its flags read: a 64-bit add is `add lo, #k wc` feeding
				// `addx hi, #0`, and an inlined 64-bit negation decides its carry
				// with an `if_e` after `add lo, #1 wz`.
				if (*_Operand)(unsafe.Pointer((*_IR)(unsafe.Pointer(ir1)).Fsrc)).Fkind == int32(_IMM_INT) && (*_Operand)(unsafe.Pointer((*_IR)(unsafe.Pointer(prev)).Fsrc)).Fkind == int32(_IMM_INT) && (*_IR)(unsafe.Pointer(ir1)).Fcond == (*_IR)(unsafe.Pointer(prev)).Fcond && !(s__HasUsedFlags(tls, cc, prev) != 0) && !(s__HasUsedFlags(tls, cc, ir1) != 0) {
					val = s__AddSubVal(tls, cc, ir1) + s__AddSubVal(tls, cc, prev)
					if val < 0 {
						val = -val
						x__ReplaceOpcode(tls, cc, ir1, int32(_OPC_SUB))
					} else {
						x__ReplaceOpcode(tls, cc, ir1, int32(_OPC_ADD))
					}
					(*_IR)(unsafe.Pointer(ir1)).Fsrc = x__NewImmediate(tls, cc, val)
					x__DeleteIR(tls, cc, irl, prev)
					change = int32(1)
				}
			}
		}
		ir1 = ir_next
	}
	return change
}

// C documentation
//
//	// try to transform an operation with a destination that is
//	// known to be the constant "imm"
//	// if the src is also constant, convert it to a move immediate
//	// returns 1 if there is a change
func s__TransformConstDst(tls *libc.TLS, cc *CC, irl uintptr, ir uintptr, imm uintptr) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var cval, val1, val2 _int32_t
	var newlabel uintptr
	var setsResult int32
	var _ /* condchange at bp+0 */ int32
	_, _, _, _, _ = cval, newlabel, setsResult, val1, val2
	setsResult = int32(1)
	if cc.x__gl_p2 != 0 && (!(s__InstrSetsDst(tls, cc, ir) != 0) || (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_LOCKREL) && x__IRIsDeadAfter(tls, cc, ir, (*_IR)(unsafe.Pointer(ir)).Fdst) != 0) {
		// this may be a case where we can replace dst with src
		if (*_IR)(unsafe.Pointer(ir)).Finstr != 0 {
			switch (*_Instruction)(unsafe.Pointer((*_IR)(unsafe.Pointer(ir)).Finstr)).Fops {
			case int32(_P2_DST_CONST_OK):
				fallthrough
			case int32(_P2_TWO_OPERANDS):
				fallthrough
			case int32(_P2_RDWR_OPERANDS):
				(*_IR)(unsafe.Pointer(ir)).Fdst = imm
				return int32(1)
			default:
				break
			}
		}
	}
	if (*_IR)(unsafe.Pointer(ir)).Fsrc == libc.UintptrFromInt32(0) {
		return 0
	}
	if (*_Operand)(unsafe.Pointer(imm)).Fkind == int32(_IMM_INT) && (*_Operand)(unsafe.Pointer(imm)).Fval == 0 {
		// transform add foo, bar into mov foo, bar, if foo is known to be 0
		if ((*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_ADD) || (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_SUB) || (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_OR) || (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_XOR)) && (libc.Uint32FromInt32((*_IR)(unsafe.Pointer(ir)).Fflags) == uint32(_FLAG_WZ) || !(x__InstrSetsAnyFlags(tls, cc, ir) != 0)) {
			if (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_SUB) {
				x__ReplaceOpcode(tls, cc, ir, int32(_OPC_NEG))
			} else {
				x__ReplaceOpcode(tls, cc, ir, int32(_OPC_MOV))
			}
			return int32(1)
		}
	}
	if (*_Operand)(unsafe.Pointer((*_IR)(unsafe.Pointer(ir)).Fsrc)).Fkind != int32(_IMM_INT) {
		return 0
	}
	if (*_Operand)(unsafe.Pointer(imm)).Fkind == int32(_IMM_COG_LABEL) && (*_IR)(unsafe.Pointer(ir)).Fopc == int32(_OPC_ADD) && (*_IR)(unsafe.Pointer(ir)).Fflags == 0 {
		newlabel = x__NewOperand(tls, cc, int32(_IMM_COG_LABEL), (*_Operand)(unsafe.Pointer(imm)).Fname, (*_Operand)(unsafe.Pointer(imm)).Fval+(*_Operand)(unsafe.Pointer((*_IR)(unsafe.Pointer(ir)).Fsrc)).Fval)
		(*_IR)(unsafe.Pointer(ir)).Fsrc = newlabel
		x__ReplaceOpcode(tls, cc, ir, int32(_OPC_MOV))
		return int32(1)
	}
	if (*_Operand)(unsafe.Pointer(imm)).Fkind != int32(_IMM_INT) {
		return 0
	}
	if libc.Uint32FromInt32((*_IR)(unsafe.Pointer(ir)).Fflags)&uint32(_FLAG_WC) != 0 {
		// we don't know how to set the WC flag for anything other
		// than cmps/cmp/sub
		if (*_IR)(unsafe.Pointer(ir)).Fopc != int32(_OPC_CMPS) && (*_IR)(unsafe.Pointer(ir)).Fopc != int32(_OPC_CMP) && (*_IR)(unsafe.Pointer(ir)).Fopc != int32(_OPC_SUB) {
			return 0
		}
	}
	val1 = int32((*_Operand)(unsafe.Pointer(imm)).Fval)
	val2 = int32((*_Operand)(unsafe.Pointer((*_IR)(unsafe.Pointer(ir)).Fsrc)).Fval)
	cval = 0
	switch (*_IR)(unsafe.Pointer(ir)).Fopc {
	case int32(_OPC_ADD):
		val1 = val1 + val2
	case int32(_OPC_TEST):
		setsResult = m_false
		// fall through
		fallthrough
	case int32(_OPC_AND):
		val1 = val1 & val2
	case int32(_OPC_OR):
		val1 = val1 | val2
	case int32(_OPC_XOR):
		val1 = val1 ^ val2
	case int32(_OPC_TESTN):
		setsResult = m_false
		// fall through
		fallthrough
	case int32(_OPC_ANDN):
		val1 = val1 & ^val2
	case int32(_OPC_SHL):
		val1 = val1 << (val2 & int32(31))
	case int32(_OPC_SAR):
		val1 = val1 >> (val2 & int32(31))
	case int32(_OPC_SHR):
		val1 = libc.Int32FromUint32(libc.Uint32FromInt32(val1) >> (val2 & int32(31)))
	case int32(_OPC_ZEROX):
		val2 = int32(31) - val2&int32(31)
		val1 = libc.Int32FromUint32(libc.Uint32FromInt32(val1) << val2 >> val2)
	case int32(_OPC_SIGNX):
		val2 = int32(31) - val2&int32(31)
		val1 = val1 << val2 >> val2
	case int32(_OPC_CMPS):
		// C is the signed less-than, which the sign of the difference
		// is not when the difference overflows: -7 - 0x7fffffff wraps
		if val1 < val2 {
			cval = -int32(1)
		} else {
			if val1 == val2 {
				cval = 0
			} else {
				cval = int32(1)
			}
		}
		val1 = libc.Int32FromUint32(libc.Uint32FromInt32(val1) - libc.Uint32FromInt32(val2))
		setsResult = 0
	case int32(_OPC_CMP):
		setsResult = 0
		fallthrough
	case int32(_OPC_SUB):
		if libc.Uint32FromInt32(val1) < libc.Uint32FromInt32(val2) {
			cval = -int32(1)
		} else {
			if val1 == val2 {
				cval = 0
			} else {
				cval = int32(1)
			}
		}
		val1 = val1 - val2
	case int32(_OPC_TESTBN):
		setsResult = m_false
		// Z is set if bit is CLEAR
		val1 = val1 & (int32(1) << (val2 & int32(31)))
	case int32(_OPC_TESTB):
		setsResult = m_false
		// Z is set if bit is SET
		val1 = ^val1 & (int32(1) << (val2 & int32(31)))
	case int32(_OPC_BITH):
		val1 = libc.Int32FromUint32(uint32(val1) | s__EvalP2BitMask(tls, cc, val2))
	case int32(_OPC_BITL):
		val1 = libc.Int32FromUint32(uint32(val1) & ^s__EvalP2BitMask(tls, cc, val2))
	case int32(_OPC_BITNOT):
		val1 = libc.Int32FromUint32(uint32(val1) ^ s__EvalP2BitMask(tls, cc, val2))
	default:
		return 0
	}
	if x__InstrSetsAnyFlags(tls, cc, ir) != 0 {
		**(**int32)(__ccgo_up(bp)) = 0
		if !(x__ApplyConditionAfter(tls, cc, irl, ir, cval, val1, bp) != 0) {
			return **(**int32)(__ccgo_up(bp)) // Couldn't apply condition :(
		}
		**(**int32)(__ccgo_up(ir + 48)) &= libc.BoolInt32(!(uint32(_FLAG_WZ)|uint32(_FLAG_WC)|uint32(_FLAG_ANDC)|uint32(_FLAG_ANDZ)|uint32(_FLAG_ORC)|uint32(_FLAG_ORZ)|uint32(_FLAG_XORC)|uint32(_FLAG_XORZ)|uint32(_FLAG_WCZ) != 0))
	}
	if setsResult != 0 {
		if val1 < 0 {
			x__ReplaceOpcode(tls, cc, ir, int32(_OPC_NEG))
			(*_IR)(unsafe.Pointer(ir)).Fsrc = x__NewImmediate(tls, cc, -val1)
		} else {
			x__ReplaceOpcode(tls, cc, ir, int32(_OPC_MOV))
			(*_IR)(unsafe.Pointer(ir)).Fsrc = x__NewImmediate(tls, cc, val1)
		}
	} else {
		(*_IR)(unsafe.Pointer(ir)).Fcond = int32(_COND_FALSE)
	}
	return int32(1)
}
