// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && amd64) || (windows && amd64)

package flexcc

import (
	"unsafe"

	"modernc.org/libc"
)

const _BASICYYEMPTY = -2

const _BASICYYEOF = 0

const _BASICYYUNDEF = 257

const _BASICYYerror = 256

const _BAS_ABS = 279

const _BAS_ABSADDR = 402

const _BAS_ADD_ASSIGN = 403

const _BAS_ALIAS = 280

const _BAS_ALIGNL = 271

const _BAS_ALIGNW = 272

const _BAS_ALLOCA = 288

const _BAS_AND = 281

const _BAS_ANDALSO = 282

const _BAS_AND_ASSIGN = 408

const _BAS_ANY = 283

const _BAS_APPEND = 284

const _BAS_AS = 285

const _BAS_ASC = 286

const _BAS_ASM = 287

const _BAS_BOOLEAN = 289

const _BAS_BYREF = 290

const _BAS_BYTE = 291

const _BAS_BYVAL = 292

const _BAS_CALL = 293

const _BAS_CASE = 294

const _BAS_CAST = 295

const _BAS_CAST_INT = 331

const _BAS_CATCH = 296

const _BAS_CHAIN = 297

const _BAS_CLASS = 298

const _BAS_CLOSE = 299

const _BAS_CONST = 300

const _BAS_CONTINUE = 301

const _BAS_CPU = 302

const _BAS_DATA = 303

const _BAS_DECLARE = 304

const _BAS_DEF = 305

const _BAS_DEFINT = 306

const _BAS_DEFSNG = 307

const _BAS_DELETE = 308

const _BAS_DIM = 309

const _BAS_DIRECTION = 310

const _BAS_DIV_ASSIGN = 406

const _BAS_DO = 311

const _BAS_DOUBLE = 312

const _BAS_ELSE = 313

const _BAS_EMPTY = 258

const _BAS_END = 314

const _BAS_ENDIF = 315

const _BAS_ENUM = 316

const _BAS_EOF = 266

const _BAS_EOLN = 265

const _BAS_EXIT = 317

const _BAS_EXTERN = 318

const _BAS_FILE = 273

const _BAS_FIT = 274

const _BAS_FIXED = 319

const _BAS_FLOAT = 263

const _BAS_FOR = 320

const _BAS_FUNCTION = 321

const _BAS_FUNC_NAME = 322

const _BAS_GE = 398

const _BAS_GET = 323

const _BAS_GOSUB = 325

const _BAS_GOTO = 324

const _BAS_HASMETHOD = 326

const _BAS_HWREG = 270

const _BAS_IDENTIFIER = 259

const _BAS_IF = 327

const _BAS_IMPLEMENTS = 328

const _BAS_IMPORT = 329

const _BAS_INPUT = 330

const _BAS_INSTR = 268

const _BAS_INSTRMODIFIER = 269

const _BAS_INTEGER = 262

const _BAS_INTEGER_KW = 332

const _BAS_INTERFACE = 333

const _BAS_LABEL_EXPLICIT = 261

const _BAS_LABEL_INFERRED = 260

const _BAS_LE = 397

const _BAS_LEN = 334

const _BAS_LET = 335

const _BAS_LIB = 336

const _BAS_LINE = 337

const _BAS_LONG = 338

const _BAS_LONGINT = 339

const _BAS_LOOP = 340

const _BAS_MOD = 341

const _BAS_MOD_ASSIGN = 407

const _BAS_MUL_ASSIGN = 405

const _BAS_NE = 399

const _BAS_NEW = 342

const _BAS_NEXT = 343

const _BAS_NIL = 344

const _BAS_NOT = 345

const _BAS_OFFSETOF = 346

const _BAS_ON = 347

const _BAS_OPEN = 348

const _BAS_OPTION = 349

const _BAS_OR = 350

const _BAS_ORELSE = 351

const _BAS_ORG = 275

const _BAS_ORGF = 276

const _BAS_ORGH = 277

const _BAS_OR_ASSIGN = 409

const _BAS_OUTPUT = 352

const _BAS_POINTER = 353

const _BAS_PRESERVE = 354

const _BAS_PRINT = 355

const _BAS_PRIVATE = 356

const _BAS_PROGRAM = 357

const _BAS_PTR = 358

const _BAS_PUT = 359

const _BAS_READ = 360

const _BAS_REDIM = 361

const _BAS_REGISTER = 362

const _BAS_RES = 278

const _BAS_RESTORE = 363

const _BAS_RETURN = 364

const _BAS_SAMETYPES = 365

const _BAS_SELECT = 366

const _BAS_SELF = 367

const _BAS_SHARED = 368

const _BAS_SHL = 400

const _BAS_SHORT = 369

const _BAS_SHR = 401

const _BAS_SINGLE = 370

const _BAS_SIZEOF = 371

const _BAS_SQRT = 372

const _BAS_STEP = 373

const _BAS_STRING = 264

const _BAS_STRING_KW = 374

const _BAS_STRUCT = 375

const _BAS_SUB = 376

const _BAS_SUB_ASSIGN = 404

const _BAS_THEN = 377

const _BAS_THROW = 378

const _BAS_THROWIFCAUGHT = 379

const _BAS_TO = 380

const _BAS_TRY = 381

const _BAS_TYPE = 382

const _BAS_TYPENAME = 267

const _BAS_UBYTE = 383

const _BAS_UINTEGER = 384

const _BAS_ULONG = 385

const _BAS_ULONGINT = 386

const _BAS_UNION = 387

const _BAS_UNTIL = 388

const _BAS_USHORT = 389

const _BAS_USING = 390

const _BAS_VAR = 391

const _BAS_WEND = 392

const _BAS_WHILE = 394

const _BAS_WITH = 393

const _BAS_WORD = 395

const _BAS_XOR = 396

const _BAS_XOR_ASSIGN = 410

const _CGRAMYYEMPTY = -2

const _CGRAMYYEOF = 0

const _CGRAMYYUNDEF = 257

const _CGRAMYYerror = 256

const _C_ABSADDR_OP = 287

const _C_ADD_ASSIGN = 277

const _C_ALIGNL = 349

const _C_ALIGNW = 350

const _C_AND_ASSIGN = 281

const _C_AND_OP = 272

const _C_ASM = 328

const _C_ATTRIBUTE = 327

const _C_BOOL = 294

const _C_BREAK = 323

const _C_BUILTIN_ABS = 363

const _C_BUILTIN_ALLOCA = 369

const _C_BUILTIN_CLZ = 364

const _C_BUILTIN_COGSTART = 370

const _C_BUILTIN_COGSTART_COG = 371

const _C_BUILTIN_EXPECT = 372

const _C_BUILTIN_FRAC = 366

const _C_BUILTIN_LONGJMP = 379

const _C_BUILTIN_MULH = 367

const _C_BUILTIN_MULUH = 368

const _C_BUILTIN_OFFSETOF = 373

const _C_BUILTIN_PRINTF = 374

const _C_BUILTIN_REV = 375

const _C_BUILTIN_SETJMP = 378

const _C_BUILTIN_SQRT = 365

const _C_BUILTIN_STRLEN = 380

const _C_BUILTIN_VA_ARG = 377

const _C_BUILTIN_VA_START = 376

const _C_BYTE = 351

const _C_CASE = 313

const _C_CATCH = 334

const _C_CHAR = 295

const _C_CLASS = 335

const _C_CONST = 305

const _C_CONSTANT = 259

const _C_CONTINUE = 322

const _C_DEBUG = 330

const _C_DEC_OP = 265

const _C_DEFAULT = 314

const _C_DIV_ASSIGN = 275

const _C_DO = 319

const _C_DOUBLE = 304

const _C_DOUBLECOLON = 312

const _C_ELLIPSIS = 311

const _C_ELSE = 316

const _C_ELSEIF = 352

const _C_END = 353

const _C_ENUM = 310

const _C_EOLN = 361

const _C_EQ_OP = 270

const _C_EXTERN = 289

const _C_FALSE = 337

const _C_FILE = 354

const _C_FIT = 355

const _C_FLOAT = 303

const _C_FOR = 320

const _C_FROMFILE = 325

const _C_FUNC = 362

const _C_GE_OP = 269

const _C_GOTO = 321

const _C_HWREG = 333

const _C_IDENTIFIER = 258

const _C_IF = 315

const _C_IMAGINARY = 297

const _C_INC_OP = 264

const _C_INLINE = 298

const _C_INSTR = 331

const _C_INSTRMODIFIER = 332

const _C_INT = 299

const _C_LEFT_ASSIGN = 279

const _C_LEFT_OP = 266

const _C_LE_OP = 268

const _C_LONG = 300

const _C_MOD_ASSIGN = 276

const _C_MUL_ASSIGN = 274

const _C_NE_OP = 271

const _C_NULLPTR = 339

const _C_ORG = 356

const _C_ORGF = 358

const _C_ORGH = 357

const _C_OR_ASSIGN = 283

const _C_OR_OP = 273

const _C_PASM = 329

const _C_PRIVATE = 341

const _C_PTR_OP = 263

const _C_PUBLIC = 342

const _C_REGISTER = 292

const _C_RES = 359

const _C_RESTRICT = 293

const _C_RETURN = 324

const _C_RIGHT_ASSIGN = 280

const _C_RIGHT_OP = 267

const _C_SHORT = 296

const _C_SIGNED = 301

const _C_SIZEOF = 261

const _C_STATIC = 290

const _C_STRING_LITERAL = 260

const _C_STRUCT = 308

const _C_SUB_ASSIGN = 278

const _C_SWITCH = 317

const _C_TEMPLATE = 343

const _C_THIS = 344

const _C_THROW = 345

const _C_THROWIF = 346

const _C_TRUE = 340

const _C_TRY = 347

const _C_TYPEDEF = 288

const _C_TYPEOF = 262

const _C_TYPE_NAME = 284

const _C_UNION = 309

const _C_UNSIGNED = 302

const _C_USING = 326

const _C_VIRTUAL = 348

const _C_VOID = 307

const _C_VOLATILE = 306

const _C_WHILE = 318

const _C_WORD = 360

const _C_XOR_ASSIGN = 282

const _SPINYYEMPTY = -2

const _SPINYYEOF = 0

const _SPINYYUNDEF = 257

const _SPINYYerror = 256

const _SP_ABORT = 328

const _SP_ABS = 409

const _SP_ADDBITS = 404

const _SP_ADDPINS = 405

const _SP_ALIGNL = 291

const _SP_ALIGNW = 292

const _SP_ALLOCA = 325

const _SP_AND = 376

const _SP_ANDTHEN = 378

const _SP_ANNOTATION = 339

const _SP_ASM = 340

const _SP_ASMCLK = 282

const _SP_ASM_CONST = 341

const _SP_ASM_ELSE = 345

const _SP_ASM_ELSEIF = 344

const _SP_ASM_ENDIF = 346

const _SP_ASM_IF = 343

const _SP_ASSIGN = 373

const _SP_BACKTICK_STRING = 262

const _SP_BMASK = 434

const _SP_BYTE = 274

const _SP_BYTECODE = 259

const _SP_BYTEFIT = 278

const _SP_BYTES = 351

const _SP_CASE = 320

const _SP_CASE_FAST = 321

const _SP_COGINIT = 311

const _SP_COGNEW = 312

const _SP_COGREG = 265

const _SP_CON = 266

const _SP_CONDITIONAL = 439

const _SP_CONDITIONAL_SEP = 440

const _SP_CONSTANT = 427

const _SP_COPY = 363

const _SP_C_Z = 369

const _SP_DAT = 268

const _SP_DAT_LBRACK = 465

const _SP_DAT_RBRACK = 466

const _SP_DEBUG = 437

const _SP_DEBUG_END_SESSION = 452

const _SP_DECODE = 412

const _SP_DECREMENT = 418

const _SP_DITTO = 372

const _SP_DOTS = 335

const _SP_DOUBLEAT = 421

const _SP_DOUBLETILDE = 416

const _SP_DOUBLE_DOLLAR = 467

const _SP_ELSE = 302

const _SP_ELSEIF = 303

const _SP_ELSEIFNOT = 304

const _SP_EMPTY = 429

const _SP_ENCODE = 413

const _SP_ENCODE2 = 414

const _SP_END = 272

const _SP_ENDASM = 342

const _SP_ENDIANL = 450

const _SP_ENDIANW = 451

const _SP_EOF = 334

const _SP_EOLN = 333

const _SP_EQ = 386

const _SP_EXP = 447

const _SP_EXP10 = 445

const _SP_EXP2 = 443

const _SP_FABS = 411

const _SP_FADD = 454

const _SP_FDIV = 457

const _SP_FEQ = 461

const _SP_FGE = 463

const _SP_FGT = 459

const _SP_FIELD = 350

const _SP_FIELDPTR = 423

const _SP_FILE = 338

const _SP_FILL = 362

const _SP_FIT = 290

const _SP_FLE = 462

const _SP_FLOAT = 424

const _SP_FLOATNUM = 263

const _SP_FLT = 458

const _SP_FMUL = 456

const _SP_FNE = 460

const _SP_FRAC = 393

const _SP_FROM = 294

const _SP_FSQRT = 410

const _SP_FSUB = 455

const _SP_FVAR = 280

const _SP_FVARS = 281

const _SP_GE = 379

const _SP_GEU = 381

const _SP_GTU = 383

const _SP_HERE = 336

const _SP_HIGHMULT = 394

const _SP_HWREG = 285

const _SP_IDENTIFIER = 258

const _SP_IF = 300

const _SP_IFNOT = 301

const _SP_INCREMENT = 417

const _SP_INDENT = 331

const _SP_INLINECCODE = 273

const _SP_INSTR = 283

const _SP_INSTRMODIFIER = 284

const _SP_INTERFACE = 347

const _SP_LE = 380

const _SP_LEU = 382

const _SP_LIMITMAX = 389

const _SP_LIMITMIN = 388

const _SP_LOG = 446

const _SP_LOG10 = 444

const _SP_LOG2 = 442

const _SP_LONG = 276

const _SP_LONGS = 353

const _SP_LOOKDOWN = 307

const _SP_LOOKDOWNZ = 308

const _SP_LOOKUP = 309

const _SP_LOOKUPZ = 310

const _SP_LOOK_SEP = 438

const _SP_LSTRING = 354

const _SP_LTU = 384

const _SP_MOVBYTS = 449

const _SP_NAMESP = 348

const _SP_NAN = 432

const _SP_NE = 385

const _SP_NEWTASK = 370

const _SP_NEXT = 324

const _SP_NOT = 415

const _SP_NUM = 260

const _SP_OBJ = 271

const _SP_OFFSETOF = 453

const _SP_ONES = 433

const _SP_OR = 375

const _SP_ORELSE = 377

const _SP_ORG = 286

const _SP_ORGF = 288

const _SP_ORGH = 287

const _SP_OTHER = 322

const _SP_OUTDENT = 332

const _SP_PINH = 319

const _SP_PINL = 318

const _SP_PINR = 315

const _SP_PINT = 316

const _SP_PINW = 317

const _SP_POW = 448

const _SP_PRI = 270

const _SP_PUB = 269

const _SP_QEXP = 436

const _SP_QLOG = 435

const _SP_QUAD = 277

const _SP_QUIT = 323

const _SP_RANDOM = 428

const _SP_REF_DEC = 420

const _SP_REF_INC = 419

const _SP_REGEXEC = 326

const _SP_REGLOAD = 327

const _SP_REMAINDER = 390

const _SP_REPEAT = 293

const _SP_REPEAT_SEP = 441

const _SP_RES = 289

const _SP_RESULT = 329

const _SP_RETURN = 330

const _SP_REV = 402

const _SP_REV2 = 403

const _SP_ROTL = 398

const _SP_ROTR = 397

const _SP_ROUND = 426

const _SP_SAR = 401

const _SP_SCAS = 395

const _SP_SGNCOMP = 387

const _SP_SHL = 399

const _SP_SHR = 400

const _SP_SIGNX = 430

const _SP_SIZEOF = 367

const _SP_SPR = 264

const _SP_SQRT = 408

const _SP_STEP = 296

const _SP_STRING = 261

const _SP_STRINGPTR = 337

const _SP_STRUCT = 366

const _SP_SWAP = 364

const _SP_SWAP_OP = 368

const _SP_TASKHLT = 314

const _SP_TASKINIT = 313

const _SP_THEN = 305

const _SP_THISTASK = 371

const _SP_TO = 295

const _SP_TRIPLEAT = 422

const _SP_TRUNC = 425

const _SP_TYPENAME = 355

const _SP_UNSDIV = 391

const _SP_UNSHIGHMULT = 396

const _SP_UNSMOD = 392

const _SP_UNTIL = 299

const _SP_VAR = 267

const _SP_VARARGS = 349

const _SP_WHILE = 297

const _SP_WITH = 298

const _SP_WORD = 275

const _SP_WORDFIT = 279

const _SP_WORDS = 352

const _SP_XOR = 374

const _SP_ZEROX = 431

const _YYSYMBOL_YYEMPTY = -2

const _YYSYMBOL_YYEOF = 0

const /* error  */
_YYSYMBOL_YYUNDEF = 2

const /* "end of file"  */
_YYSYMBOL_YYerror = 1

// C documentation
//
//	/* State numbers in computations.  */
type _yy_state_fast_t = int32

// C documentation
//
//	/* Stored state numbers (used for stacks). */
type _yy_state_t = int16

// C documentation
//
//	/* Context of a parse error.  */
type _yypcontext_t = struct {
	Fyyssp   uintptr
	Fyytoken _yysymbol_kind_t1
}

type _yysymbol_kind_t1 = int32

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

type _yytype_int16 = int16

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */

type _yytype_int8 = int8

const m_YYNSTATES = 1234

const m_YYNSTATES1 = 967

const m_YYNSTATES2 = 858

func s__AdjustParamForByVal(tls *libc.TLS, cc *CC, param uintptr) (r uintptr) {
	var typ uintptr
	_ = typ
	typ = (*_AST)(unsafe.Pointer(param)).Fleft
	if typ != 0 && !((*_AST)(unsafe.Pointer(typ)).Fkind == int32(_AST_IDENTIFIER) || (*_AST)(unsafe.Pointer(typ)).Fkind == int32(_AST_LOCAL_IDENTIFIER)) && (x__IsClassType(tls, cc, typ) != 0 || x__IsArrayType(tls, cc, typ) != 0) {
		(*_AST)(unsafe.Pointer(param)).Fleft = x__NewAST(tls, cc, int32(_AST_COPYREFTYPE), typ, libc.UintptrFromInt32(0))
	}
	return param
}

// C documentation
//
//	/* convert a Spin block type into a standard block type */
func s__MapSpinBlock(tls *libc.TLS, cc *CC, c int32) (r int32) {
	switch c {
	case int32(_SP_CON):
		return int32(m_BLOCK_CON)
	case int32(_SP_VAR):
		return int32(m_BLOCK_VAR)
	case int32(_SP_OBJ):
		return int32(m_BLOCK_OBJ)
	case int32(_SP_DAT):
		return int32(m_BLOCK_DAT)
	case int32(_SP_ASM):
		fallthrough
	case int32(_SP_ASM_CONST):
		fallthrough
	case int32(_SP_ORG):
		return int32(m_BLOCK_ASM)
	case int32(_SP_PUB):
		return int32(m_BLOCK_PUB)
	case int32(_SP_PRI):
		return int32(m_BLOCK_PRI)
	default:
		return int32(m_BLOCK_UNKNOWN)
	}
	return r
}

func s__ParseCAttribute(tls *libc.TLS, cc *CC, L uintptr, ast_ptr uintptr) (r int32) {
	bp := tls.Alloc(32)
	defer tls.Free(32)
	var ast uintptr
	var balance, c int32
	var _ /* fb at bp+0 */ _flexbuf
	_, _, _ = ast, balance, c
	balance = 0
	ast = x__NewAST(tls, cc, int32(_AST_ANNOTATION), libc.UintptrFromInt32(0), libc.UintptrFromInt32(0))
	x__flexbuf_init(tls, cc, bp, uint64(32))
	for cond := true; cond; cond = balance > 0 {
		c = x__lexgetc(tls, cc, L)
		if c < 0 {
			break
		}
		if c == int32('(') {
			balance = balance + 1
		} else {
			if c == int32(')') {
				balance = balance - 1
			}
		}
		x__flexbuf_addchar(tls, cc, bp, c)
	}
	x__flexbuf_addchar(tls, cc, bp, 0)
	*(*uintptr)(unsafe.Pointer(ast + 8)) = x__flexbuf_get(tls, cc, bp)
	**(**uintptr)(__ccgo_up(ast_ptr)) = ast
	return int32(_C_ATTRIBUTE)
}

func s__PrintUpper(tls *libc.TLS, cc *CC, f uintptr, name uintptr) {
	var c, v1 int32
	var v2 uintptr
	_, _, _ = c, v1, v2
	for {
		v2 = name
		name = name + 1
		v1 = int32(**(**int8)(__ccgo_up(v2)))
		c = v1
		if !(v1 != 0) {
			break
		}
		x__flexbuf_addchar(tls, cc, f, libc.Xtoupper(tls, c))
	}
}

// C documentation
//
//	// declare a Spin structure
func s__SpinDeclareInterface(tls *libc.TLS, cc *CC, ident uintptr, defs uintptr) {
	var P, body, classname, item, newobj, rettype uintptr
	_, _, _, _, _, _ = P, body, classname, item, newobj, rettype
	classname = x__GetUserIdentifierName(tls, cc, ident)
	P = x__NewModule(tls, cc, classname, (*_Module)(unsafe.Pointer(cc.x__current)).FcurLanguage)
	newobj = x__NewAbstractObject(tls, cc, ident, libc.UintptrFromInt32(0), 0)
	*(*uintptr)(unsafe.Pointer(newobj + 8)) = P
	(*_Module)(unsafe.Pointer(P)).FisInterface = int8(1)
	x__AddSymbol(tls, cc, cc.x__currentTypes, classname, int32(_SYM_TYPEDEF), newobj, libc.UintptrFromInt32(0))
	if P != cc.x__current {
		(*_Module)(unsafe.Pointer(P)).FLptr = (*_Module)(unsafe.Pointer(cc.x__current)).FLptr
		(*_Module)(unsafe.Pointer(P)).Fsubclasses = (*_Module)(unsafe.Pointer(cc.x__current)).Fsubclasses
		(*_Module)(unsafe.Pointer(cc.x__current)).Fsubclasses = P
		(*_Module)(unsafe.Pointer(P)).Fsuperclass = cc.x__current
		(*_Module)(unsafe.Pointer(P)).Ffullname = (*_Module)(unsafe.Pointer(cc.x__current)).Ffullname // for finding "class using"
		*(*uintptr)(unsafe.Pointer(newobj + 8)) = P
		(*_Module)(unsafe.Pointer(P)).FisPacked = int8(1)
		/* import parent's symbols into P */
		(*_Module)(unsafe.Pointer(P)).Fobjsyms.Fnext = cc.x__current + 144
		x__AddSymbol(tls, cc, cc.x__current+144, classname, int32(_SYM_TYPEDEF), newobj, libc.UintptrFromInt32(0))
	}
	x__PushCurrentModule(tls, cc)
	cc.x__current = P
	/* declare abstract methods */
	for defs != 0 {
		body = libc.UintptrFromInt32(0)
		item = (*_AST)(unsafe.Pointer(defs)).Fleft
		defs = (*_AST)(unsafe.Pointer(defs)).Fright
		for item != 0 && (*_AST)(unsafe.Pointer(item)).Fkind == int32(_AST_COMMENTEDNODE) {
			item = (*_AST)(unsafe.Pointer(item)).Fleft
		}
		rettype = x__SpinRetType(tls, cc, item)
		x__DeclareFunction(tls, cc, cc.x__current, rettype, int32(1), item, body, libc.UintptrFromInt32(0), libc.UintptrFromInt32(0))
	}
	x__PopCurrentModule(tls, cc)
}

func s__cleanname(tls *libc.TLS, cc *CC, name uintptr) (r uintptr) {
	var c, i, v2 int32
	var v1 uintptr
	_, _, _, _ = c, i, v1, v2
	i = 0
	for i < int32(1020) {
		v1 = name
		name = name + 1
		c = int32(**(**int8)(__ccgo_up(v1)))
		if c == 0 {
			break
		}
		if libc.Xisalnum(tls, c) != 0 || c == int32('_') {
			v2 = i
			i = i + 1
			cc.s__temp[v2] = int8(c)
		} else {
			v2 = i
			i = i + 1
			cc.s__temp[v2] = int8('_')
			switch c {
			case int32('$'):
				v2 = i
				i = i + 1
				cc.s__temp[v2] = int8('S')
			case int32('#'):
				v2 = i
				i = i + 1
				cc.s__temp[v2] = int8('R')
			case int32('%'):
				v2 = i
				i = i + 1
				cc.s__temp[v2] = int8('I')
			default:
				v2 = i
				i = i + 1
				cc.s__temp[v2] = int8(int32('A') + c&int32(0xF))
				v2 = i
				i = i + 1
				cc.s__temp[v2] = int8(int32('A') + c&int32(0xF))
				break
			}
		}
	}
	v2 = i
	i = i + 1
	cc.s__temp[v2] = 0
	return uintptr(unsafe.Pointer(&cc.s__temp))
}

func s__yy_symbol_value_print(tls *libc.TLS, cc *CC, yyo uintptr, yykind _yysymbol_kind_t1, yyvaluep uintptr) {
	var yyoutput uintptr
	_ = yyoutput
	yyoutput = yyo
	_ = yyoutput
	if !(yyvaluep != 0) {
		return
	}
	_ = yykind
}

/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

func s__yy_symbol_value_print1(tls *libc.TLS, cc *CC, yyo uintptr, yykind _yysymbol_kind_t1, yyvaluep uintptr) {
	var yyoutput uintptr
	_ = yyoutput
	yyoutput = yyo
	_ = yyoutput
	if !(yyvaluep != 0) {
		return
	}
	_ = yykind
}

/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

func s__yy_symbol_value_print2(tls *libc.TLS, cc *CC, yyo uintptr, yykind _yysymbol_kind_t1, yyvaluep uintptr) {
	var yyoutput uintptr
	_ = yyoutput
	yyoutput = yyo
	_ = yyoutput
	if !(yyvaluep != 0) {
		return
	}
	_ = yykind
}

/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

func s__yy_syntax_error_arguments(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yycount, yyn int32
	var v1 uintptr
	_, _, _ = yycount, yyn, v1
	/* Actual size of YYARG. */
	yycount = 0
	/* There are many possibilities here to consider:
	   - If this state is a consistent state with a default action, then
	     the only way this function was invoked is if the default action
	     is an error action.  In that case, don't check for expected
	     tokens because there are none.
	   - The only way there can be no lookahead present (in yychar) is if
	     this state is a consistent state with a default action.  Thus,
	     detecting the absence of a lookahead is sufficient to determine
	     that there is no unexpected or expected token to report.  In that
	     case, just report a simple "syntax error".
	   - Don't assume there isn't a lookahead just because this state is a
	     consistent state with a default action.  There might have been a
	     previous inconsistent state, consistent state with a non-default
	     action, or user semantic action that manipulated yychar.
	   - Of course, the expected token list depends on states to have
	     correct lookahead information, and it depends on the parser not
	     to perform extra reductions after fetching a lookahead from the
	     scanner and before detecting a syntax error.  Thus, state merging
	     (from LALR or IELR) and default reductions corrupt the expected
	     token list.  However, the list is correct for canonical LR with
	     one exception: it will still contain any token that will not be
	     accepted due to an error action in a later state.
	*/
	if (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken != int32(_YYSYMBOL_YYEMPTY) {
		if yyarg != 0 {
			**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(yycount)*4)) = (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken
		}
		yycount = yycount + 1
		if yyarg != 0 {
			v1 = yyarg + uintptr(1)*4
		} else {
			v1 = yyarg
		}
		yyn = s__yypcontext_expected_tokens(tls, cc, yyctx, v1, yyargn-int32(1))
		if yyn == int32(_YYENOMEM) {
			return int32(_YYENOMEM)
		} else {
			yycount = yycount + yyn
		}
	}
	return yycount
}

func s__yy_syntax_error_arguments1(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yycount, yyn int32
	var v1 uintptr
	_, _, _ = yycount, yyn, v1
	/* Actual size of YYARG. */
	yycount = 0
	/* There are many possibilities here to consider:
	   - If this state is a consistent state with a default action, then
	     the only way this function was invoked is if the default action
	     is an error action.  In that case, don't check for expected
	     tokens because there are none.
	   - The only way there can be no lookahead present (in yychar) is if
	     this state is a consistent state with a default action.  Thus,
	     detecting the absence of a lookahead is sufficient to determine
	     that there is no unexpected or expected token to report.  In that
	     case, just report a simple "syntax error".
	   - Don't assume there isn't a lookahead just because this state is a
	     consistent state with a default action.  There might have been a
	     previous inconsistent state, consistent state with a non-default
	     action, or user semantic action that manipulated yychar.
	   - Of course, the expected token list depends on states to have
	     correct lookahead information, and it depends on the parser not
	     to perform extra reductions after fetching a lookahead from the
	     scanner and before detecting a syntax error.  Thus, state merging
	     (from LALR or IELR) and default reductions corrupt the expected
	     token list.  However, the list is correct for canonical LR with
	     one exception: it will still contain any token that will not be
	     accepted due to an error action in a later state.
	*/
	if (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken != int32(_YYSYMBOL_YYEMPTY) {
		if yyarg != 0 {
			**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(yycount)*4)) = (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken
		}
		yycount = yycount + 1
		if yyarg != 0 {
			v1 = yyarg + uintptr(1)*4
		} else {
			v1 = yyarg
		}
		yyn = s__yypcontext_expected_tokens1(tls, cc, yyctx, v1, yyargn-int32(1))
		if yyn == int32(_YYENOMEM) {
			return int32(_YYENOMEM)
		} else {
			yycount = yycount + yyn
		}
	}
	return yycount
}

func s__yy_syntax_error_arguments2(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yycount, yyn int32
	var v1 uintptr
	_, _, _ = yycount, yyn, v1
	/* Actual size of YYARG. */
	yycount = 0
	/* There are many possibilities here to consider:
	   - If this state is a consistent state with a default action, then
	     the only way this function was invoked is if the default action
	     is an error action.  In that case, don't check for expected
	     tokens because there are none.
	   - The only way there can be no lookahead present (in yychar) is if
	     this state is a consistent state with a default action.  Thus,
	     detecting the absence of a lookahead is sufficient to determine
	     that there is no unexpected or expected token to report.  In that
	     case, just report a simple "syntax error".
	   - Don't assume there isn't a lookahead just because this state is a
	     consistent state with a default action.  There might have been a
	     previous inconsistent state, consistent state with a non-default
	     action, or user semantic action that manipulated yychar.
	   - Of course, the expected token list depends on states to have
	     correct lookahead information, and it depends on the parser not
	     to perform extra reductions after fetching a lookahead from the
	     scanner and before detecting a syntax error.  Thus, state merging
	     (from LALR or IELR) and default reductions corrupt the expected
	     token list.  However, the list is correct for canonical LR with
	     one exception: it will still contain any token that will not be
	     accepted due to an error action in a later state.
	*/
	if (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken != int32(_YYSYMBOL_YYEMPTY) {
		if yyarg != 0 {
			**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(yycount)*4)) = (*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyytoken
		}
		yycount = yycount + 1
		if yyarg != 0 {
			v1 = yyarg + uintptr(1)*4
		} else {
			v1 = yyarg
		}
		yyn = s__yypcontext_expected_tokens2(tls, cc, yyctx, v1, yyargn-int32(1))
		if yyn == int32(_YYENOMEM) {
			return int32(_YYENOMEM)
		} else {
			yycount = yycount + yyn
		}
	}
	return yycount
}

// C documentation
//
//	/* Put in YYARG at most YYARGN of the expected tokens given the
//	   current YYCTX, and return the number of tokens stored in YYARG.  If
//	   YYARG is null, return the number of expected tokens (guaranteed to
//	   be less than YYNTOKENS).  Return YYENOMEM on memory exhaustion.
//	   Return 0 if there are more than YYARGN expected tokens, yet fill
//	   YYARG up to YYARGN. */
func s__yypcontext_expected_tokens(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2 int32
	_, _, _, _, _, _, _, _ = yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2
	/* Actual size of YYARG. */
	yycount = 0
	yyn = int32(cc.s__yypact[+int32(**(**_yy_state_t)(__ccgo_up((*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyyssp)))])
	if !(yyn == -libc.Int32FromInt32(1086)) {
		if yyn < 0 {
			v1 = -yyn
		} else {
			v1 = 0
		}
		/* Start YYX at -YYN if negative to avoid negative indexes in
		   YYCHECK.  In other words, skip the first -YYN actions for
		   this state because they are default actions.  */
		yyxbegin = v1
		/* Stay within bounds of both yycheck and yytname.  */
		yychecklim = int32(m_YYLAST) - yyn + int32(1)
		if yychecklim < int32(m_YYNTOKENS) {
			v2 = yychecklim
		} else {
			v2 = int32(m_YYNTOKENS)
		}
		yyxend = v2
		yyx = yyxbegin
		for {
			if !(yyx < yyxend) {
				break
			}
			if int32(cc.s__yycheck[yyx+yyn]) == yyx && yyx != int32(_YYSYMBOL_YYerror) && libc.Bool(!(libc.Int32FromInt32(0) != 0)) {
				if !(yyarg != 0) {
					yycount = yycount + 1
				} else {
					if yycount == yyargn {
						return 0
					} else {
						v1 = yycount
						yycount = yycount + 1
						**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(v1)*4)) = yyx
					}
				}
			}
			goto _3
		_3:
			;
			yyx = yyx + 1
		}
	}
	if yyarg != 0 && yycount == 0 && 0 < yyargn {
		**(**_yysymbol_kind_t1)(__ccgo_up(yyarg)) = int32(_YYSYMBOL_YYEMPTY)
	}
	return yycount
}

// C documentation
//
//	/* Put in YYARG at most YYARGN of the expected tokens given the
//	   current YYCTX, and return the number of tokens stored in YYARG.  If
//	   YYARG is null, return the number of expected tokens (guaranteed to
//	   be less than YYNTOKENS).  Return YYENOMEM on memory exhaustion.
//	   Return 0 if there are more than YYARGN expected tokens, yet fill
//	   YYARG up to YYARGN. */
func s__yypcontext_expected_tokens1(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2 int32
	_, _, _, _, _, _, _, _ = yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2
	/* Actual size of YYARG. */
	yycount = 0
	yyn = int32(cc.s__yypact1[+int32(**(**_yy_state_t)(__ccgo_up((*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyyssp)))])
	if !(yyn == -libc.Int32FromInt32(810)) {
		if yyn < 0 {
			v1 = -yyn
		} else {
			v1 = 0
		}
		/* Start YYX at -YYN if negative to avoid negative indexes in
		   YYCHECK.  In other words, skip the first -YYN actions for
		   this state because they are default actions.  */
		yyxbegin = v1
		/* Stay within bounds of both yycheck and yytname.  */
		yychecklim = int32(m_YYLAST1) - yyn + int32(1)
		if yychecklim < int32(m_YYNTOKENS1) {
			v2 = yychecklim
		} else {
			v2 = int32(m_YYNTOKENS1)
		}
		yyxend = v2
		yyx = yyxbegin
		for {
			if !(yyx < yyxend) {
				break
			}
			if int32(cc.s__yycheck1[yyx+yyn]) == yyx && yyx != int32(_YYSYMBOL_YYerror) && libc.Bool(!(libc.Int32FromInt32(0) != 0)) {
				if !(yyarg != 0) {
					yycount = yycount + 1
				} else {
					if yycount == yyargn {
						return 0
					} else {
						v1 = yycount
						yycount = yycount + 1
						**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(v1)*4)) = yyx
					}
				}
			}
			goto _3
		_3:
			;
			yyx = yyx + 1
		}
	}
	if yyarg != 0 && yycount == 0 && 0 < yyargn {
		**(**_yysymbol_kind_t1)(__ccgo_up(yyarg)) = int32(_YYSYMBOL_YYEMPTY)
	}
	return yycount
}

// C documentation
//
//	/* Put in YYARG at most YYARGN of the expected tokens given the
//	   current YYCTX, and return the number of tokens stored in YYARG.  If
//	   YYARG is null, return the number of expected tokens (guaranteed to
//	   be less than YYNTOKENS).  Return YYENOMEM on memory exhaustion.
//	   Return 0 if there are more than YYARGN expected tokens, yet fill
//	   YYARG up to YYARGN. */
func s__yypcontext_expected_tokens2(tls *libc.TLS, cc *CC, yyctx uintptr, yyarg uintptr, yyargn int32) (r int32) {
	var yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2 int32
	_, _, _, _, _, _, _, _ = yychecklim, yycount, yyn, yyx, yyxbegin, yyxend, v1, v2
	/* Actual size of YYARG. */
	yycount = 0
	yyn = int32(cc.s__yypact2[+int32(**(**_yy_state_t)(__ccgo_up((*_yypcontext_t)(unsafe.Pointer(yyctx)).Fyyssp)))])
	if !(yyn == -libc.Int32FromInt32(686)) {
		if yyn < 0 {
			v1 = -yyn
		} else {
			v1 = 0
		}
		/* Start YYX at -YYN if negative to avoid negative indexes in
		   YYCHECK.  In other words, skip the first -YYN actions for
		   this state because they are default actions.  */
		yyxbegin = v1
		/* Stay within bounds of both yycheck and yytname.  */
		yychecklim = int32(m_YYLAST2) - yyn + int32(1)
		if yychecklim < int32(m_YYNTOKENS2) {
			v2 = yychecklim
		} else {
			v2 = int32(m_YYNTOKENS2)
		}
		yyxend = v2
		yyx = yyxbegin
		for {
			if !(yyx < yyxend) {
				break
			}
			if int32(cc.s__yycheck2[yyx+yyn]) == yyx && yyx != int32(_YYSYMBOL_YYerror) && libc.Bool(!(libc.Int32FromInt32(0) != 0)) {
				if !(yyarg != 0) {
					yycount = yycount + 1
				} else {
					if yycount == yyargn {
						return 0
					} else {
						v1 = yycount
						yycount = yycount + 1
						**(**_yysymbol_kind_t1)(__ccgo_up(yyarg + uintptr(v1)*4)) = yyx
					}
				}
			}
			goto _3
		_3:
			;
			yyx = yyx + 1
		}
	}
	if yyarg != 0 && yycount == 0 && 0 < yyargn {
		**(**_yysymbol_kind_t1)(__ccgo_up(yyarg)) = int32(_YYSYMBOL_YYEMPTY)
	}
	return yycount
}

// C documentation
//
//	/* Return the length of YYSTR.  */
func s__yystrlen(tls *libc.TLS, cc *CC, yystr uintptr) (r int64) {
	var yylen int64
	_ = yylen
	yylen = 0
	for {
		if !(**(**int8)(__ccgo_up(yystr + uintptr(yylen))) != 0) {
			break
		}
		goto _1
		goto _1
	_1:
		;
		yylen = yylen + 1
	}
	return yylen
}

// C documentation
//
//	/* Return the length of YYSTR.  */
func s__yystrlen1(tls *libc.TLS, cc *CC, yystr uintptr) (r int64) {
	var yylen int64
	_ = yylen
	yylen = 0
	for {
		if !(**(**int8)(__ccgo_up(yystr + uintptr(yylen))) != 0) {
			break
		}
		goto _1
		goto _1
	_1:
		;
		yylen = yylen + 1
	}
	return yylen
}

// C documentation
//
//	/* Return the length of YYSTR.  */
func s__yystrlen2(tls *libc.TLS, cc *CC, yystr uintptr) (r int64) {
	var yylen int64
	_ = yylen
	yylen = 0
	for {
		if !(**(**int8)(__ccgo_up(yystr + uintptr(yylen))) != 0) {
			break
		}
		goto _1
		goto _1
	_1:
		;
		yylen = yylen + 1
	}
	return yylen
}

func s__yysymbol_name(tls *libc.TLS, cc *CC, yysymbol _yysymbol_kind_t1) (r uintptr) {
	return cc.s__yytname[yysymbol]
}

// C documentation
//
//	/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
//	   quotes and backslashes, so that it's suitable for yyerror.  The
//	   heuristic is that double-quoting is unnecessary unless the string
//	   contains an apostrophe, a comma, or backslash (other than
//	   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
//	   null, do not copy; instead, return the length of what the result
//	   would have been.  */
func s__yytnamerr(tls *libc.TLS, cc *CC, yyres uintptr, yystr uintptr) (r int64) {
	var yyn int64
	var yyp, v2 uintptr
	_, _, _ = yyn, yyp, v2
	if int32(**(**int8)(__ccgo_up(yystr))) == int32('"') {
		yyn = 0
		yyp = yystr
		for {
			yyp = yyp + 1
			v2 = yyp
			switch int32(**(**int8)(__ccgo_up(v2))) {
			case int32(','):
				goto _3
			case int32('\''):
				goto _4
			case int32('\\'):
				goto _5
			default:
				goto _6
			case int32('"'):
				goto _7
			}
			goto _8
		_4:
			;
		_3:
			;
			goto do_not_strip_quotes
		_5:
			;
			yyp = yyp + 1
			v2 = yyp
			if int32(**(**int8)(__ccgo_up(v2))) != int32('\\') {
				goto do_not_strip_quotes
			} else {
				goto append
			}
			goto append
		append:
			;
		_6:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = **(**int8)(__ccgo_up(yyp))
			}
			yyn = yyn + 1
			goto _8
		_7:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = int8('\000')
			}
			return yyn
		_8:
			;
			goto _1
		_1:
		}
		goto do_not_strip_quotes
	do_not_strip_quotes:
	}
	if yyres != 0 {
		return int64(s__yystpcpy(tls, cc, yyres, yystr)) - int64(yyres)
	} else {
		return s__yystrlen(tls, cc, yystr)
	}
	return r
}

// C documentation
//
//	/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
//	   quotes and backslashes, so that it's suitable for yyerror.  The
//	   heuristic is that double-quoting is unnecessary unless the string
//	   contains an apostrophe, a comma, or backslash (other than
//	   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
//	   null, do not copy; instead, return the length of what the result
//	   would have been.  */
func s__yytnamerr1(tls *libc.TLS, cc *CC, yyres uintptr, yystr uintptr) (r int64) {
	var yyn int64
	var yyp, v2 uintptr
	_, _, _ = yyn, yyp, v2
	if int32(**(**int8)(__ccgo_up(yystr))) == int32('"') {
		yyn = 0
		yyp = yystr
		for {
			yyp = yyp + 1
			v2 = yyp
			switch int32(**(**int8)(__ccgo_up(v2))) {
			case int32(','):
				goto _3
			case int32('\''):
				goto _4
			case int32('\\'):
				goto _5
			default:
				goto _6
			case int32('"'):
				goto _7
			}
			goto _8
		_4:
			;
		_3:
			;
			goto do_not_strip_quotes
		_5:
			;
			yyp = yyp + 1
			v2 = yyp
			if int32(**(**int8)(__ccgo_up(v2))) != int32('\\') {
				goto do_not_strip_quotes
			} else {
				goto append
			}
			goto append
		append:
			;
		_6:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = **(**int8)(__ccgo_up(yyp))
			}
			yyn = yyn + 1
			goto _8
		_7:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = int8('\000')
			}
			return yyn
		_8:
			;
			goto _1
		_1:
		}
		goto do_not_strip_quotes
	do_not_strip_quotes:
	}
	if yyres != 0 {
		return int64(s__yystpcpy1(tls, cc, yyres, yystr)) - int64(yyres)
	} else {
		return s__yystrlen1(tls, cc, yystr)
	}
	return r
}

// C documentation
//
//	/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
//	   quotes and backslashes, so that it's suitable for yyerror.  The
//	   heuristic is that double-quoting is unnecessary unless the string
//	   contains an apostrophe, a comma, or backslash (other than
//	   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
//	   null, do not copy; instead, return the length of what the result
//	   would have been.  */
func s__yytnamerr2(tls *libc.TLS, cc *CC, yyres uintptr, yystr uintptr) (r int64) {
	var yyn int64
	var yyp, v2 uintptr
	_, _, _ = yyn, yyp, v2
	if int32(**(**int8)(__ccgo_up(yystr))) == int32('"') {
		yyn = 0
		yyp = yystr
		for {
			yyp = yyp + 1
			v2 = yyp
			switch int32(**(**int8)(__ccgo_up(v2))) {
			case int32(','):
				goto _3
			case int32('\''):
				goto _4
			case int32('\\'):
				goto _5
			default:
				goto _6
			case int32('"'):
				goto _7
			}
			goto _8
		_4:
			;
		_3:
			;
			goto do_not_strip_quotes
		_5:
			;
			yyp = yyp + 1
			v2 = yyp
			if int32(**(**int8)(__ccgo_up(v2))) != int32('\\') {
				goto do_not_strip_quotes
			} else {
				goto append
			}
			goto append
		append:
			;
		_6:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = **(**int8)(__ccgo_up(yyp))
			}
			yyn = yyn + 1
			goto _8
		_7:
			;
			if yyres != 0 {
				**(**int8)(__ccgo_up(yyres + uintptr(yyn))) = int8('\000')
			}
			return yyn
		_8:
			;
			goto _1
		_1:
		}
		goto do_not_strip_quotes
	do_not_strip_quotes:
	}
	if yyres != 0 {
		return int64(s__yystpcpy2(tls, cc, yyres, yystr)) - int64(yyres)
	} else {
		return s__yystrlen2(tls, cc, yystr)
	}
	return r
}

func x__basicyylex(tls *libc.TLS, cc *CC, yval uintptr) (r int32) {
	var c, v1 int32
	_, _ = c, v1
	v1 = s__getBasicToken(tls, cc, (*_Module)(unsafe.Pointer(cc.x__current)).FLptr, yval)
	c = v1
	cc.x__saved_basicyychar = v1
	if c == int32(_BAS_EOF) || c == -int32(1) {
		return 0
	}
	return c
}

func x__spinyylex(tls *libc.TLS, cc *CC, yval uintptr) (r int32) {
	var c, v1 int32
	_, _ = c, v1
	v1 = x__getSpinToken(tls, cc, (*_Module)(unsafe.Pointer(cc.x__current)).FLptr, yval)
	c = v1
	cc.x__saved_spinyychar = v1
	if c == int32(_SP_EOF) {
		return 0
	}
	return c
}
