// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (linux && amd64) || (windows && amd64)

package flexcc

import (
	"unsafe"

	"modernc.org/libc"
)

type _Function = struct {
	Fnext                  uintptr
	Fname                  uintptr
	Fuser_name             uintptr
	Fdecl                  uintptr
	Foveralltype           uintptr
	Fannotations           uintptr
	Fdoccomment            uintptr
	Fnumparams             int32
	Fparams                uintptr
	Fdefaultparams         uintptr
	Fnumlocals             int32
	Flocals                uintptr
	Fbody                  uintptr
	Fnumresults            int32
	Fresultexpr            uintptr
	Fextradecl             uintptr
	Fparmarray             uintptr
	Fresult_in_parmarray   int32
	Flocalarray            uintptr
	Flocalarray_len        int32
	Flocalsyms             _SymbolTable
	Fmodule                uintptr
	Fspecialfunc           uintptr
	FlocalsUsedInAsm       _uint64_t
	Foptimize_flags        int32
	Fwarn_flags            int32
	F__ccgo1248            uint32
	Fattributes            uint32
	FcallSites             uint32
	FvisitFlag             uint32
	FtempStackSize         uint32
	Fbedata                uintptr
	Fclosure               uintptr
	Fcaller                uintptr
	Flanguage              int32
	Flang_processed        int8
	Flocal_var_counter     int32
	Fmax_local_var_counter int32
	Fsym_funcptr           uintptr
	Fmethod_index          int32
}

type _LexStream = struct {
	Fptr               uintptr
	Farg               uintptr
	Fmaxbytes          _size_t
	Fgetcf             uintptr
	Fungot             [16]int32
	Fungot_ptr         int32
	Fblock_type        int32
	Fsave_block        int32
	Fblock_firstline   int32
	Findent            [64]int32
	Findentsp          int32
	Fpending_indent    int32
	Feoln              int32
	Feof               int32
	FfirstNonBlank     int32
	FlastGlobal        uintptr
	FcolCounter        int32
	FlineCounter       int32
	FfileName          uintptr
	Flanguage          int32
	Flanguage_version  int32
	FsawCr             int32
	FpendingLine       int32
	FcurLine           _Flexbuf
	FlineInfo          _Flexbuf
	Fflags             uint32
	FsawInstruction    int8
	FsawDataDirective  int8
	Fbacktick_state    int8
	Fmixed_tab_warning int8
	Findent_saw_spaces int8
	Findent_saw_tabs   int8
	Fif_nest           int32
	FexprSp            int32
	FexprStateStack    [64]_SpinExprState1
}

type _Module = struct {
	Fnext               uintptr
	Fconblock           uintptr
	Fdatblock           uintptr
	Fpendingvarblock    uintptr
	Ffinalvarblock      uintptr
	Fobjblock           uintptr
	Ffuncblock          uintptr
	Ftopcomment         uintptr
	Fbotcomment         uintptr
	Fobjparams          uintptr
	Fdatblock_tail      uintptr
	Fconblock_tail      uintptr
	Fparse_tail         uintptr
	Fdatannotations     uintptr
	Fbas_data           uintptr
	Fbas_data_tail      uintptr
	Ffunctions          uintptr
	FLptr               uintptr
	Fobjsyms            _SymbolTable
	Fname_space         uintptr
	Fvarsize            int32
	Fdatsize            int32
	Ffullname           uintptr
	Fbasename           uintptr
	Fclassname          uintptr
	Foutfilename        uintptr
	Fdatname            uintptr
	FvisitFlag          uint32
	Fall_visitflags     uint32
	FpasmLabels         int8
	FvolatileVariables  int8
	FsawToken           int8
	FcodeCog            int8
	FdatHasCode         int8
	FgasPasm            int8
	FisUnion            int8
	FisInterface        int8
	FdefaultPrivate     int8
	FlongOnly           int8
	FfromUsing          int8
	FisPacked           int8
	Fbedata             uintptr
	FmainLanguage       int32
	FcurLanguage        int32
	FcurLangVersion     int32
	Fbody               uintptr
	Fsubclasses         uintptr
	Fsuperclass         uintptr
	Fparent             uintptr
	Ftype1              uintptr
	Fvarsize_used       int32
	Fvarsize_used_valid uint8
}

type _NuIrLabel = struct {
	Foffset         int32
	Fnum            int32
	Fname           [16]int8
	Fcomefrom_valid uint8
	Fcomefrom       uintptr
	Fseqno          uint32
}

type _OPTAB = struct {
	Fop   int8
	Fprec int8
	Fskip int8
}

type _fmtspecs = struct {
	Fspec  int8
	Ffunc1 __Fmt_func
}

type _mz_zip_archive_file_stat = struct {
	Fm_file_index       _mz_uint32
	Fm_central_dir_ofs  _mz_uint64
	Fm_version_made_by  _mz_uint16
	Fm_version_needed   _mz_uint16
	Fm_bit_flag         _mz_uint16
	Fm_method           _mz_uint16
	Fm_time             _time_t
	Fm_crc32            _mz_uint32
	Fm_comp_size        _mz_uint64
	Fm_uncomp_size      _mz_uint64
	Fm_internal_attr    _mz_uint16
	Fm_external_attr    _mz_uint32
	Fm_local_header_ofs _mz_uint64
	Fm_comment_size     _mz_uint32
	Fm_is_directory     _mz_bool
	Fm_is_encrypted     _mz_bool
	Fm_is_supported     _mz_bool
	Fm_filename         [512]int8
	Fm_comment          [512]int8
}

func s__AddStructBody(tls *libc.TLS, cc *CC, C uintptr, body uintptr) {
	var is_union int32
	_ = is_union
	if body != 0 {
		is_union = int32((*_Module)(unsafe.Pointer(C)).FisUnion)
		s__DeclareCMemberVariables(tls, cc, C, body, is_union)
		x__DeclareMemberVariables(tls, cc, C)
	}
}

func s__IsHiddenIdent(tls *libc.TLS, cc *CC, ident uintptr) (r uint8) {
	if ident != 0 && (*_AST)(unsafe.Pointer(ident)).Fkind == int32(_AST_IDENTIFIER) && int32(**(**int8)(__ccgo_up(*(*uintptr)(unsafe.Pointer(ident + 8))))) == int32('^') {
		/* special bitfield holder identifier; skip */
		return libc.BoolUint8(m_true != 0)
	}
	return libc.BoolUint8(m_false != 0)
}

func s__IsTemporaryLabel(tls *libc.TLS, cc *CC, op uintptr) (r uint8) {
	var name uintptr
	_ = name
	name = (*_Operand)(unsafe.Pointer(op)).Fname
	if name != 0 && (int32(**(**int8)(__ccgo_up(name))) == int32('L') && int32(**(**int8)(__ccgo_up(name + 1))) == int32('_') && int32(**(**int8)(__ccgo_up(name + 2))) == int32('_')) {
		return libc.BoolUint8(m_true != 0)
	}
	return libc.BoolUint8(m_false != 0)
}

// C documentation
//
//	/* turn an expression list into an expression */
func s__MakeCaseTest(tls *libc.TLS, cc *CC, ident uintptr, expr uintptr) (r1 uintptr) {
	var left, r, r2, right, s uintptr
	var lval, rval _int32_t
	_, _, _, _, _, _, _ = left, lval, r, r2, right, rval, s
	if !(expr != 0) {
		return libc.UintptrFromInt32(0)
	}
	if (*_AST)(unsafe.Pointer(expr)).Fkind == int32(_AST_RANGE) {
		if x__IsConstExpr(tls, cc, (*_AST)(unsafe.Pointer(expr)).Fleft) != 0 && x__IsConstExpr(tls, cc, (*_AST)(unsafe.Pointer(expr)).Fright) != 0 {
			left = (*_AST)(unsafe.Pointer(expr)).Fleft
			right = (*_AST)(unsafe.Pointer(expr)).Fright
			lval = int32(x__EvalConstExpr(tls, cc, left))
			rval = int32(x__EvalConstExpr(tls, cc, right))
			if lval > rval {
				left = (*_AST)(unsafe.Pointer(expr)).Fright
				right = (*_AST)(unsafe.Pointer(expr)).Fleft
			}
			r = x__AstOperator(tls, cc, int32(_K_GE), ident, left)
			r2 = x__AstOperator(tls, cc, int32(_K_LE), ident, right)
			r = x__AstOperator(tls, cc, int32(_K_BOOL_AND), r, r2)
		} else {
			r = x__NewAST(tls, cc, int32(_AST_ISBETWEEN), ident, expr)
		}
		return r
	}
	if (*_AST)(unsafe.Pointer(expr)).Fkind == int32(_AST_EXPRLIST) {
		r = s__MakeCaseTest(tls, cc, ident, (*_AST)(unsafe.Pointer(expr)).Fleft)
		if (*_AST)(unsafe.Pointer(expr)).Fright != 0 {
			r2 = s__MakeCaseTest(tls, cc, ident, (*_AST)(unsafe.Pointer(expr)).Fright)
			r = x__AstOperator(tls, cc, int32(_K_BOOL_OR), r, r2)
		}
		return r
	}
	if (*_AST)(unsafe.Pointer(expr)).Fkind == int32(_AST_STRING) {
		s = *(*uintptr)(unsafe.Pointer(expr + 8))
		r = x__AstOperator(tls, cc, int32(_K_EQ), ident, x__AstInteger(tls, cc, int64(**(**int8)(__ccgo_up(s)))))
		s = s + 1
		for **(**int8)(__ccgo_up(s)) != 0 {
			r = x__AstOperator(tls, cc, int32(_K_BOOL_OR), r, x__AstOperator(tls, cc, int32(_K_EQ), ident, x__AstInteger(tls, cc, int64(**(**int8)(__ccgo_up(s))))))
			s = s + 1
		}
		return r
	}
	return x__AstOperator(tls, cc, int32(_K_EQ), ident, expr)
}

// C documentation
//
//	// utility: decide if two lines are the same
func s__MatchLines(tls *libc.TLS, cc *CC, line1 uintptr, line2 uintptr) (r int32) {
	if !(line1 != 0) || !(line2 != 0) {
		return 0
	}
	if int64(line2)-int64(line1) < int64(12) {
		return 0
	}
	// ignore the addresses, just look at the hex output
	// addresses are 5 + 1 + 3 + 1 bytes
	// hex are 12 bytes
	if !(libc.Xstrncmp(tls, line1+uintptr(m_LINE_ADDRLEN), line2+uintptr(m_LINE_ADDRLEN), uint64(m_LINE_HEXLEN)) != 0) {
		// OK, they may match
		// make sure neither line ends with a '|'
		if int32(**(**int8)(__ccgo_up(line1 + uintptr(libc.Int32FromInt32(m_LINE_ADDRLEN)+libc.Int32FromInt32(m_LINE_HEXLEN))))) != int32('\n') {
			return 0
		}
		if int32(**(**int8)(__ccgo_up(line2 + uintptr(libc.Int32FromInt32(m_LINE_ADDRLEN)+libc.Int32FromInt32(m_LINE_HEXLEN))))) != int32('\n') {
			return 0
		}
		return int32(1)
	}
	return 0
}

func s__QuotedName(tls *libc.TLS, cc *CC, orig_name uintptr) (r uintptr) {
	var c, i, v2 int32
	var name, v1 uintptr
	_, _, _, _, _ = c, i, name, v1, v2
	name = orig_name
	i = 0
	for i < libc.Int32FromInt32(m_MAX_BUF)-libc.Int32FromInt32(2) {
		v1 = name
		name = name + 1
		c = int32(**(**int8)(__ccgo_up(v1)))
		if c == 0 {
			break
		}
		switch c {
		case int32('!'):
			fallthrough
		case int32('$'):
			fallthrough
		case int32('%'):
			fallthrough
		case int32('#'):
			v2 = i
			i = i + 1
			cc.s__buf2[v2] = int8('`')
		case int32(' '):
			fallthrough
		case int32('\n'):
			return orig_name
		default:
			break
		}
		v2 = i
		i = i + 1
		cc.s__buf2[v2] = int8(c)
	}
	v2 = i
	i = i + 1
	cc.s__buf2[v2] = 0
	return uintptr(unsafe.Pointer(&cc.s__buf2))
}

// C documentation
//
//	// declare a Spin structure
func s__SpinDeclareStruct(tls *libc.TLS, cc *CC, ident uintptr, defs uintptr) {
	var P, classname, item, newobj uintptr
	_, _, _, _ = P, classname, item, newobj
	classname = x__GetUserIdentifierName(tls, cc, ident)
	P = x__NewModule(tls, cc, classname, (*_Module)(unsafe.Pointer(cc.x__current)).FcurLanguage)
	newobj = x__NewAbstractObject(tls, cc, ident, libc.UintptrFromInt32(0), 0)
	*(*uintptr)(unsafe.Pointer(newobj + 8)) = P
	x__AddSymbol(tls, cc, cc.x__currentTypes, classname, int32(_SYM_TYPEDEF), newobj, libc.UintptrFromInt32(0))
	if P != cc.x__current {
		(*_Module)(unsafe.Pointer(P)).FLptr = (*_Module)(unsafe.Pointer(cc.x__current)).FLptr
		(*_Module)(unsafe.Pointer(P)).Fsubclasses = (*_Module)(unsafe.Pointer(cc.x__current)).Fsubclasses
		(*_Module)(unsafe.Pointer(cc.x__current)).Fsubclasses = P
		(*_Module)(unsafe.Pointer(P)).Fsuperclass = cc.x__current
		(*_Module)(unsafe.Pointer(P)).Ffullname = (*_Module)(unsafe.Pointer(cc.x__current)).Ffullname // for finding "class using"
		*(*uintptr)(unsafe.Pointer(newobj + 8)) = P
		(*_Module)(unsafe.Pointer(P)).FisPacked = int8(1)
		/* import parent's symbols into P */
		(*_Module)(unsafe.Pointer(P)).Fobjsyms.Fnext = cc.x__current + 144
		x__AddSymbol(tls, cc, cc.x__current+144, classname, int32(_SYM_TYPEDEF), newobj, libc.UintptrFromInt32(0))
	}
	x__PushCurrentModule(tls, cc)
	cc.x__current = P
	/* declare member variables */
	for defs != 0 {
		item = (*_AST)(unsafe.Pointer(defs)).Fleft
		defs = (*_AST)(unsafe.Pointer(defs)).Fright
		for item != 0 && (*_AST)(unsafe.Pointer(item)).Fkind == int32(_AST_COMMENTEDNODE) {
			item = (*_AST)(unsafe.Pointer(item)).Fleft
		}
		x__DeclareBASICMemberVariables(tls, cc, item)
	}
	x__PopCurrentModule(tls, cc)
}

func s__TransformLongMove(tls *libc.TLS, cc *CC, astptr uintptr, ast uintptr) (r uint8) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var assign, count, dst, dst_id, dst_tmp, dsttab, sequence, src, src_id, src_tmp, srctab, symd, syms uintptr
	var dstarray, dstoff, i, n, srcarray, srcoff, v1 int32
	var _ /* saveinfo at bp+0 */ _ASTReportInfo
	_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ = assign, count, dst, dst_id, dst_tmp, dstarray, dstoff, dsttab, i, n, sequence, src, src_id, src_tmp, srcarray, srcoff, srctab, symd, syms, v1
	srcarray = 0
	dstarray = 0
	ast = (*_AST)(unsafe.Pointer(ast)).Fright // ast->left is the longmove function
	dst = (*_AST)(unsafe.Pointer(ast)).Fleft
	ast = (*_AST)(unsafe.Pointer(ast)).Fright
	if !(ast != 0) || !(dst != 0) {
		return libc.BoolUint8(m_false != 0)
	}
	src = (*_AST)(unsafe.Pointer(ast)).Fleft
	ast = (*_AST)(unsafe.Pointer(ast)).Fright
	if !(ast != 0) || !(src != 0) {
		return libc.BoolUint8(m_false != 0)
	}
	count = (*_AST)(unsafe.Pointer(ast)).Fleft
	ast = (*_AST)(unsafe.Pointer(ast)).Fright
	if ast != 0 || !(count != 0) {
		return libc.BoolUint8(m_false != 0)
	}
	if !(x__IsConstExpr(tls, cc, count) != 0) {
		return libc.BoolUint8(m_false != 0)
	}
	n = int32(x__EvalConstExpr(tls, cc, count))
	if cc.x__gl_output == int32(m_OUTPUT_BYTECODE) && cc.x__gl_interp_kind != int32(m_INTERP_KIND_NUCODE) {
		v1 = int32(m_LONGMOVE_THRESHOLD_BYTECODE)
	} else {
		v1 = int32(m_LONGMOVE_THRESHOLD)
	}
	if n > v1 || n <= 0 {
		return libc.BoolUint8(m_false != 0)
	}
	// check src and dst
	if (*_AST)(unsafe.Pointer(src)).Fkind != int32(_AST_ADDROF) && (*_AST)(unsafe.Pointer(src)).Fkind != int32(_AST_ABSADDROF) {
		return libc.BoolUint8(m_false != 0)
	}
	src = (*_AST)(unsafe.Pointer(src)).Fleft
	if !((*_AST)(unsafe.Pointer(src)).Fkind == int32(_AST_IDENTIFIER) || (*_AST)(unsafe.Pointer(src)).Fkind == int32(_AST_LOCAL_IDENTIFIER)) {
		return libc.BoolUint8(m_false != 0)
	}
	if (*_AST)(unsafe.Pointer(dst)).Fkind != int32(_AST_ADDROF) && (*_AST)(unsafe.Pointer(dst)).Fkind != int32(_AST_ABSADDROF) {
		return libc.BoolUint8(m_false != 0)
	}
	dst = (*_AST)(unsafe.Pointer(dst)).Fleft
	if !((*_AST)(unsafe.Pointer(dst)).Fkind == int32(_AST_IDENTIFIER) || (*_AST)(unsafe.Pointer(dst)).Fkind == int32(_AST_LOCAL_IDENTIFIER)) {
		return libc.BoolUint8(m_false != 0)
	}
	// ok, we have the pattern we like
	syms = x__LookupAstSymbol(tls, cc, src, libc.UintptrFromInt32(0))
	symd = x__LookupAstSymbol(tls, cc, dst, libc.UintptrFromInt32(0))
	if !(syms != 0) || !(symd != 0) {
		return libc.BoolUint8(m_false != 0)
	}
	switch (*_Symbol)(unsafe.Pointer(syms)).Fkind {
	case int32(_SYM_LABEL):
		srcarray = int32(m_true)
		// fall through
		fallthrough
	case int32(_SYM_VARIABLE):
		srctab = cc.x__current + 144
	case int32(_SYM_RESULT):
		fallthrough
	case int32(_SYM_PARAMETER):
		fallthrough
	case int32(_SYM_LOCALVAR):
		srctab = cc.x__curfunc + 160
	default:
		return libc.BoolUint8(m_false != 0)
	}
	switch (*_Symbol)(unsafe.Pointer(symd)).Fkind {
	case int32(_SYM_LABEL):
		dstarray = int32(m_true)
		// fall through
		fallthrough
	case int32(_SYM_VARIABLE):
		dsttab = cc.x__current + 144
	case int32(_SYM_RESULT):
		fallthrough
	case int32(_SYM_PARAMETER):
		fallthrough
	case int32(_SYM_LOCALVAR):
		dsttab = cc.x__curfunc + 160
	default:
		return libc.BoolUint8(m_false != 0)
	}
	if x__IsArrayType(tls, cc, x__ExprType(tls, cc, src)) != 0 {
		srcarray = x__TypeSize(tls, cc, x__ExprType(tls, cc, src)) / int32(m_LONG_SIZE)
	}
	if x__IsArrayType(tls, cc, x__ExprType(tls, cc, dst)) != 0 {
		dstarray = x__TypeSize(tls, cc, x__ExprType(tls, cc, dst)) / int32(m_LONG_SIZE)
	}
	x__AstReportAs(tls, cc, dst, bp)
	srcoff = (*_Symbol)(unsafe.Pointer(syms)).Foffset
	dstoff = (*_Symbol)(unsafe.Pointer(symd)).Foffset
	sequence = libc.UintptrFromInt32(0)
	i = 0
	for {
		src_id = x__AstIdentifier(tls, cc, (*_Symbol)(unsafe.Pointer(syms)).Four_name)
		dst_id = x__AstIdentifier(tls, cc, (*_Symbol)(unsafe.Pointer(symd)).Four_name)
		if srcarray != 0 {
			src_tmp = x__NewAST(tls, cc, int32(_AST_ARRAYREF), src_id, x__AstInteger(tls, cc, int64(i)))
		} else {
			src_tmp = src_id
		}
		if dstarray != 0 {
			dst_tmp = x__NewAST(tls, cc, int32(_AST_ARRAYREF), dst_id, x__AstInteger(tls, cc, int64(i)))
		} else {
			dst_tmp = dst_id
		}
		i = i + 1
		assign = x__AstAssign(tls, cc, dst_tmp, src_tmp)
		sequence = x__AddToList(tls, cc, sequence, x__NewAST(tls, cc, int32(_AST_SEQUENCE), assign, libc.UintptrFromInt32(0)))
		n = n - 1
		if n == 0 {
			break
		}
		srcoff = srcoff + int32(4)
		dstoff = dstoff + int32(4)
		if !(dstarray != 0) {
			symd = x__FindSymbolByOffsetAndKind(tls, cc, dsttab, dstoff, (*_Symbol)(unsafe.Pointer(symd)).Fkind)
		}
		if !(srcarray != 0) {
			syms = x__FindSymbolByOffsetAndKind(tls, cc, srctab, srcoff, (*_Symbol)(unsafe.Pointer(syms)).Fkind)
		}
		if !(symd != 0) || !(syms != 0) {
			x__AstReportDone(tls, cc, bp)
			return libc.BoolUint8(m_false != 0)
		}
		srcoff = (*_Symbol)(unsafe.Pointer(syms)).Foffset
		dstoff = (*_Symbol)(unsafe.Pointer(symd)).Foffset
		goto _2
	_2:
	}
	**(**uintptr)(__ccgo_up(astptr)) = sequence
	/* the longmove probably indicates a COG will be reading these
	   variables */
	(*_Module)(unsafe.Pointer(cc.x__current)).FvolatileVariables = int8(1)
	x__AstReportDone(tls, cc, bp)
	return libc.BoolUint8(m_true != 0)
}

func s___fmt_char(tls *libc.TLS, cc *CC, pi uintptr, args uintptr) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var _ /* buf at bp+0 */ [2]int8
	if int32(uint32(*(*uint8)(unsafe.Pointer(pi + 16))&0x10>>4)) != 0 {
		return s___fmt_wchar(tls, cc, pi, args)
	}
	(*_Printf_info)(unsafe.Pointer(pi)).Fpad = int32(' ')
	(**(**[2]int8)(__ccgo_up(bp)))[0] = int8(libc.VaInt32(&**(**_va_list)(__ccgo_up(args))))
	(**(**[2]int8)(__ccgo_up(bp)))[int32(1)] = 0
	return s___fmtputstr(tls, cc, bp, pi)
}

func s__de_stringize(tls *libc.TLS, cc *CC, in uintptr, out uintptr) (r uintptr) {
	/*
	 * Make token sequence from a string literal for _Pragma() operator.
	 */
	var c, c1, v1 int32
	var in_p, v2, v4 uintptr
	var v3 bool
	_, _, _, _, _, _, _ = c, c1, in_p, v1, v2, v3, v4
	in_p = in
	if int32(**(**int8)(__ccgo_up(in_p))) == int32('L') {
		in_p = in_p + 1
	} /* Skip 'L' prefix      */
	for {
		in_p = in_p + 1
		v2 = in_p
		v1 = int32(**(**int8)(__ccgo_up(v2)))
		c = v1
		if !(v1 != int32('\000')) {
			break
		}
		if v3 = c == int32('\\'); v3 {
			c1 = int32(**(**int8)(__ccgo_up(in_p + libc.UintptrFromInt32(1))))
		}
		if v3 && (c1 == libc.Int32FromUint8('\\') || c1 == int32('"')) {
			in_p = in_p + 1
			v4 = in_p
			c = int32(**(**int8)(__ccgo_up(v4)))
		} /* "De-escape" escape sequence  */
		v2 = out
		out = out + 1
		**(**int8)(__ccgo_up(v2)) = int8(c)
	}
	out = out - 1
	v2 = out
	**(**int8)(__ccgo_up(v2)) = int8('\000') /* Remove the closing '"'       */
	return out
}

// C documentation
//
//	//
//	// output the sign and any hex digits required
//	// if buf is NULL print using pi
//	// otherwise put into buf
//	// returns number of bytes output, or -1 if an error happens
//	//
func s__emitsign(tls *libc.TLS, cc *CC, pi uintptr, buf uintptr, sign int32, hex int32) (r1 int32) {
	var r int32
	var v1 uintptr
	_, _ = r, v1
	r = 0
	if sign != 0 {
		if buf != 0 {
			v1 = buf
			buf = buf + 1
			**(**int8)(__ccgo_up(v1)) = int8(sign)
		} else {
			if s___fmtputc(tls, cc, sign, pi) < 0 {
				return -int32(1)
			}
		}
		r = r + 1
	}
	if hex != 0 {
		if buf != 0 {
			v1 = buf
			buf = buf + 1
			**(**int8)(__ccgo_up(v1)) = int8('0')
			v1 = buf
			buf = buf + 1
			**(**int8)(__ccgo_up(v1)) = int8(hex)
		} else {
			if s___fmtputc(tls, cc, int32('0'), pi) < 0 {
				return -int32(1)
			}
			if s___fmtputc(tls, cc, hex, pi) < 0 {
				return -int32(1)
			}
		}
		r = r + int32(2)
	}
	return r
}

// C documentation
//
//	// duplicate a file name, possibly quoted
func s__getFileName(tls *libc.TLS, cc *CC, name uintptr, orig uintptr) (r uintptr) {
	var ptr uintptr
	var siz _size_t
	_, _ = ptr, siz
	ptr = libc.Xstrdup(tls, name)
	if int32(**(**int8)(__ccgo_up(ptr))) == int32('"') {
		siz = libc.Xstrlen(tls, ptr+uintptr(1))
		if siz > uint64(1) {
			libc.Xmemmove(tls, ptr, ptr+uintptr(1), siz-uint64(1))
			**(**int8)(__ccgo_up(ptr + uintptr(siz-uint64(2)))) = 0
		}
	}
	// special case: if the original file name matches the last part
	// of the new one, just return the original
	if !(libc.Xstrchr(tls, orig, int32('/')) != 0) && libc.Xstrlen(tls, ptr) > libc.Xstrlen(tls, orig) {
		siz = libc.Xstrlen(tls, ptr) - libc.Xstrlen(tls, orig)
		if int32(**(**int8)(__ccgo_up(ptr + uintptr(siz-uint64(1))))) == int32('/') && !(libc.Xstrcmp(tls, ptr+uintptr(siz), orig) != 0) {
			libc.Xmemmove(tls, ptr, ptr+uintptr(siz), libc.Xstrlen(tls, orig)+uint64(1))
		}
	}
	return ptr
}

func s__md_quote(tls *libc.TLS, cc *CC, output uintptr) (r uintptr) {
	/*
	 * 'Quote' $, tab and space.
	 * This function was written referring to GCC V.3.2 source.
	 */
	var p, q, v10 uintptr
	_, _, _ = p, q, v10
	p = cc.s__mkdep_target
	for {
		if !(**(**int8)(__ccgo_up(p)) != 0) {
			break
		}
		switch int32(**(**int8)(__ccgo_up(p))) {
		case int32('\t'):
			goto _2
		case int32(' '):
			goto _3
		case int32('$'):
			goto _4
		default:
			goto _5
		}
		goto _6
	_3:
		;
	_2:
		;
		/* GNU-make treats backslash-space sequence peculiarly  */
		q = p - uintptr(1)
	_9:
		;
		if !(cc.s__mkdep_target <= q && int32(**(**int8)(__ccgo_up(q))) == int32('\\')) {
			goto _7
		}
		v10 = output
		output = output + 1
		**(**int8)(__ccgo_up(v10)) = int8('\\')
		goto _8
	_8:
		;
		q = q - 1
		goto _9
		goto _7
	_7:
		;
		v10 = output
		output = output + 1
		**(**int8)(__ccgo_up(v10)) = int8('\\')
		goto _6
	_4:
		;
		v10 = output
		output = output + 1
		**(**int8)(__ccgo_up(v10)) = int8('$')
		goto _6
	_5:
		;
		goto _6
	_6:
		;
		**(**int8)(__ccgo_up(output)) = **(**int8)(__ccgo_up(p))
		goto _1
	_1:
		;
		p = p + 1
		output = output + 1
	}
	**(**int8)(__ccgo_up(output)) = int8('\000')
	return output
}

func s__mem_putc(tls *libc.TLS, cc *CC, c int32, od _OUTDEST) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var _ /* string at bp+0 */ [1]int8
	(**(**[1]int8)(__ccgo_up(bp)))[0] = int8(c)
	if s__append_to_buffer(tls, cc, uintptr(unsafe.Pointer(&cc.s__mem_buffers))+uintptr(od)*32, bp, uint64(1)) != libc.UintptrFromInt32(0) {
		return 0
	} else {
		return libc.BoolInt32(!(libc.Int32FromInt32(0) != 0))
	}
	return r
}

func s__mz_zip_writer_write_zeros(tls *libc.TLS, cc *CC, pZip1 uintptr, cur_file_ofs _mz_uint64, n _mz_uint32) (r _mz_bool) {
	bp := tls.Alloc(4096)
	defer tls.Free(4096)
	var s _mz_uint32
	var v1 uint64
	var v3 uintptr
	var v4 _mz_bool
	var _ /* buf at bp+0 */ [4096]int8
	_, _, _, _ = s, v1, v3, v4
	if libc.Uint64FromInt64(4096) < uint64(n) {
		v1 = libc.Uint64FromInt64(4096)
	} else {
		v1 = uint64(n)
	}
	libc.Xmemset(tls, bp, 0, v1)
	for n != 0 {
		if libc.Uint64FromInt64(4096) < uint64(n) {
			v1 = libc.Uint64FromInt64(4096)
		} else {
			v1 = uint64(n)
		}
		s = uint32(v1)
		if (*(*func(*libc.TLS, *CC, uintptr, _mz_uint64, uintptr, _size_t) _size_t)(unsafe.Pointer(&struct{ uintptr }{(*_mz_zip_archive)(unsafe.Pointer(pZip1)).Fm_pWrite})))(tls, cc, (*_mz_zip_archive)(unsafe.Pointer(pZip1)).Fm_pIO_opaque, cur_file_ofs, bp, uint64(s)) != uint64(s) {
			v3 = pZip1
			if v3 != 0 {
				(*_mz_zip_archive)(unsafe.Pointer(v3)).Fm_last_error = int32(_MZ_ZIP_FILE_WRITE_FAILED)
			}
			v4 = libc.Int32FromInt32(m_MZ_FALSE)
			goto _5
		_5:
			return v4
		}
		cur_file_ofs = cur_file_ofs + uint64(s)
		n = n - s
	}
	return libc.Int32FromInt32(m_MZ_TRUE)
}

func s__parse_getincludestring(tls *libc.TLS, cc *CC, P uintptr) (r uintptr) {
	var endchar int8
	var ptr, start, v1 uintptr
	_, _, _, _ = endchar, ptr, start, v1
	s__parse_skipspaces(tls, cc, P)
	ptr = (*_ParseState)(unsafe.Pointer(P)).Fstr
	if int32(**(**int8)(__ccgo_up(ptr))) == int32('"') {
		endchar = int8('"')
	} else {
		if int32(**(**int8)(__ccgo_up(ptr))) == int32('<') {
			endchar = int8('>')
		} else {
			return libc.UintptrFromInt32(0)
		}
	}
	ptr = ptr + 1
	start = ptr
	ptr = s__skip_quoted_string(tls, cc, ptr, int32(endchar))
	if !(**(**int8)(__ccgo_up(ptr)) != 0) {
		return libc.UintptrFromInt32(0)
	}
	(*_ParseState)(unsafe.Pointer(P)).Fc = 0 //*ptr;
	v1 = ptr
	ptr = ptr + 1
	**(**int8)(__ccgo_up(v1)) = 0
	ptr = ptr + 1
	for **(**int8)(__ccgo_up(ptr)) != 0 && int32(**(**int8)(__ccgo_up(ptr))) != int32('\n') {
		ptr = ptr + 1
	}
	if **(**int8)(__ccgo_up(ptr)) != 0 {
		ptr = ptr + 1
	}
	(*_ParseState)(unsafe.Pointer(P)).Fsave = ptr
	return start
}

func s__parse_restofline(tls *libc.TLS, cc *CC, pp uintptr, P uintptr) (r uintptr) {
	var len1 _size_t
	var ptr, ret uintptr
	_, _, _ = len1, ptr, ret
	if (*_ParseState)(unsafe.Pointer(P)).Fsave != 0 {
		**(**int8)(__ccgo_up((*_ParseState)(unsafe.Pointer(P)).Fsave)) = int8((*_ParseState)(unsafe.Pointer(P)).Fc)
		ptr = (*_ParseState)(unsafe.Pointer(P)).Fsave
	} else {
		ptr = (*_ParseState)(unsafe.Pointer(P)).Fstr
	}
	ret = ptr
	for **(**int8)(__ccgo_up(ptr)) != 0 && int32(**(**int8)(__ccgo_up(ptr))) != int32('\n') {
		ptr = ptr + 1
	}
	if **(**int8)(__ccgo_up(ptr)) != 0 {
		(*_ParseState)(unsafe.Pointer(P)).Fc = int32(**(**int8)(__ccgo_up(ptr)))
		**(**int8)(__ccgo_up(ptr)) = 0
		(*_ParseState)(unsafe.Pointer(P)).Fsave = ptr
	} else {
		(*_ParseState)(unsafe.Pointer(P)).Fsave = libc.UintptrFromInt32(0)
	}
	// ignore line comments
	if (*_preprocess)(unsafe.Pointer(pp)).Flinecomment != 0 {
		len1 = libc.Xstrlen(tls, (*_preprocess)(unsafe.Pointer(pp)).Flinecomment)
		ptr = ret
		for **(**int8)(__ccgo_up(ptr)) != 0 && 0 != libc.Xstrncmp(tls, ptr, (*_preprocess)(unsafe.Pointer(pp)).Flinecomment, len1) {
			ptr = ptr + 1
		}
		**(**int8)(__ccgo_up(ptr)) = 0
	}
	(*_ParseState)(unsafe.Pointer(P)).Fstr = ret
	return (*_ParseState)(unsafe.Pointer(P)).Fstr
}

// C documentation
//
//	// parse the printf flags (like 0, -, etc)
//	// also initializes the width and prec fields
func s__parseflags(tls *libc.TLS, cc *CC, fmt uintptr, pi uintptr) (r uintptr) {
	var c int32
	var v2 uintptr
	_, _ = c, v2
	(*_Printf_info)(unsafe.Pointer(pi)).Fwidth = 0
	(*_Printf_info)(unsafe.Pointer(pi)).Fprec = -int32(1)
	(*_Printf_info)(unsafe.Pointer(pi)).Fpad = int32(' ')
	libc.SetBitFieldPtr8Uint32(pi+16, libc.AssignBitFieldPtr8Uint32(pi+16, libc.AssignBitFieldPtr8Uint32(pi+16, libc.AssignBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(0), 1, 1, 0x2), 1, 3, 0x8), 1, 0, 0x1), 2, 0x4)
	libc.SetBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(0), 4, 0x10)
	for {
		v2 = fmt
		fmt = fmt + 1
		c = int32(**(**int8)(__ccgo_up(v2)))
		switch c {
		case int32('-'):
			libc.SetBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(1), 2, 0x4)
		case int32('#'):
			libc.SetBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(1), 0, 0x1)
		case int32('+'):
			libc.SetBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(1), 3, 0x8)
		case int32('0'):
			(*_Printf_info)(unsafe.Pointer(pi)).Fpad = int32('0')
		case int32(' '):
			libc.SetBitFieldPtr8Uint32(pi+16, libc.Uint32FromInt32(1), 1, 0x2)
		default:
			return fmt - uintptr(1)
		}
		goto _1
	_1:
	}
	return r
}

func s__parseint(tls *libc.TLS, cc *CC, fmt_p uintptr, args uintptr) (r1 int32) {
	var c, r int32
	var fmt, v1 uintptr
	_, _, _, _ = c, fmt, r, v1
	fmt = **(**uintptr)(__ccgo_up(fmt_p))
	r = 0
	c = int32(**(**int8)(__ccgo_up(fmt)))
	if c == int32('*') {
		r = libc.VaInt32(&**(**_va_list)(__ccgo_up(args)))
		fmt = fmt + 1
	} else {
		for c >= int32('0') && c <= int32('9') {
			r = int32(10)*r + (c - int32('0'))
			fmt = fmt + 1
			v1 = fmt
			c = int32(**(**int8)(__ccgo_up(v1)))
		}
	}
	**(**uintptr)(__ccgo_up(fmt_p)) = fmt
	return r
}

func s__patch_long(tls *libc.TLS, cc *CC, where uintptr, val _int32_t) {
	var v1 uintptr
	_ = v1
	v1 = where
	where = where + 1
	**(**int8)(__ccgo_up(v1)) = int8(val >> libc.Int32FromInt32(0) & int32(255))
	v1 = where
	where = where + 1
	**(**int8)(__ccgo_up(v1)) = int8(val >> libc.Int32FromInt32(8) & int32(255))
	v1 = where
	where = where + 1
	**(**int8)(__ccgo_up(v1)) = int8(val >> libc.Int32FromInt32(16) & int32(255))
	v1 = where
	where = where + 1
	**(**int8)(__ccgo_up(v1)) = int8(val >> libc.Int32FromInt32(24) & int32(255))
}

// C documentation
//
//	/*
//	 * function to read a single LATIN-1 character
//	 * from a file
//	 * returns number of bytes placed in buffer, or -1 on EOF
//	 */
func s__read_latin1(tls *libc.TLS, cc *CC, f uintptr, buf uintptr) (r int32) {
	var c int32
	_ = c
	c = libc.Xfgetc(tls, f)
	if c == -int32(1) {
		return -int32(1)
	}
	if c <= int32(127) {
		**(**int8)(__ccgo_up(buf)) = int8(c)
		return int32(1)
	}
	**(**int8)(__ccgo_up(buf)) = int8(int32(0xC0) + c>>int32(6)&int32(0x1f))
	**(**int8)(__ccgo_up(buf + 1)) = int8(int32(0x80) + c&int32(0x3f))
	return int32(2)
}

// C documentation
//
//	/*
//	 * function to read a single UTF-8 character
//	 * from a file
//	 * returns number of bytes placed in buffer, or -1 on EOF
//	 */
func s__read_single(tls *libc.TLS, cc *CC, f uintptr, buf uintptr) (r int32) {
	var c int32
	_ = c
	c = libc.Xfgetc(tls, f)
	if c == -int32(1) {
		return -int32(1)
	}
	**(**int8)(__ccgo_up(buf)) = int8(c)
	return int32(1)
}

// C documentation
//
//	/*
//	 * function to read a single UTF-16 character
//	 * from a file
//	 * returns number of bytes placed in buffer, or -1 on EOF
//	 */
func s__read_utf16(tls *libc.TLS, cc *CC, f uintptr, buf uintptr) (r1 int32) {
	var c, d, r int32
	_, _, _ = c, d, r
	c = libc.Xfgetc(tls, f)
	if c < 0 {
		return -int32(1)
	}
	d = libc.Xfgetc(tls, f)
	if d < 0 {
		return -int32(1)
	}
	c = c + d<<int32(8)
	/* here we need to translate UTF-16 to UTF-8 */
	/* FIXME: this code is not done properly; it does
	   not handle surrogate pairs (0xD800 - 0xDFFF)
	*/
	if c < int32(128) {
		**(**int8)(__ccgo_up(buf)) = int8(c)
		r = int32(1)
	} else {
		if c < int32(0x800) {
			**(**int8)(__ccgo_up(buf)) = int8(int32(0xC0) + c>>int32(6)&int32(0x1F))
			**(**int8)(__ccgo_up(buf + 1)) = int8(int32(0x80) + c&int32(0x3F))
			r = int32(2)
		} else {
			if c < int32(0x10000) {
				**(**int8)(__ccgo_up(buf)) = int8(int32(0xE0) + c>>int32(12)&int32(0x0F))
				**(**int8)(__ccgo_up(buf + 1)) = int8(int32(0x80) + c>>int32(6)&int32(0x3F))
				**(**int8)(__ccgo_up(buf + 2)) = int8(int32(0x80) + c&int32(0x3F))
				r = int32(3)
			} else {
				**(**int8)(__ccgo_up(buf)) = int8(int32(0xE0) + c>>int32(18)&int32(0x07))
				**(**int8)(__ccgo_up(buf + 1)) = int8(int32(0x80) + c>>int32(12)&int32(0x3F))
				**(**int8)(__ccgo_up(buf + 2)) = int8(int32(0x80) + c>>int32(6)&int32(0x3F))
				**(**int8)(__ccgo_up(buf + 3)) = int8(int32(0x80) + c&int32(0x3F))
				r = int32(4)
			}
		}
	}
	return r
}

// C documentation
//
//	/*
//	 * skip over a quoted string
//	 * returns a pointer to the last character (normally a quote)
//	 */
func s__skip_quoted_string(tls *libc.TLS, cc *CC, ptr uintptr, lastchar int32) (r uintptr) {
	for **(**int8)(__ccgo_up(ptr)) != 0 && int32(**(**int8)(__ccgo_up(ptr))) != lastchar {
		ptr = ptr + 1
	}
	return ptr
}

// C documentation
//
//	/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
//	   YYDEST.  */
func s__yystpcpy(tls *libc.TLS, cc *CC, yydest uintptr, yysrc uintptr) (r uintptr) {
	var yyd, yys, v2, v3 uintptr
	var v1 int8
	_, _, _, _, _ = yyd, yys, v1, v2, v3
	yyd = yydest
	yys = yysrc
	for {
		v2 = yys
		yys = yys + 1
		v1 = **(**int8)(__ccgo_up(v2))
		v3 = yyd
		yyd = yyd + 1
		**(**int8)(__ccgo_up(v3)) = v1
		if !(int32(v1) != int32('\000')) {
			break
		}
		continue
	}
	return yyd - uintptr(1)
}

// C documentation
//
//	/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
//	   YYDEST.  */
func s__yystpcpy1(tls *libc.TLS, cc *CC, yydest uintptr, yysrc uintptr) (r uintptr) {
	var yyd, yys, v2, v3 uintptr
	var v1 int8
	_, _, _, _, _ = yyd, yys, v1, v2, v3
	yyd = yydest
	yys = yysrc
	for {
		v2 = yys
		yys = yys + 1
		v1 = **(**int8)(__ccgo_up(v2))
		v3 = yyd
		yyd = yyd + 1
		**(**int8)(__ccgo_up(v3)) = v1
		if !(int32(v1) != int32('\000')) {
			break
		}
		continue
	}
	return yyd - uintptr(1)
}

// C documentation
//
//	/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
//	   YYDEST.  */
func s__yystpcpy2(tls *libc.TLS, cc *CC, yydest uintptr, yysrc uintptr) (r uintptr) {
	var yyd, yys, v2, v3 uintptr
	var v1 int8
	_, _, _, _, _ = yyd, yys, v1, v2, v3
	yyd = yydest
	yys = yysrc
	for {
		v2 = yys
		yys = yys + 1
		v1 = **(**int8)(__ccgo_up(v2))
		v3 = yyd
		yyd = yyd + 1
		**(**int8)(__ccgo_up(v3)) = v1
		if !(int32(v1) != int32('\000')) {
			break
		}
		continue
	}
	return yyd - uintptr(1)
}

func s__zip_strrpl(tls *libc.TLS, cc *CC, str uintptr, n _size_t, oldchar int8, newchar int8) (r uintptr) {
	var begin, rpl, v3 uintptr
	var c, v2 int8
	var i _size_t
	var v4 bool
	_, _, _, _, _, _, _ = begin, c, i, rpl, v2, v3, v4
	rpl = calloc(tls, cc, libc.Uint64FromInt32(1)+n, uint64(1))
	begin = rpl
	if !(rpl != 0) {
		return libc.UintptrFromInt32(0)
	}
	i = uint64(0)
	for {
		if v4 = i < n; v4 {
			v3 = str
			str = str + 1
			v2 = **(**int8)(__ccgo_up(v3))
			c = v2
		}
		if !(v4 && v2 != 0) {
			break
		}
		if int32(c) == int32(oldchar) {
			c = newchar
		}
		v3 = rpl
		rpl = rpl + 1
		**(**int8)(__ccgo_up(v3)) = c
		goto _1
	_1:
		;
		i = i + 1
	}
	return begin
}

// C documentation
//
//	/*
//	 * an annotation just looks like a function with no name or body
//	 */
func x__DeclareToplevelAnnotation(tls *libc.TLS, cc *CC, anno uintptr) {
	var f, str uintptr
	_, _ = f, str
	/* check the annotation string; some of them are special */
	str = *(*uintptr)(unsafe.Pointer(anno + 8))
	if int32(**(**int8)(__ccgo_up(str))) == int32('!') {
		/* directives, not code */
		str = str + uintptr(1)
		s__ParseDirectives(tls, cc, str)
	} else {
		f = x__NewFunction(tls, cc, 0)
		(*_Function)(unsafe.Pointer(f)).Fannotations = anno
	}
}

/*
 * type inference
 */

// C documentation
//
//	/*
//	 * "canonicalize" an identifier, to make sure it
//	 * does not conflict with any C reserved words
//	 * also checks for spaces and other illegal characters within the name
//	 */
func x__Is_C_Reserved(tls *libc.TLS, cc *CC, name uintptr) (r uint8) {
	var ptr, s uintptr
	_, _ = ptr, s
	s = x__FindSymbolEx(tls, cc, uintptr(unsafe.Pointer(&cc.x__ckeywords)), name, 0)
	if s != 0 && !(libc.Xstrcmp(tls, name, (*_Symbol)(unsafe.Pointer(s)).Four_name) != 0) {
		return libc.BoolUint8(m_true != 0)
	}
	if libc.Xstrlen(tls, name) < uint64(3) {
		return libc.BoolUint8(m_false != 0)
	}
	ptr = name
	for {
		if !(**(**int8)(__ccgo_up(ptr)) != 0) {
			break
		}
		if !(x__isIdentifierChar(tls, cc, int32(**(**int8)(__ccgo_up(ptr)))) != 0) {
			return libc.BoolUint8(m_true != 0)
		}
		goto _1
	_1:
		;
		ptr = ptr + 1
	}
	if int32(**(**int8)(__ccgo_up(ptr + uintptr(-libc.Int32FromInt32(2))))) == int32('_') && int32(**(**int8)(__ccgo_up(ptr + uintptr(-libc.Int32FromInt32(1))))) == int32('t') {
		return libc.BoolUint8(m_true != 0)
	}
	return libc.BoolUint8(m_false != 0)
}

func x__NewObjectWithParams(tls *libc.TLS, cc *CC, identifier uintptr, string1 uintptr, fromUsing int32, paramlist uintptr) (r uintptr) {
	var P, ast, filename uintptr
	_, _, _ = P, ast, filename
	if string1 != 0 {
		filename = *(*uintptr)(unsafe.Pointer(string1 + 8))
	} else {
		filename = libc.UintptrFromInt32(0)
	}
	ast = x__NewAST(tls, cc, int32(_AST_OBJECT), identifier, libc.UintptrFromInt32(0))
	if filename != 0 {
		P = x__ParseFile(tls, cc, filename, paramlist)
		(*_Module)(unsafe.Pointer(P)).FfromUsing = int8(fromUsing)
		*(*uintptr)(unsafe.Pointer(ast + 8)) = P
	}
	return ast
}

// C documentation
//
//	/*
//	 * transform a case expression list into a single boolean test
//	 * "var" is the variable the case is testing against (may be
//	 * a temporary)
//	 */
func x__TransformCaseExprList(tls *libc.TLS, cc *CC, var1 uintptr, ast uintptr) (r uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var c, v1 int32
	var listexpr, newStr, node, result, sptr, strNode, v2 uintptr
	var _ /* saveinfo at bp+0 */ _ASTReportInfo
	_, _, _, _, _, _, _, _, _ = c, listexpr, newStr, node, result, sptr, strNode, v1, v2
	listexpr = libc.UintptrFromInt32(0)
	node = libc.UintptrFromInt32(0)
	for ast != 0 {
		x__AstReportAs(tls, cc, ast, bp)
		if (*_AST)(unsafe.Pointer(ast)).Fkind == int32(_AST_OTHER) {
			result = x__AstInteger(tls, cc, int64(1))
			x__AstReportDone(tls, cc, bp)
			return result
		}
		if (*_AST)(unsafe.Pointer((*_AST)(unsafe.Pointer(ast)).Fleft)).Fkind == int32(_AST_RANGE) {
			node = x__NewAST(tls, cc, int32(_AST_ISBETWEEN), var1, (*_AST)(unsafe.Pointer(ast)).Fleft)
		} else {
			if (*_AST)(unsafe.Pointer((*_AST)(unsafe.Pointer(ast)).Fleft)).Fkind == int32(_AST_STRING) {
				// if the string is long, break it up into single characters
				sptr = *(*uintptr)(unsafe.Pointer((*_AST)(unsafe.Pointer(ast)).Fleft + 8))
				for {
					v2 = sptr
					sptr = sptr + 1
					v1 = int32(**(**int8)(__ccgo_up(v2)))
					c = v1
					if !(v1 != 0) {
						break
					}
					newStr = malloc(tls, cc, uint64(2))
					**(**int8)(__ccgo_up(newStr)) = int8(c)
					**(**int8)(__ccgo_up(newStr + 1)) = 0
					strNode = x__NewAST(tls, cc, int32(_AST_STRING), libc.UintptrFromInt32(0), libc.UintptrFromInt32(0))
					*(*uintptr)(unsafe.Pointer(strNode + 8)) = newStr
					node = x__AstOperator(tls, cc, int32(_K_EQ), var1, strNode)
					if **(**int8)(__ccgo_up(sptr)) != 0 {
						if listexpr != 0 {
							listexpr = x__AstOperator(tls, cc, int32(_K_BOOL_OR), listexpr, node)
						} else {
							listexpr = node
						}
					}
				}
			} else {
				node = x__AstOperator(tls, cc, int32(_K_EQ), var1, (*_AST)(unsafe.Pointer(ast)).Fleft)
			}
		}
		if listexpr != 0 {
			listexpr = x__AstOperator(tls, cc, int32(_K_BOOL_OR), listexpr, node)
		} else {
			listexpr = node
		}
		ast = (*_AST)(unsafe.Pointer(ast)).Fright
		x__AstReportDone(tls, cc, bp)
	}
	return listexpr
}

func x__dofmt(tls *libc.TLS, cc *CC, __ccgo_fp_func _FmtPutchar, funcarg uintptr, _fmt uintptr, args uintptr) (r int32) {
	bp := tls.Alloc(64)
	defer tls.Free(64)
	*(*uintptr)(unsafe.Pointer(bp)) = _fmt
	var c, i, q int32
	var v2 uintptr
	var _ /* pi at bp+8 */ _Printf_info
	_, _, _, _ = c, i, q, v2
	libc.Xmemset(tls, bp+8, 0, uint64(48))
	(**(**_Printf_info)(__ccgo_up(bp + 8))).Fputarg = funcarg
	(**(**_Printf_info)(__ccgo_up(bp + 8))).Fputchar = __ccgo_fp_func
	for {
		v2 = **(**uintptr)(__ccgo_up(bp))
		**(**uintptr)(__ccgo_up(bp)) = **(**uintptr)(__ccgo_up(bp)) + 1
		c = int32(**(**int8)(__ccgo_up(v2)))
		if c == 0 {
			break
		}
		if c != int32('%') {
			q = s___fmtputc(tls, cc, c, bp+8)
			if q < 0 {
				return q
			}
			goto _1
		}
		**(**uintptr)(__ccgo_up(bp)) = s__parseflags(tls, cc, **(**uintptr)(__ccgo_up(bp)), bp+8)
		(**(**_Printf_info)(__ccgo_up(bp + 8))).Fwidth = s__parseint(tls, cc, bp, args)
		if (**(**_Printf_info)(__ccgo_up(bp + 8))).Fwidth < 0 {
			(**(**_Printf_info)(__ccgo_up(bp + 8))).Fwidth = -(**(**_Printf_info)(__ccgo_up(bp + 8))).Fwidth
			libc.SetBitFieldPtr8Uint32(bp+8+16, libc.Uint32FromInt32(1), 2, 0x4)
		}
		c = int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp)))))
		if c == 0 {
			break
		}
		if c == int32('.') {
			**(**uintptr)(__ccgo_up(bp)) = **(**uintptr)(__ccgo_up(bp)) + 1
			(**(**_Printf_info)(__ccgo_up(bp + 8))).Fprec = s__parseint(tls, cc, bp, args)
			c = int32(**(**int8)(__ccgo_up(**(**uintptr)(__ccgo_up(bp)))))
			if c == 0 {
				break
			}
		}
		**(**uintptr)(__ccgo_up(bp)) = s__parsesize(tls, cc, **(**uintptr)(__ccgo_up(bp)), bp+8)
		v2 = **(**uintptr)(__ccgo_up(bp))
		**(**uintptr)(__ccgo_up(bp)) = **(**uintptr)(__ccgo_up(bp)) + 1
		c = int32(**(**int8)(__ccgo_up(v2)))
		if c == 0 {
			break
		}
		(**(**_Printf_info)(__ccgo_up(bp + 8))).Fspec = c
		q = 0
		i = 0
		for {
			if !(cc.s__fmtspecs[i].Ffunc1 != 0) {
				break
			}
			if int32(cc.s__fmtspecs[i].Fspec) == c {
				q = (*(*func(*libc.TLS, *CC, uintptr, uintptr) int32)(unsafe.Pointer(&struct{ uintptr }{cc.s__fmtspecs[i].Ffunc1})))(tls, cc, bp+8, args)
				break
			}
			goto _4
		_4:
			;
			i = i + 1
		}
		if cc.s__fmtspecs[i].Ffunc1 == libc.UintptrFromInt32(0) {
			q = s___fmt_unsupported(tls, cc, bp+8, args)
		}
		if q < 0 {
			return q
		}
		goto _1
	_1:
	}
	return (**(**_Printf_info)(__ccgo_up(bp + 8))).Fbyteswritten
}

// C documentation
//
//	/* add a single character to a buffer */
func x__flexbuf_addchar(tls *libc.TLS, cc *CC, fb uintptr, c int32) (r uintptr) {
	var newdata uintptr
	var newlen _size_t
	_, _ = newdata, newlen
	newlen = (*_flexbuf)(unsafe.Pointer(fb)).Flen1 + uint64(1)
	if newlen > (*_flexbuf)(unsafe.Pointer(fb)).Fspace {
		newdata = realloc(tls, cc, (*_flexbuf)(unsafe.Pointer(fb)).Fdata, (*_flexbuf)(unsafe.Pointer(fb)).Fspace+(*_flexbuf)(unsafe.Pointer(fb)).Fgrowsize)
		if !(newdata != 0) {
			return newdata
		}
		**(**_size_t)(__ccgo_up(fb + 16)) += (*_flexbuf)(unsafe.Pointer(fb)).Fgrowsize
		(*_flexbuf)(unsafe.Pointer(fb)).Fdata = newdata
	}
	**(**int8)(__ccgo_up((*_flexbuf)(unsafe.Pointer(fb)).Fdata + uintptr((*_flexbuf)(unsafe.Pointer(fb)).Flen1))) = int8(c)
	(*_flexbuf)(unsafe.Pointer(fb)).Flen1 = newlen
	return (*_flexbuf)(unsafe.Pointer(fb)).Fdata
}

func x__get_file(tls *libc.TLS, cc *CC, name uintptr, src_dir uintptr, fullname uintptr, bufsize _size_t, include_opt int32) (r uintptr) {
	/*
	 * Common FILEINFO buffer initialization for a new file or macro.
	 */
	var file uintptr
	_ = file
	file = x__xmalloc(tls, cc, uint64(128))
	(*_FILEINFO)(unsafe.Pointer(file)).Fbuffer = x__xmalloc(tls, cc, bufsize)
	(*_FILEINFO)(unsafe.Pointer(file)).Fbptr = (*_FILEINFO)(unsafe.Pointer(file)).Fbuffer /* Initialize line ptr  */
	**(**int8)(__ccgo_up((*_FILEINFO)(unsafe.Pointer(file)).Fbuffer)) = int8('\000')      /* Force first read     */
	(*_FILEINFO)(unsafe.Pointer(file)).Fline = 0                                          /* (Not used just yet)  */
	(*_FILEINFO)(unsafe.Pointer(file)).Ffp = libc.UintptrFromInt32(0)                     /* No file yet          */
	(*_FILEINFO)(unsafe.Pointer(file)).Fpos = 0                                           /* No pos to remember   */
	(*_FILEINFO)(unsafe.Pointer(file)).Fparent = cc.x__infile                             /* Chain files together */
	(*_FILEINFO)(unsafe.Pointer(file)).Finitif = cc.x__ifptr                              /* Initial ifstack      */
	(*_FILEINFO)(unsafe.Pointer(file)).Finclude_opt = include_opt                         /* Specified by -include*/
	(*_FILEINFO)(unsafe.Pointer(file)).Fdirp = libc.UintptrFromInt32(0)                   /* No include dir yet   */
	(*_FILEINFO)(unsafe.Pointer(file)).Freal_fname = name                                 /* Save file/macro name */
	(*_FILEINFO)(unsafe.Pointer(file)).Ffull_fname = fullname                             /* Full path list       */
	if name != 0 {
		(*_FILEINFO)(unsafe.Pointer(file)).Ffilename = x__xmalloc(tls, cc, libc.Xstrlen(tls, name)+uint64(1))
		libc.Xstrcpy(tls, (*_FILEINFO)(unsafe.Pointer(file)).Ffilename, name) /* Copy for #line       */
	} else {
		(*_FILEINFO)(unsafe.Pointer(file)).Ffilename = libc.UintptrFromInt32(0)
	}
	if src_dir != 0 {
		(*_FILEINFO)(unsafe.Pointer(file)).Fsrc_dir = x__xmalloc(tls, cc, libc.Xstrlen(tls, src_dir)+uint64(1))
		libc.Xstrcpy(tls, (*_FILEINFO)(unsafe.Pointer(file)).Fsrc_dir, src_dir)
	} else {
		(*_FILEINFO)(unsafe.Pointer(file)).Fsrc_dir = libc.UintptrFromInt32(0)
	}
	(*_FILEINFO)(unsafe.Pointer(file)).Flast_fputc = __ccgo_fp(x__mcpp_lib_fputc)
	(*_FILEINFO)(unsafe.Pointer(file)).Flast_fputs = __ccgo_fp(x__mcpp_lib_fputs)
	(*_FILEINFO)(unsafe.Pointer(file)).Flast_fprintf = __ccgo_fp(x__mcpp_lib_fprintf)
	if cc.x__infile != libc.UintptrFromInt32(0) { /* If #include file     */
		(*_FILEINFO)(unsafe.Pointer(cc.x__infile)).Fline = cc.x__src_line /* Save current line    */
		(*_FILEINFO)(unsafe.Pointer(cc.x__infile)).Flast_fputc = cc.x__mcpp_fputc
		(*_FILEINFO)(unsafe.Pointer(cc.x__infile)).Flast_fputs = cc.x__mcpp_fputs
		(*_FILEINFO)(unsafe.Pointer(cc.x__infile)).Flast_fprintf = cc.x__mcpp_fprintf
	}
	cc.x__infile = file /* New current file     */
	return file         /* All done.            */
}

// C documentation
//
//	/*
//	 *
//	 */
func x__lexgetc(tls *libc.TLS, cc *CC, L uintptr) (r int32) {
	var c int32
	var v1 int8
	_, _ = c, v1
	if (*_LexStream)(unsafe.Pointer(L)).Fungot_ptr != 0 {
		(*_LexStream)(unsafe.Pointer(L)).Fungot_ptr = (*_LexStream)(unsafe.Pointer(L)).Fungot_ptr - 1
		return **(**int32)(__ccgo_up(L + 32 + uintptr((*_LexStream)(unsafe.Pointer(L)).Fungot_ptr)*4))
	}
	if (*_LexStream)(unsafe.Pointer(L)).FpendingLine != 0 {
		s__startNewLine(tls, cc, L)
		(*_LexStream)(unsafe.Pointer(L)).FlineCounter = (*_LexStream)(unsafe.Pointer(L)).FlineCounter + 1
		(*_LexStream)(unsafe.Pointer(L)).FpendingLine = 0
		(*_LexStream)(unsafe.Pointer(L)).FcolCounter = 0
		v1 = libc.Int8FromInt32(0)
		(*_LexStream)(unsafe.Pointer(L)).FsawDataDirective = v1
		(*_LexStream)(unsafe.Pointer(L)).FsawInstruction = v1
		(*_LexStream)(unsafe.Pointer(L)).Fbacktick_state = 0
	}
	c = (*(*func(*libc.TLS, *CC, uintptr) int32)(unsafe.Pointer(&struct{ uintptr }{(*_LexStream)(unsafe.Pointer(L)).Fgetcf})))(tls, cc, L)
	if c == int32('\n') {
		(*_LexStream)(unsafe.Pointer(L)).FpendingLine = int32(1)
	} else {
		if c == int32('\013') {
			(*_LexStream)(unsafe.Pointer(L)).FpendingLine = int32(1)
			(*_LexStream)(unsafe.Pointer(L)).FlineCounter = (*_LexStream)(unsafe.Pointer(L)).FlineCounter - 1 // don't actually increment line counter later
		} else {
			if c == int32('\t') {
				**(**int32)(__ccgo_up(L + 400)) += cc.x__gl_tab_stops
				/* now go back to the previous stop */
				(*_LexStream)(unsafe.Pointer(L)).FcolCounter = cc.x__gl_tab_stops * ((*_LexStream)(unsafe.Pointer(L)).FcolCounter / cc.x__gl_tab_stops)
			} else {
				(*_LexStream)(unsafe.Pointer(L)).FcolCounter = (*_LexStream)(unsafe.Pointer(L)).FcolCounter + 1
			}
		}
	}
	if c == -int32(1) {
		s__startNewLine(tls, cc, L)
	} else {
		x__flexbuf_addchar(tls, cc, L+432, c)
	}
	return c
}

func x__look_id(tls *libc.TLS, cc *CC, name uintptr) (r uintptr) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	/*
	 * Look for the identifier in the symbol table.
	 * If found, return the table pointer;  Else return NULL.
	 */
	var prevp, v1 uintptr
	var _ /* cmp at bp+0 */ int32
	_, _ = prevp, v1
	prevp = x__look_prev(tls, cc, name, bp)
	if **(**int32)(__ccgo_up(bp)) == 0 && int32((*_DEFBUF)(unsafe.Pointer(**(**uintptr)(__ccgo_up(prevp)))).Fpush) == 0 {
		v1 = **(**uintptr)(__ccgo_up(prevp))
	} else {
		v1 = libc.UintptrFromInt32(0)
	}
	return v1
}

// C documentation
//
//	//
//	// reverse a string in-place
//	//
func x__strrev(tls *libc.TLS, cc *CC, origstr uintptr) (r uintptr) {
	var c int32
	var end, str, v2 uintptr
	_, _, _, _ = c, end, str, v2
	str = origstr
	end = str
	for {
		if !(**(**int8)(__ccgo_up(end)) != 0) {
			break
		}
		goto _1
	_1:
		;
		end = end + 1
	}
	end = end - 1
	for end > str {
		c = int32(**(**int8)(__ccgo_up(str)))
		v2 = str
		str = str + 1
		**(**int8)(__ccgo_up(v2)) = **(**int8)(__ccgo_up(end))
		v2 = end
		end = end - 1
		**(**int8)(__ccgo_up(v2)) = int8(c)
	}
	return origstr
}

func x__unget_string(tls *libc.TLS, cc *CC, text uintptr, name uintptr) (r uintptr) {
	/*
	 * Push a string back on the input stream.  This is done by treating
	 * the text as if it were a macro or a file.
	 */
	var file uintptr
	var size _size_t
	_, _ = file, size
	if text != 0 {
		size = libc.Xstrlen(tls, text) + uint64(1)
	} else {
		size = uint64(1)
	}
	file = x__get_file(tls, cc, name, libc.UintptrFromInt32(0), libc.UintptrFromInt32(0), size, m_FALSE)
	if text != 0 {
		libc.Xmemcpy(tls, (*_FILEINFO)(unsafe.Pointer(file)).Fbuffer, text, size)
	} else {
		**(**int8)(__ccgo_up((*_FILEINFO)(unsafe.Pointer(file)).Fbuffer)) = int8('\000')
	}
	return file
}
