// Code generated by 'egg -o parser.go -start SourceFile -package octogo octogo.ebnf', DO NOT EDIT.

// Parser generated from octogo.ebnf.

package octogo

import (
	"errors"
	"fmt"
	"go/token"
	"strconv"
	"unicode"
	"unicode/utf8"

	"modernc.org/scanner"
)

var _ = unicode.MaxRune

// Symbols
const (
	TOK_EOF        = Symbol(0)  // EOF
	TOK_0021003d   = Symbol(1)  // "!="
	TOK_003c002d   = Symbol(2)  // "<-"
	TOK_003c003c   = Symbol(3)  // "<<"
	TOK_003c003d   = Symbol(4)  // "<="
	TOK_003d003d   = Symbol(5)  // "=="
	TOK_003e003d   = Symbol(6)  // ">="
	TOK_003e003e   = Symbol(7)  // ">>"
	TOK_bool       = Symbol(8)  // "bool"
	TOK_byte       = Symbol(9)  // "byte"
	TOK_case       = Symbol(10) // "case"
	TOK_chan       = Symbol(11) // "chan"
	TOK_const      = Symbol(12) // "const"
	TOK_default    = Symbol(13) // "default"
	TOK_else       = Symbol(14) // "else"
	TOK_false      = Symbol(15) // "false"
	TOK_for        = Symbol(16) // "for"
	TOK_func       = Symbol(17) // "func"
	TOK_go         = Symbol(18) // "go"
	TOK_if         = Symbol(19) // "if"
	TOK_import     = Symbol(20) // "import"
	TOK_int        = Symbol(21) // "int"
	TOK_package    = Symbol(22) // "package"
	TOK_return     = Symbol(23) // "return"
	TOK_select     = Symbol(24) // "select"
	TOK_switch     = Symbol(25) // "switch"
	TOK_true       = Symbol(26) // "true"
	TOK_var        = Symbol(27) // "var"
	TOK_0026       = Symbol(28) // '&'
	TOK_0028       = Symbol(29) // '('
	TOK_0029       = Symbol(30) // ')'
	TOK_002a       = Symbol(31) // '*'
	TOK_002b       = Symbol(32) // '+'
	TOK_002c       = Symbol(33) // ','
	TOK_002d       = Symbol(34) // '-'
	TOK_002e       = Symbol(35) // '.'
	TOK_002f       = Symbol(36) // '/'
	TOK_003a       = Symbol(37) // ':'
	TOK_003c       = Symbol(38) // '<'
	TOK_003d       = Symbol(39) // '='
	TOK_003e       = Symbol(40) // '>'
	TOK_005b       = Symbol(41) // '['
	TOK_005d       = Symbol(42) // ']'
	TOK_005e       = Symbol(43) // '^'
	TOK_007b       = Symbol(44) // '{'
	TOK_007c       = Symbol(45) // '|'
	TOK_007d       = Symbol(46) // '}'
	identifier     = Symbol(47) // identifier
	int_lit        = Symbol(48) // int_lit
	string_lit     = Symbol(49) // string_lit
	white_space    = Symbol(50) // white_space
	SourceFile     = Symbol(51) // SourceFile
	PackageClause  = Symbol(52) // PackageClause
	ImportDecl     = Symbol(53) // ImportDecl
	TopLevelDecl   = Symbol(54) // TopLevelDecl
	ConstDecl      = Symbol(55) // ConstDecl
	Type           = Symbol(56) // Type
	VarDecl        = Symbol(57) // VarDecl
	FuncDecl       = Symbol(58) // FuncDecl
	ParameterList  = Symbol(59) // ParameterList
	Block          = Symbol(60) // Block
	Statement      = Symbol(61) // Statement
	Postfix        = Symbol(62) // Postfix
	Selector       = Symbol(63) // Selector
	Index          = Symbol(64) // Index
	CallSuffix     = Symbol(65) // CallSuffix
	ArgumentList   = Symbol(66) // ArgumentList
	SwitchStmt     = Symbol(67) // SwitchStmt
	CaseClause     = Symbol(68) // CaseClause
	CaseHead       = Symbol(69) // CaseHead
	ExpressionList = Symbol(70) // ExpressionList
	SelectStmt     = Symbol(71) // SelectStmt
	CommClause     = Symbol(72) // CommClause
	CommHead       = Symbol(73) // CommHead
	CommOp         = Symbol(74) // CommOp
	PostfixComm    = Symbol(75) // PostfixComm
	Expression     = Symbol(76) // Expression
	SimpleExpr     = Symbol(77) // SimpleExpr
	Term           = Symbol(78) // Term
	Factor         = Symbol(79) // Factor
	FactorSuffix   = Symbol(80) // FactorSuffix
	RelOp          = Symbol(81) // RelOp
	AddOp          = Symbol(82) // AddOp
	MulOp          = Symbol(83) // MulOp
)

const SymbolNames = "EOF\"!=\"\"<-\"\"<<\"\"<=\"\"==\"\">=\"\">>\"\"bool\"\"byte\"\"case\"\"chan\"\"const\"\"default\"\"else\"\"false\"\"for\"\"func\"\"go\"\"if\"\"import\"\"int\"\"package\"\"return\"\"select\"\"switch\"\"true\"\"var\"'&''('')''*''+'',''-''.''/'':''<''=''>''['']''^''{''|''}'identifierint_litstring_litwhite_spaceSourceFilePackageClauseImportDeclTopLevelDeclConstDeclTypeVarDeclFuncDeclParameterListBlockStatementPostfixSelectorIndexCallSuffixArgumentListSwitchStmtCaseClauseCaseHeadExpressionListSelectStmtCommClauseCommHeadCommOpPostfixCommExpressionSimpleExprTermFactorFactorSuffixRelOpAddOpMulOp"

var SymbolIndex = [...]uint16{0, 3, 7, 11, 15, 19, 23, 27, 31, 37, 43, 49, 55, 62, 71, 77, 84, 89, 95, 99, 103, 111, 116, 125, 133, 141, 149, 155, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 208, 211, 214, 217, 227, 234, 244, 255, 265, 278, 288, 300, 309, 313, 320, 328, 341, 346, 355, 362, 370, 375, 385, 397, 407, 417, 425, 439, 449, 459, 467, 473, 484, 494, 504, 508, 514, 526, 531, 536, 541}

func (s Symbol) String() string {
	idx := int(s) - 0
	if s < 0 || idx >= len(SymbolIndex)-1 {
		return "Symbol(" + strconv.FormatInt(int64(s), 10) + ")"
	}
	return SymbolNames[SymbolIndex[idx]:SymbolIndex[idx+1]]
}

var errorSets = [...][]Symbol{
	{TOK_003e, TOK_003c, TOK_003e003d, TOK_003d003d, TOK_003c003d, TOK_0021003d},
	{CaseHead, TOK_007d, TOK_default, TOK_case},
	{CommHead, TOK_007d, TOK_default, TOK_case},
	{TOK_default, TOK_case},
	{FuncDecl, VarDecl, ConstDecl, TOK_var, TOK_import, TOK_func, TOK_const},
	{FuncDecl, VarDecl, ConstDecl, TOK_var, TOK_func, TOK_const},
	{TOK_var, TOK_func, TOK_const},
	{TOK_const},
	{TOK_else},
	{TOK_func},
	{SelectStmt, SwitchStmt, VarDecl, ConstDecl, identifier, TOK_007d, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{SelectStmt, SwitchStmt, VarDecl, ConstDecl, identifier, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{identifier, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{Factor, Term, SimpleExpr, Expression, string_lit, int_lit, identifier, TOK_0029, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_lit, int_lit, identifier, TOK_005d, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_lit, int_lit, identifier, TOK_007b, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, Expression, string_lit, int_lit, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_lit, int_lit, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, string_lit, int_lit, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, string_lit, int_lit, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{string_lit, int_lit, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{CallSuffix, Index, Selector, TOK_005b, TOK_003d, TOK_002e, TOK_0028, TOK_003c002d},
	{TOK_005b, TOK_003d, TOK_002e, TOK_0028, TOK_003c002d},
	{Index, Selector, TOK_005b, TOK_003d, TOK_002e, TOK_003c002d},
	{TOK_005b, TOK_003d, TOK_002e, TOK_003c002d},
	{identifier, TOK_003c002d},
	{TOK_import},
	{TOK_package},
	{TOK_select},
	{TOK_switch},
	{TOK_var},
	{CallSuffix, Index, Selector, TOK_005b, TOK_002e, TOK_0028},
	{TOK_005b, TOK_002e, TOK_0028},
	{TOK_0028},
	{TOK_003c002d},
	{TOK_002f, TOK_002a, TOK_0026, TOK_003e003e, TOK_003c003c},
	{identifier, TOK_0029},
	{TOK_0029},
	{TOK_007c, TOK_005e, TOK_002d, TOK_002b},
	{TOK_002c},
	{TOK_002e},
	{TOK_003a},
	{TOK_003d},
	{TOK_005b},
	{TOK_005d},
	{TOK_007b},
	{identifier},
	{string_lit},
	{TOK_007b, TOK_005b, TOK_int, TOK_chan, TOK_byte, TOK_bool},
	{TOK_005b, TOK_int, TOK_chan, TOK_byte, TOK_bool},
}

type Parser struct {
	cache     [][]int32
	eof       bool
	errBudget int
	off       int
	sc        *RecScanner
	src       []byte
	tok       Token // current lookahead
	tokIndex  int32 // For scanner.Token(tokIndex)
}

type Symbol int32

// scan recognizes longest UTF-8 lexemes. Lower IDs take precedence on same length.
//
//	id   0: $
//	id   1: !=
//	id   2: <-
//	id   3: <<
//	id   4: <=
//	id   5: ==
//	id   6: >=
//	id   7: >>
//	id   8: bool
//	id   9: byte
//	id  10: case
//	id  11: chan
//	id  12: const
//	id  13: default
//	id  14: else
//	id  15: false
//	id  16: for
//	id  17: func
//	id  18: go
//	id  19: if
//	id  20: import
//	id  21: int
//	id  22: package
//	id  23: return
//	id  24: select
//	id  25: switch
//	id  26: true
//	id  27: var
//	id  28: &
//	id  29: \(
//	id  30: \)
//	id  31: \*
//	id  32: \+
//	id  33: ,
//	id  34: -
//	id  35: \.
//	id  36: /
//	id  37: :
//	id  38: <
//	id  39: =
//	id  40: >
//	id  41: \[
//	id  42: \]
//	id  43: \^
//	id  44: \{
//	id  45: \|
//	id  46: \}
//	id  47: ((((\pL))|(_)))((((((\pL))|(_)))|((\p{Nd}))))*
//	id  48: ((((0)|(([1-9]))(((_))?((([0-9]))(((_))?(([0-9])))*))?))|((0)(((b)|(B)))((_))?((((0)|(1)))(((_))?(((0)|(1))))*))|((0)(((o)|(O)))?((_))?((([0-7]))(((_))?(([0-7])))*))|((0)(((x)|(X)))((_))?((([0-9A-Fa-f]))(((_))?(([0-9A-Fa-f])))*)))
//	id  49: (((`)(([^\x60]))*(`))|((")((((((\\)(u)(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f])))|((\\)(U)(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f]))(([0-9A-Fa-f])))|((\\)(((a)|(b)|(f)|(n)|(r)|(t)|(v)|(\\)|(')|("))))))|((((\\)(([0-7]))(([0-7]))(([0-7])))|((\\)(x)(([0-9A-Fa-f]))(([0-9A-Fa-f])))))))*(")))
//	id  50: (/\*([^*]|\*+[^*/])*\*+/|//.*| |\t|\n|\r)
//
// ID == -1 is returned when no lexeme was recognized.
func (*Parser) scan(s []byte) (id, length int) {
	const endOfText = 0x110000
	var pos, pos0, width, width1 int
	id = -1
	var r, r1 rune
	_ = pos0
	_ = r
	_ = r1
	_ = width1
	step := func(pos int) (r rune, n int) {
		if pos < len(s) {
			c := s[pos]
			if c < utf8.RuneSelf {
				return rune(c), 1
			}
			return utf8.DecodeRune(s[pos:])
		}
		return endOfText, 0
	}
	move := func() {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
	}
	accept := func(x rune) bool {
		if r == x {
			move()
			return true
		}
		return false
	}
	_ = accept
	accept2 := func(x rune) bool {
		if r <= x {
			move()
			return true
		}
		return false
	}
	_ = accept2
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	if accept('\t') {
		goto l87
	}
	if accept('\n') {
		goto l89
	}
	if accept('\r') {
		goto l91
	}
	if accept(' ') {
		goto l93
	}
	if accept('!') {
		goto l95
	}
	if accept('"') {
		goto l100
	}
	if accept('&') {
		goto l254
	}
	if accept('(') {
		goto l256
	}
	if accept(')') {
		goto l258
	}
	if accept('*') {
		goto l260
	}
	if accept('+') {
		goto l262
	}
	if accept(',') {
		goto l264
	}
	if accept('-') {
		goto l266
	}
	if accept('.') {
		goto l268
	}
	if accept('/') {
		goto l270
	}
	if accept('0') {
		goto l308
	}
	if accept(':') {
		goto l462
	}
	if accept('<') {
		goto l464
	}
	if accept('=') {
		goto l478
	}
	if accept('>') {
		goto l484
	}
	if accept('[') {
		goto l494
	}
	if accept(']') {
		goto l496
	}
	if accept('^') {
		goto l498
	}
	if accept('_') {
		goto l500
	}
	if accept('`') {
		goto l532
	}
	if accept('b') {
		goto l544
	}
	if accept('c') {
		goto l612
	}
	if accept('d') {
		goto l720
	}
	if accept('e') {
		goto l788
	}
	if accept('f') {
		goto l826
	}
	if accept('g') {
		goto l924
	}
	if accept('i') {
		goto l942
	}
	if accept('p') {
		goto l1030
	}
	if accept('r') {
		goto l1098
	}
	if accept('s') {
		goto l1156
	}
	if accept('t') {
		goto l1264
	}
	if accept('v') {
		goto l1302
	}
	if accept('{') {
		goto l1330
	}
	if accept('|') {
		goto l1332
	}
	if accept('}') {
		goto l1334
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l1336
	}
	if r < '1' {
		goto l82out
	}
	if accept2('9') {
		goto l438
	}
l82out:
	if r == endOfText {
		goto l1344
	}
	return id, length
l87:
	id, length = 50, pos
	return id, length
l89:
	id, length = 50, pos
	return id, length
l91:
	id, length = 50, pos
	return id, length
l93:
	id, length = 50, pos
	return id, length
l95:
	if accept('=') {
		goto l98
	}
	return id, length
l98:
	id, length = 1, pos
	return id, length
l100:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l105:
	id, length = 49, pos
	return id, length
l107:
	if accept('"') {
		goto l136
	}
	if accept('\'') {
		goto l141
	}
	if accept('U') {
		goto l157
	}
	if accept('\\') {
		goto l186
	}
	if accept('a') {
		goto l191
	}
	if accept('b') {
		goto l196
	}
	if accept('f') {
		goto l201
	}
	if accept('n') {
		goto l206
	}
	if accept('r') {
		goto l211
	}
	if accept('t') {
		goto l216
	}
	if accept('u') {
		goto l221
	}
	if accept('v') {
		goto l238
	}
	if accept('x') {
		goto l243
	}
	if r < '0' {
		goto l133out
	}
	if accept2('7') {
		goto l146
	}
l133out:
	return id, length
l136:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l141:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l146:
	if r < '0' {
		goto l146out
	}
	if accept2('7') {
		goto l149
	}
l146out:
	return id, length
l149:
	if r < '0' {
		goto l149out
	}
	if accept2('7') {
		goto l152
	}
l149out:
	return id, length
l152:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l157:
	if r < '0' {
		goto l157out
	}
	if accept2('9') {
		goto l160
	}
	if r < 'A' {
		goto l157out
	}
	if accept2('F') {
		goto l160
	}
	if r < 'a' {
		goto l157out
	}
	if accept2('f') {
		goto l160
	}
l157out:
	return id, length
l160:
	if r < '0' {
		goto l160out
	}
	if accept2('9') {
		goto l163
	}
	if r < 'A' {
		goto l160out
	}
	if accept2('F') {
		goto l163
	}
	if r < 'a' {
		goto l160out
	}
	if accept2('f') {
		goto l163
	}
l160out:
	return id, length
l163:
	if r < '0' {
		goto l163out
	}
	if accept2('9') {
		goto l166
	}
	if r < 'A' {
		goto l163out
	}
	if accept2('F') {
		goto l166
	}
	if r < 'a' {
		goto l163out
	}
	if accept2('f') {
		goto l166
	}
l163out:
	return id, length
l166:
	if r < '0' {
		goto l166out
	}
	if accept2('9') {
		goto l169
	}
	if r < 'A' {
		goto l166out
	}
	if accept2('F') {
		goto l169
	}
	if r < 'a' {
		goto l166out
	}
	if accept2('f') {
		goto l169
	}
l166out:
	return id, length
l169:
	if r < '0' {
		goto l169out
	}
	if accept2('9') {
		goto l172
	}
	if r < 'A' {
		goto l169out
	}
	if accept2('F') {
		goto l172
	}
	if r < 'a' {
		goto l169out
	}
	if accept2('f') {
		goto l172
	}
l169out:
	return id, length
l172:
	if r < '0' {
		goto l172out
	}
	if accept2('9') {
		goto l175
	}
	if r < 'A' {
		goto l172out
	}
	if accept2('F') {
		goto l175
	}
	if r < 'a' {
		goto l172out
	}
	if accept2('f') {
		goto l175
	}
l172out:
	return id, length
l175:
	if r < '0' {
		goto l175out
	}
	if accept2('9') {
		goto l178
	}
	if r < 'A' {
		goto l175out
	}
	if accept2('F') {
		goto l178
	}
	if r < 'a' {
		goto l175out
	}
	if accept2('f') {
		goto l178
	}
l175out:
	return id, length
l178:
	if r < '0' {
		goto l178out
	}
	if accept2('9') {
		goto l181
	}
	if r < 'A' {
		goto l178out
	}
	if accept2('F') {
		goto l181
	}
	if r < 'a' {
		goto l178out
	}
	if accept2('f') {
		goto l181
	}
l178out:
	return id, length
l181:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l186:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l191:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l196:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l201:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l206:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l211:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l216:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l221:
	if r < '0' {
		goto l221out
	}
	if accept2('9') {
		goto l224
	}
	if r < 'A' {
		goto l221out
	}
	if accept2('F') {
		goto l224
	}
	if r < 'a' {
		goto l221out
	}
	if accept2('f') {
		goto l224
	}
l221out:
	return id, length
l224:
	if r < '0' {
		goto l224out
	}
	if accept2('9') {
		goto l227
	}
	if r < 'A' {
		goto l224out
	}
	if accept2('F') {
		goto l227
	}
	if r < 'a' {
		goto l224out
	}
	if accept2('f') {
		goto l227
	}
l224out:
	return id, length
l227:
	if r < '0' {
		goto l227out
	}
	if accept2('9') {
		goto l230
	}
	if r < 'A' {
		goto l227out
	}
	if accept2('F') {
		goto l230
	}
	if r < 'a' {
		goto l227out
	}
	if accept2('f') {
		goto l230
	}
l227out:
	return id, length
l230:
	if r < '0' {
		goto l230out
	}
	if accept2('9') {
		goto l233
	}
	if r < 'A' {
		goto l230out
	}
	if accept2('F') {
		goto l233
	}
	if r < 'a' {
		goto l230out
	}
	if accept2('f') {
		goto l233
	}
l230out:
	return id, length
l233:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l238:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l243:
	if r < '0' {
		goto l243out
	}
	if accept2('9') {
		goto l246
	}
	if r < 'A' {
		goto l243out
	}
	if accept2('F') {
		goto l246
	}
	if r < 'a' {
		goto l243out
	}
	if accept2('f') {
		goto l246
	}
l243out:
	return id, length
l246:
	if r < '0' {
		goto l246out
	}
	if accept2('9') {
		goto l249
	}
	if r < 'A' {
		goto l246out
	}
	if accept2('F') {
		goto l249
	}
	if r < 'a' {
		goto l246out
	}
	if accept2('f') {
		goto l249
	}
l246out:
	return id, length
l249:
	if accept('"') {
		goto l105
	}
	if accept('\\') {
		goto l107
	}
	return id, length
l254:
	id, length = 28, pos
	return id, length
l256:
	id, length = 29, pos
	return id, length
l258:
	id, length = 30, pos
	return id, length
l260:
	id, length = 31, pos
	return id, length
l262:
	id, length = 32, pos
	return id, length
l264:
	id, length = 33, pos
	return id, length
l266:
	id, length = 34, pos
	return id, length
l268:
	id, length = 35, pos
	return id, length
l270:
	id, length = 36, pos
	if accept('*') {
		goto l276
	}
	if accept('/') {
		goto l300
	}
	return id, length
l276:
	if accept('*') {
		goto l281
	}
	if accept2(')') {
		goto l295
	}
	if r < '+' {
		goto l278out
	}
	if accept2('\U0010ffff') {
		goto l295
	}
l278out:
	return id, length
l281:
	if accept('*') {
		goto l281
	}
	if accept('/') {
		goto l288
	}
	if accept2(')') {
		goto l290
	}
	if r < '+' {
		goto l285out
	}
	if accept2('.') {
		goto l290
	}
	if r < '0' {
		goto l285out
	}
	if accept2('\U0010ffff') {
		goto l290
	}
l285out:
	return id, length
l288:
	id, length = 50, pos
	return id, length
l290:
	if accept('*') {
		goto l281
	}
	if accept2(')') {
		goto l295
	}
	if r < '+' {
		goto l292out
	}
	if accept2('\U0010ffff') {
		goto l295
	}
l292out:
	return id, length
l295:
	if accept('*') {
		goto l281
	}
	if accept2(')') {
		goto l295
	}
	if r < '+' {
		goto l297out
	}
	if accept2('\U0010ffff') {
		goto l295
	}
l297out:
	return id, length
l300:
	id, length = 50, pos
	if accept2('\t') {
		goto l304
	}
	if r < '\v' {
		goto l301out
	}
	if accept2('\U0010ffff') {
		goto l304
	}
l301out:
	return id, length
l304:
	id, length = 50, pos
	if accept2('\t') {
		goto l304
	}
	if r < '\v' {
		goto l305out
	}
	if accept2('\U0010ffff') {
		goto l304
	}
l305out:
	return id, length
l308:
	id, length = 48, pos
	if accept('B') {
		goto l341
	}
	if accept('O') {
		goto l390
	}
	if accept('X') {
		goto l398
	}
	if accept('_') {
		goto l395
	}
	if accept('b') {
		goto l421
	}
	if accept('o') {
		goto l428
	}
	if accept('x') {
		goto l433
	}
	if r < '0' {
		goto l323out
	}
	if accept2('7') {
		goto l326
	}
l323out:
	return id, length
l326:
	id, length = 48, pos
	if accept('_') {
		goto l338
	}
	if r < '0' {
		goto l329out
	}
	if accept2('7') {
		goto l332
	}
l329out:
	return id, length
l332:
	id, length = 48, pos
	if accept('_') {
		goto l338
	}
	if r < '0' {
		goto l335out
	}
	if accept2('7') {
		goto l332
	}
l335out:
	return id, length
l338:
	if r < '0' {
		goto l338out
	}
	if accept2('7') {
		goto l332
	}
l338out:
	return id, length
l341:
	if accept('0') {
		goto l348
	}
	if accept('1') {
		goto l377
	}
	if accept('_') {
		goto l385
	}
	return id, length
l348:
	id, length = 48, pos
	if accept('0') {
		goto l356
	}
	if accept('1') {
		goto l364
	}
	if accept('_') {
		goto l372
	}
	return id, length
l356:
	id, length = 48, pos
	if accept('0') {
		goto l356
	}
	if accept('1') {
		goto l364
	}
	if accept('_') {
		goto l372
	}
	return id, length
l364:
	id, length = 48, pos
	if accept('0') {
		goto l356
	}
	if accept('1') {
		goto l364
	}
	if accept('_') {
		goto l372
	}
	return id, length
l372:
	if accept('0') {
		goto l356
	}
	if accept('1') {
		goto l364
	}
	return id, length
l377:
	id, length = 48, pos
	if accept('0') {
		goto l356
	}
	if accept('1') {
		goto l364
	}
	if accept('_') {
		goto l372
	}
	return id, length
l385:
	if accept('0') {
		goto l348
	}
	if accept('1') {
		goto l377
	}
	return id, length
l390:
	if accept('_') {
		goto l395
	}
	if r < '0' {
		goto l392out
	}
	if accept2('7') {
		goto l326
	}
l392out:
	return id, length
l395:
	if r < '0' {
		goto l395out
	}
	if accept2('7') {
		goto l326
	}
l395out:
	return id, length
l398:
	if accept('_') {
		goto l418
	}
	if r < '0' {
		goto l400out
	}
	if accept2('9') {
		goto l403
	}
	if r < 'A' {
		goto l400out
	}
	if accept2('F') {
		goto l403
	}
	if r < 'a' {
		goto l400out
	}
	if accept2('f') {
		goto l403
	}
l400out:
	return id, length
l403:
	id, length = 48, pos
	if accept('_') {
		goto l415
	}
	if r < '0' {
		goto l406out
	}
	if accept2('9') {
		goto l409
	}
	if r < 'A' {
		goto l406out
	}
	if accept2('F') {
		goto l409
	}
	if r < 'a' {
		goto l406out
	}
	if accept2('f') {
		goto l409
	}
l406out:
	return id, length
l409:
	id, length = 48, pos
	if accept('_') {
		goto l415
	}
	if r < '0' {
		goto l412out
	}
	if accept2('9') {
		goto l409
	}
	if r < 'A' {
		goto l412out
	}
	if accept2('F') {
		goto l409
	}
	if r < 'a' {
		goto l412out
	}
	if accept2('f') {
		goto l409
	}
l412out:
	return id, length
l415:
	if r < '0' {
		goto l415out
	}
	if accept2('9') {
		goto l409
	}
	if r < 'A' {
		goto l415out
	}
	if accept2('F') {
		goto l409
	}
	if r < 'a' {
		goto l415out
	}
	if accept2('f') {
		goto l409
	}
l415out:
	return id, length
l418:
	if r < '0' {
		goto l418out
	}
	if accept2('9') {
		goto l403
	}
	if r < 'A' {
		goto l418out
	}
	if accept2('F') {
		goto l403
	}
	if r < 'a' {
		goto l418out
	}
	if accept2('f') {
		goto l403
	}
l418out:
	return id, length
l421:
	if accept('0') {
		goto l348
	}
	if accept('1') {
		goto l377
	}
	if accept('_') {
		goto l385
	}
	return id, length
l428:
	if accept('_') {
		goto l395
	}
	if r < '0' {
		goto l430out
	}
	if accept2('7') {
		goto l326
	}
l430out:
	return id, length
l433:
	if accept('_') {
		goto l418
	}
	if r < '0' {
		goto l435out
	}
	if accept2('9') {
		goto l403
	}
	if r < 'A' {
		goto l435out
	}
	if accept2('F') {
		goto l403
	}
	if r < 'a' {
		goto l435out
	}
	if accept2('f') {
		goto l403
	}
l435out:
	return id, length
l438:
	id, length = 48, pos
	if accept('_') {
		goto l459
	}
	if r < '0' {
		goto l441out
	}
	if accept2('9') {
		goto l444
	}
l441out:
	return id, length
l444:
	id, length = 48, pos
	if accept('_') {
		goto l456
	}
	if r < '0' {
		goto l447out
	}
	if accept2('9') {
		goto l450
	}
l447out:
	return id, length
l450:
	id, length = 48, pos
	if accept('_') {
		goto l456
	}
	if r < '0' {
		goto l453out
	}
	if accept2('9') {
		goto l450
	}
l453out:
	return id, length
l456:
	if r < '0' {
		goto l456out
	}
	if accept2('9') {
		goto l450
	}
l456out:
	return id, length
l459:
	if r < '0' {
		goto l459out
	}
	if accept2('9') {
		goto l444
	}
l459out:
	return id, length
l462:
	id, length = 37, pos
	return id, length
l464:
	id, length = 38, pos
	if accept('-') {
		goto l472
	}
	if accept('<') {
		goto l474
	}
	if accept('=') {
		goto l476
	}
	return id, length
l472:
	id, length = 2, pos
	return id, length
l474:
	id, length = 3, pos
	return id, length
l476:
	id, length = 4, pos
	return id, length
l478:
	id, length = 39, pos
	if accept('=') {
		goto l482
	}
	return id, length
l482:
	id, length = 5, pos
	return id, length
l484:
	id, length = 40, pos
	if accept('=') {
		goto l490
	}
	if accept('>') {
		goto l492
	}
	return id, length
l490:
	id, length = 6, pos
	return id, length
l492:
	id, length = 7, pos
	return id, length
l494:
	id, length = 41, pos
	return id, length
l496:
	id, length = 42, pos
	return id, length
l498:
	id, length = 43, pos
	return id, length
l500:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l508:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l516:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l524:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l532:
	if accept('`') {
		goto l537
	}
	if accept2('_') {
		goto l539
	}
	if r < 'a' {
		goto l534out
	}
	if accept2('\U0010ffff') {
		goto l539
	}
l534out:
	return id, length
l537:
	id, length = 49, pos
	return id, length
l539:
	if accept('`') {
		goto l537
	}
	if accept2('_') {
		goto l539
	}
	if r < 'a' {
		goto l541out
	}
	if accept2('\U0010ffff') {
		goto l539
	}
l541out:
	return id, length
l544:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('o') {
		goto l556
	}
	if accept('y') {
		goto l584
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l556:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('o') {
		goto l566
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l566:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('l') {
		goto l576
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l576:
	id, length = 8, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l584:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l594
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l594:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l604
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l604:
	id, length = 9, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l612:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l626
	}
	if accept('h') {
		goto l654
	}
	if accept('o') {
		goto l682
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l626:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('s') {
		goto l636
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l636:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l646
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l646:
	id, length = 10, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l654:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l664
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l664:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('n') {
		goto l674
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l674:
	id, length = 11, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l682:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('n') {
		goto l692
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l692:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('s') {
		goto l702
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l702:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l712
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l712:
	id, length = 12, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l720:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l730
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l730:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('f') {
		goto l740
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l740:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l750
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l750:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('u') {
		goto l760
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l760:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('l') {
		goto l770
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l770:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l780
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l780:
	id, length = 13, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l788:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('l') {
		goto l798
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l798:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('s') {
		goto l808
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l808:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l818
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l818:
	id, length = 14, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l826:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l840
	}
	if accept('o') {
		goto l878
	}
	if accept('u') {
		goto l896
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l840:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('l') {
		goto l850
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l850:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('s') {
		goto l860
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l860:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l870
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l870:
	id, length = 15, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l878:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('r') {
		goto l888
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l888:
	id, length = 16, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l896:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('n') {
		goto l906
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l906:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('c') {
		goto l916
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l916:
	id, length = 17, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l924:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('o') {
		goto l934
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l934:
	id, length = 18, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l942:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('f') {
		goto l956
	}
	if accept('m') {
		goto l964
	}
	if accept('n') {
		goto l1012
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l956:
	id, length = 19, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l964:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('p') {
		goto l974
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l974:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('o') {
		goto l984
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l984:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('r') {
		goto l994
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l994:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l1004
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1004:
	id, length = 20, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1012:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l1022
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1022:
	id, length = 21, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1030:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l1040
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1040:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('c') {
		goto l1050
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1050:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('k') {
		goto l1060
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1060:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l1070
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1070:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('g') {
		goto l1080
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1080:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l1090
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1090:
	id, length = 22, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1098:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l1108
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1108:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l1118
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1118:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('u') {
		goto l1128
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1128:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('r') {
		goto l1138
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1138:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('n') {
		goto l1148
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1148:
	id, length = 23, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1156:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l1168
	}
	if accept('w') {
		goto l1216
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1168:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('l') {
		goto l1178
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1178:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l1188
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1188:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('c') {
		goto l1198
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1198:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l1208
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1208:
	id, length = 24, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1216:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('i') {
		goto l1226
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1226:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('t') {
		goto l1236
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1236:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('c') {
		goto l1246
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1246:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('h') {
		goto l1256
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1256:
	id, length = 25, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1264:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('r') {
		goto l1274
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1274:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('u') {
		goto l1284
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1284:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('e') {
		goto l1294
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1294:
	id, length = 26, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1302:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('a') {
		goto l1312
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1312:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if accept('r') {
		goto l1322
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1322:
	id, length = 27, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1330:
	id, length = 44, pos
	return id, length
l1332:
	id, length = 45, pos
	return id, length
l1334:
	id, length = 46, pos
	return id, length
l1336:
	id, length = 47, pos
	if accept('_') {
		goto l508
	}
	if unicode.Is(unicode.L, r) {
		move()
		goto l516
	}
	if unicode.Is(unicode.Nd, r) {
		move()
		goto l524
	}
	return id, length
l1344:
	id, length = 0, pos
	return id, length
}

// Scan is used internally from Parse.
func (p *Parser) Scan() (r Token) {
	return p.sc.Scan()
}

// init initalizes 'p' with content in 'src', assuming it comes from 'name'.
// 'src' becomes "owned" by 'p'. init invalidates any pre-existing ASTs produced by 'p'. Mutating
// 'src' invalidates the current AST returned from any parsing function called after init.
func (p *Parser) init(name string, src []byte) (err error) {
	p.eof = false
	p.errBudget = 10
	p.off = 0
	p.src = src
	p.tok = Token{}
	p.tokIndex = 0
	p.sc = NewRecScanner(name, p.src, p.scan, int(white_space))
	return nil
}

// AddOp grammar:
//
//	AddOp = "+" | "-" | "|" | "^" .
//
//	State 0
//		on  '+', '-', '^', '|'
//			shift and goto state 1
//	State 1
//		Accept
//
// AddOp is used internally from Parse.
func (p *Parser) AddOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(AddOp), 0)
	// state0:
	accept, errorSet = false, 38
	switch Symbol(p.tok.Ch) {
	case TOK_002b, TOK_002d, TOK_005e, TOK_007c:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ArgumentList grammar:
//
//	ArgumentList = Expression { "," Expression } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 1
//	State 1
//		Accept
//		on  ','
//			shift and goto state 0
//
// ArgumentList is used internally from Parse.
func (p *Parser) ArgumentList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ArgumentList), 0)
state0:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 39
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Block grammar:
//
//	Block = "{" { Statement } "}" .
//
//	State 0
//		on  '{'
//			shift and goto state 1
//	State 1
//		on  '}'
//			shift and goto state 2
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 1
//	State 2
//		Accept
//
// Block is used internally from Parse.
func (p *Parser) Block() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Block), 0)
	// state0:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 10
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CallSuffix grammar:
//
//	CallSuffix = "(" [ ArgumentList ] ")" .
//
//	State 0
//		on  '('
//			shift and goto state 1
//	State 1
//		on  ')'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call ArgumentList and goto state 3
//	State 2
//		Accept
//	State 3
//		on  ')'
//			shift and goto state 2
//
// CallSuffix is used internally from Parse.
func (p *Parser) CallSuffix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CallSuffix), 0)
	// state0:
	accept, errorSet = false, 33
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 13
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.ArgumentList())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 37
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CaseClause grammar:
//
//	CaseClause = CaseHead ":" { Statement } .
//
//	State 0
//		on  "case", "default"
//			call CaseHead and goto state 1
//	State 1
//		on  ':'
//			shift and goto state 2
//	State 2
//		Accept
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 2
//
// CaseClause is used internally from Parse.
func (p *Parser) CaseClause() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CaseClause), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case, TOK_default:
		r = p.add(r, p.CaseHead())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 41
	switch Symbol(p.tok.Ch) {
	case TOK_003a:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 11
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CaseHead grammar:
//
//	CaseHead   = "case" ExpressionList | "default" .
//
//	State 0
//		on  "case"
//			shift and goto state 1
//		on  "default"
//			shift and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call ExpressionList and goto state 2
//	State 2
//		Accept
//
// CaseHead is used internally from Parse.
func (p *Parser) CaseHead() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CaseHead), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case:
		r = append(r, p.shift())
		goto state1
	case TOK_default:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 16
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.ExpressionList())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CommClause grammar:
//
//	CommClause = CommHead ":" { Statement } .
//
//	State 0
//		on  "case", "default"
//			call CommHead and goto state 1
//	State 1
//		on  ':'
//			shift and goto state 2
//	State 2
//		Accept
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 2
//
// CommClause is used internally from Parse.
func (p *Parser) CommClause() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommClause), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case, TOK_default:
		r = p.add(r, p.CommHead())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 41
	switch Symbol(p.tok.Ch) {
	case TOK_003a:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 11
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CommHead grammar:
//
//	CommHead   = "case" CommOp | "default" .
//
//	State 0
//		on  "case"
//			shift and goto state 1
//		on  "default"
//			shift and goto state 2
//	State 1
//		on  "<-", identifier
//			call CommOp and goto state 2
//	State 2
//		Accept
//
// CommHead is used internally from Parse.
func (p *Parser) CommHead() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommHead), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case:
		r = append(r, p.shift())
		goto state1
	case TOK_default:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 25
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, identifier:
		r = p.add(r, p.CommOp())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CommOp grammar:
//
//	CommOp = "<-" Expression
//	       | identifier PostfixComm .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  identifier
//			shift and goto state 3
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", '.', '=', '['
//			call PostfixComm and goto state 2
//
// CommOp is used internally from Parse.
func (p *Parser) CommOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommOp), 0)
	// state0:
	accept, errorSet = false, 25
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case identifier:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 23
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_002e, TOK_003d, TOK_005b:
		r = p.add(r, p.PostfixComm())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// ConstDecl grammar:
//
//	ConstDecl = "const" identifier "=" Expression .
//
//	State 0
//		on  "const"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  '='
//			shift and goto state 3
//	State 3
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 4
//	State 4
//		Accept
//
// ConstDecl is used internally from Parse.
func (p *Parser) ConstDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ConstDecl), 0)
	// state0:
	accept, errorSet = false, 7
	switch Symbol(p.tok.Ch) {
	case TOK_const:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 42
	switch Symbol(p.tok.Ch) {
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Expression grammar:
//
//	Expression = SimpleExpr [ RelOp SimpleExpr ] .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call SimpleExpr and goto state 1
//	State 1
//		Accept
//		on  "!=", "<=", "==", ">=", '<', '>'
//			call RelOp and goto state 2
//	State 2
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call SimpleExpr and goto state 3
//	State 3
//		Accept
//
// Expression is used internally from Parse.
func (p *Parser) Expression() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Expression), 0)
	// state0:
	accept, errorSet = false, 18
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.SimpleExpr())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	switch Symbol(p.tok.Ch) {
	case TOK_0021003d, TOK_003c003d, TOK_003d003d, TOK_003e003d, TOK_003c, TOK_003e:
		r = p.add(r, p.RelOp())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 18
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.SimpleExpr())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ExpressionList grammar:
//
//	ExpressionList = Expression { "," Expression } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 1
//	State 1
//		Accept
//		on  ','
//			shift and goto state 0
//
// ExpressionList is used internally from Parse.
func (p *Parser) ExpressionList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ExpressionList), 0)
state0:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 39
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Factor grammar:
//
//	Factor = identifier [ FactorSuffix ]
//	       | int_lit
//	       | string_lit
//	       | "true"
//	       | "false"
//	       | "<-" Expression
//	       | "(" Expression ")" .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  "false", "true", int_lit, string_lit
//			shift and goto state 2
//		on  '('
//			shift and goto state 3
//		on  identifier
//			shift and goto state 5
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 4
//	State 4
//		on  ')'
//			shift and goto state 2
//	State 5
//		Accept
//		on  '(', '.', '['
//			call FactorSuffix and goto state 2
//
// Factor is used internally from Parse.
func (p *Parser) Factor() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Factor), 0)
	// state0:
	accept, errorSet = false, 20
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_false, TOK_true, int_lit, string_lit:
		r = append(r, p.shift())
		goto state2
	case TOK_0028:
		r = append(r, p.shift())
		goto state3
	case identifier:
		r = append(r, p.shift())
		goto state5
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 37
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = true, 31
	switch Symbol(p.tok.Ch) {
	case TOK_0028, TOK_002e, TOK_005b:
		r = p.add(r, p.FactorSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// FactorSuffix grammar:
//
//	FactorSuffix = { Selector | Index } [ CallSuffix ] .
//
//	State 0
//		Accept
//		on  '.'
//			call Selector and goto state 1
//		on  '['
//			call Index and goto state 1
//		on  '('
//			call CallSuffix and goto state 2
//	State 1
//		Accept
//		on  '.'
//			call Selector and goto state 1
//		on  '['
//			call Index and goto state 1
//		on  '('
//			call CallSuffix and goto state 2
//	State 2
//		Accept
//
// FactorSuffix is used internally from Parse.
func (p *Parser) FactorSuffix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(FactorSuffix), 0)
	// state0:
	accept, errorSet = true, 32
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state1
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state1
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 32
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state1
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state1
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// FuncDecl grammar:
//
//	FuncDecl = "func" identifier "(" [ ParameterList ] ")" [ Type ] Block .
//
//	State 0
//		on  "func"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  '('
//			shift and goto state 3
//	State 3
//		on  ')'
//			shift and goto state 4
//		on  identifier
//			call ParameterList and goto state 7
//	State 4
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 5
//		on  '{'
//			call Block and goto state 6
//	State 5
//		on  '{'
//			call Block and goto state 6
//	State 6
//		Accept
//	State 7
//		on  ')'
//			shift and goto state 4
//
// FuncDecl is used internally from Parse.
func (p *Parser) FuncDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(FuncDecl), 0)
	// state0:
	accept, errorSet = false, 9
	switch Symbol(p.tok.Ch) {
	case TOK_func:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 33
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 36
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state4
	case identifier:
		r = p.add(r, p.ParameterList())
		goto state7
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 48
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state5
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state6:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state7:
	accept, errorSet = false, 37
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
}

// ImportDecl grammar:
//
//	ImportDecl = "import" string_lit .
//
//	State 0
//		on  "import"
//			shift and goto state 1
//	State 1
//		on  string_lit
//			shift and goto state 2
//	State 2
//		Accept
//
// ImportDecl is used internally from Parse.
func (p *Parser) ImportDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ImportDecl), 0)
	// state0:
	accept, errorSet = false, 26
	switch Symbol(p.tok.Ch) {
	case TOK_import:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 47
	switch Symbol(p.tok.Ch) {
	case string_lit:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Index grammar:
//
//	Index = "[" Expression "]" .
//
//	State 0
//		on  '['
//			shift and goto state 1
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		on  ']'
//			shift and goto state 3
//	State 3
//		Accept
//
// Index is used internally from Parse.
func (p *Parser) Index() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Index), 0)
	// state0:
	accept, errorSet = false, 43
	switch Symbol(p.tok.Ch) {
	case TOK_005b:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// MulOp grammar:
//
//	MulOp = "*" | "/" | "<<" | ">>" | "&" .
//
//	State 0
//		on  "<<", ">>", '&', '*', '/'
//			shift and goto state 1
//	State 1
//		Accept
//
// MulOp is used internally from Parse.
func (p *Parser) MulOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(MulOp), 0)
	// state0:
	accept, errorSet = false, 35
	switch Symbol(p.tok.Ch) {
	case TOK_003c003c, TOK_003e003e, TOK_0026, TOK_002a, TOK_002f:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// PackageClause grammar:
//
//	PackageClause = "package" identifier .
//
//	State 0
//		on  "package"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		Accept
//
// PackageClause is used internally from Parse.
func (p *Parser) PackageClause() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(PackageClause), 0)
	// state0:
	accept, errorSet = false, 27
	switch Symbol(p.tok.Ch) {
	case TOK_package:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ParameterList grammar:
//
//	ParameterList = identifier Type { "," identifier Type } .
//
//	State 0
//		on  identifier
//			shift and goto state 1
//	State 1
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 2
//	State 2
//		Accept
//		on  ','
//			shift and goto state 0
//
// ParameterList is used internally from Parse.
func (p *Parser) ParameterList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ParameterList), 0)
state0:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 49
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 39
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Postfix grammar:
//
//	Postfix = { Selector | Index } ( "=" Expression | "<-" Expression | CallSuffix ) .
//
//	State 0
//		on  "<-", '='
//			shift and goto state 1
//		on  '.'
//			call Selector and goto state 3
//		on  '['
//			call Index and goto state 3
//		on  '('
//			call CallSuffix and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", '='
//			shift and goto state 1
//		on  '.'
//			call Selector and goto state 3
//		on  '['
//			call Index and goto state 3
//		on  '('
//			call CallSuffix and goto state 2
//
// Postfix is used internally from Parse.
func (p *Parser) Postfix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Postfix), 0)
	// state0:
	accept, errorSet = false, 22
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_003d:
		r = append(r, p.shift())
		goto state1
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state3
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state3
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 22
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_003d:
		r = append(r, p.shift())
		goto state1
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state3
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state3
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// PostfixComm grammar:
//
//	PostfixComm = { Selector | Index } ( "=" "<-" Expression | "<-" Expression ) .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  '='
//			shift and goto state 3
//		on  '.'
//			call Selector and goto state 4
//		on  '['
//			call Index and goto state 4
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-"
//			shift and goto state 1
//	State 4
//		on  "<-"
//			shift and goto state 1
//		on  '='
//			shift and goto state 3
//		on  '.'
//			call Selector and goto state 4
//		on  '['
//			call Index and goto state 4
//
// PostfixComm is used internally from Parse.
func (p *Parser) PostfixComm() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(PostfixComm), 0)
	// state0:
	accept, errorSet = false, 24
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state4
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 34
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 24
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state4
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state4
	}
	return p.stop(r, accept, errorSet)
}

// RelOp grammar:
//
//	RelOp = "==" | "!=" | "<" | "<=" | ">" | ">=" .
//
//	State 0
//		on  "!=", "<=", "==", ">=", '<', '>'
//			shift and goto state 1
//	State 1
//		Accept
//
// RelOp is used internally from Parse.
func (p *Parser) RelOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(RelOp), 0)
	// state0:
	accept, errorSet = false, 0
	switch Symbol(p.tok.Ch) {
	case TOK_0021003d, TOK_003c003d, TOK_003d003d, TOK_003e003d, TOK_003c, TOK_003e:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// SelectStmt grammar:
//
//	SelectStmt = "select" "{" { CommClause } "}" .
//
//	State 0
//		on  "select"
//			shift and goto state 1
//	State 1
//		on  '{'
//			shift and goto state 2
//	State 2
//		on  '}'
//			shift and goto state 3
//		on  "case", "default"
//			call CommClause and goto state 2
//	State 3
//		Accept
//
// SelectStmt is used internally from Parse.
func (p *Parser) SelectStmt() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SelectStmt), 0)
	// state0:
	accept, errorSet = false, 28
	switch Symbol(p.tok.Ch) {
	case TOK_select:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 2
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state3
	case TOK_case, TOK_default:
		r = p.add(r, p.CommClause())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Selector grammar:
//
//	Selector = "." identifier .
//
//	State 0
//		on  '.'
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		Accept
//
// Selector is used internally from Parse.
func (p *Parser) Selector() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Selector), 0)
	// state0:
	accept, errorSet = false, 40
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// SimpleExpr grammar:
//
//	SimpleExpr = Term { AddOp Term } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Term and goto state 1
//	State 1
//		Accept
//		on  '+', '-', '^', '|'
//			call AddOp and goto state 0
//
// SimpleExpr is used internally from Parse.
func (p *Parser) SimpleExpr() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SimpleExpr), 0)
state0:
	accept, errorSet = false, 19
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Term())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 38
	switch Symbol(p.tok.Ch) {
	case TOK_002b, TOK_002d, TOK_005e, TOK_007c:
		r = p.add(r, p.AddOp())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// SourceFile grammar:
//
//	SourceFile = PackageClause { ImportDecl } { TopLevelDecl } .
//
//	State 0
//		on  "package"
//			call PackageClause and goto state 1
//	State 1
//		Accept
//		on  "import"
//			call ImportDecl and goto state 1
//		on  "const", "func", "var"
//			call TopLevelDecl and goto state 2
//	State 2
//		Accept
//		on  "const", "func", "var"
//			call TopLevelDecl and goto state 2
//
// SourceFile is used internally from Parse.
func (p *Parser) SourceFile() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SourceFile), 0)
	// state0:
	accept, errorSet = false, 27
	switch Symbol(p.tok.Ch) {
	case TOK_package:
		r = p.add(r, p.PackageClause())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 4
	switch Symbol(p.tok.Ch) {
	case TOK_import:
		r = p.add(r, p.ImportDecl())
		goto state1
	case TOK_const, TOK_func, TOK_var:
		r = p.add(r, p.TopLevelDecl())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 5
	switch Symbol(p.tok.Ch) {
	case TOK_const, TOK_func, TOK_var:
		r = p.add(r, p.TopLevelDecl())
		goto state2
	}
	if accept = accept && p.eof; accept {
		r = append(r, p.shift())
	}
	r[1] = int32(len(r) - 2)
	if !accept {
		p.err(p.tok.Position(), "%q [%s]: expected %v", p.tok.Src(), Symbol(p.tok.Ch), errorSets[errorSet])
	}
	return r
}

// Statement grammar:
//
//	Statement = VarDecl
//	          | ConstDecl
//	          | "if" Expression Block [ "else" Block ]
//	          | "for" [ Expression ] Block
//	          | "return" [ Expression ]
//	          | "go" identifier CallSuffix
//	          | SwitchStmt
//	          | SelectStmt
//	          | "<-" Expression
//	          | identifier Postfix .
//
//	State 0
//		on  "return"
//			shift and goto state 10
//		on  identifier
//			shift and goto state 11
//		on  "<-"
//			shift and goto state 1
//		on  "for"
//			shift and goto state 3
//		on  "go"
//			shift and goto state 5
//		on  "if"
//			shift and goto state 7
//		on  "const"
//			call ConstDecl and goto state 2
//		on  "var"
//			call VarDecl and goto state 2
//		on  "switch"
//			call SwitchStmt and goto state 2
//		on  "select"
//			call SelectStmt and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  '{'
//			call Block and goto state 2
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 4
//	State 4
//		on  '{'
//			call Block and goto state 2
//	State 5
//		on  identifier
//			shift and goto state 6
//	State 6
//		on  '('
//			call CallSuffix and goto state 2
//	State 7
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 8
//	State 8
//		on  '{'
//			call Block and goto state 9
//	State 9
//		Accept
//		on  "else"
//			shift and goto state 4
//	State 10
//		Accept
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 2
//	State 11
//		on  "<-", '(', '.', '=', '['
//			call Postfix and goto state 2
//
// Statement is used internally from Parse.
func (p *Parser) Statement() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Statement), 0)
	// state0:
	accept, errorSet = false, 12
	switch Symbol(p.tok.Ch) {
	case TOK_return:
		r = append(r, p.shift())
		goto state10
	case identifier:
		r = append(r, p.shift())
		goto state11
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_for:
		r = append(r, p.shift())
		goto state3
	case TOK_go:
		r = append(r, p.shift())
		goto state5
	case TOK_if:
		r = append(r, p.shift())
		goto state7
	case TOK_const:
		r = p.add(r, p.ConstDecl())
		goto state2
	case TOK_var:
		r = p.add(r, p.VarDecl())
		goto state2
	case TOK_switch:
		r = p.add(r, p.SwitchStmt())
		goto state2
	case TOK_select:
		r = p.add(r, p.SelectStmt())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 15
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state6:
	accept, errorSet = false, 33
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state7:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state8
	}
	return p.stop(r, accept, errorSet)
state8:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state9
	}
	return p.stop(r, accept, errorSet)
state9:
	accept, errorSet = true, 8
	switch Symbol(p.tok.Ch) {
	case TOK_else:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state10:
	accept, errorSet = true, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state11:
	accept, errorSet = false, 21
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_0028, TOK_002e, TOK_003d, TOK_005b:
		r = p.add(r, p.Postfix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// SwitchStmt grammar:
//
//	SwitchStmt = "switch" [ Expression ] "{" { CaseClause } "}" .
//
//	State 0
//		on  "switch"
//			shift and goto state 1
//	State 1
//		on  '{'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 4
//	State 2
//		on  '}'
//			shift and goto state 3
//		on  "case", "default"
//			call CaseClause and goto state 2
//	State 3
//		Accept
//	State 4
//		on  '{'
//			shift and goto state 2
//
// SwitchStmt is used internally from Parse.
func (p *Parser) SwitchStmt() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SwitchStmt), 0)
	// state0:
	accept, errorSet = false, 29
	switch Symbol(p.tok.Ch) {
	case TOK_switch:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 15
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 1
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state3
	case TOK_case, TOK_default:
		r = p.add(r, p.CaseClause())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// Term grammar:
//
//	Term       = Factor { MulOp Factor } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Factor and goto state 1
//	State 1
//		Accept
//		on  "<<", ">>", '&', '*', '/'
//			call MulOp and goto state 0
//
// Term is used internally from Parse.
func (p *Parser) Term() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Term), 0)
state0:
	accept, errorSet = false, 20
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Factor())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 35
	switch Symbol(p.tok.Ch) {
	case TOK_003c003c, TOK_003e003e, TOK_0026, TOK_002a, TOK_002f:
		r = p.add(r, p.MulOp())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// TopLevelDecl grammar:
//
//	TopLevelDecl = FuncDecl | VarDecl | ConstDecl .
//
//	State 0
//		on  "const"
//			call ConstDecl and goto state 1
//		on  "var"
//			call VarDecl and goto state 1
//		on  "func"
//			call FuncDecl and goto state 1
//	State 1
//		Accept
//
// TopLevelDecl is used internally from Parse.
func (p *Parser) TopLevelDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(TopLevelDecl), 0)
	// state0:
	accept, errorSet = false, 6
	switch Symbol(p.tok.Ch) {
	case TOK_const:
		r = p.add(r, p.ConstDecl())
		goto state1
	case TOK_var:
		r = p.add(r, p.VarDecl())
		goto state1
	case TOK_func:
		r = p.add(r, p.FuncDecl())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Type grammar:
//
//	Type = "int" | "bool" | "byte" | "chan" Type | "[" [ Expression ] "]" Type .
//
//	State 0
//		on  "bool", "byte", "int"
//			shift and goto state 1
//		on  "chan"
//			shift and goto state 2
//		on  '['
//			shift and goto state 3
//	State 1
//		Accept
//	State 2
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 1
//	State 3
//		on  ']'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 4
//	State 4
//		on  ']'
//			shift and goto state 2
//
// Type is used internally from Parse.
func (p *Parser) Type() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Type), 0)
	// state0:
	accept, errorSet = false, 49
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_int:
		r = append(r, p.shift())
		goto state1
	case TOK_chan:
		r = append(r, p.shift())
		goto state2
	case TOK_005b:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 49
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 14
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// VarDecl grammar:
//
//	VarDecl = "var" identifier Type [ "=" Expression ] .
//
//	State 0
//		on  "var"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 3
//	State 3
//		Accept
//		on  '='
//			shift and goto state 4
//	State 4
//		on  "<-", "false", "true", '(', identifier, int_lit, string_lit
//			call Expression and goto state 5
//	State 5
//		Accept
//
// VarDecl is used internally from Parse.
func (p *Parser) VarDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(VarDecl), 0)
	// state0:
	accept, errorSet = false, 30
	switch Symbol(p.tok.Ch) {
	case TOK_var:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 49
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 42
	switch Symbol(p.tok.Ch) {
	case TOK_003d:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, int_lit, string_lit:
		r = p.add(r, p.Expression())
		goto state5
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

func (p *Parser) shift() (r int32) {
	r = p.tokIndex
	if !p.eof {
		p.tok = p.Scan()
		p.tokIndex++
		p.eof = p.tok.Ch == rune(TOK_EOF)
	}
	return r
}

func (p *Parser) get() (r []int32) {
	if n := len(p.cache); n != 0 {
		r = p.cache[n-1][:0]
		p.cache = p.cache[:n-1]
	}
	return r
}

func (p *Parser) add(r, s []int32) (t []int32) {
	p.cache = append(p.cache, s)
	return append(r, s...)
}

func (p *Parser) stop(r []int32, accept bool, errorSet int) []int32 {
	r[1] = int32(len(r) - 2)
	if !accept {
		p.err(p.tok.Position(), "%q [%s]: expected %v", p.tok.Src(), Symbol(p.tok.Ch), errorSets[errorSet])
	}
	return r
}

// EOF reports whether the parser lookahead token is EOF.
func (p *Parser) EOF() bool {
	return p.eof
}

// Token returns the n-th token in 'p'. Token panics if 'n' is out of range.
func (p *Parser) Token(n int32) (r Token) {
	return p.sc.Token(int(n))
}

// Parse parses 'src'. 'src' becomes "owned" by the parser and must not be
// mutated afterwards.
func (p *Parser) Parse(name string, src []byte) (ast []int32, err error) {
	if err = p.init(name, src); err != nil {
		return nil, err
	}

	defer func() {
		switch e := recover(); x := e.(type) {
		case nil:
			// ok
		case scanner.ErrList:
			err = x
		case error:
			err = errors.Join(err, x)
		default:
			err = errors.Join(err, fmt.Errorf("%v", x))
		}
	}()

	p.tok = p.Scan()
	ast = p.SourceFile()
	return ast, p.sc.Err()
}

func (p *Parser) err0(pos token.Position, s string, args ...any) {
	p.sc.AddErr(pos, s, args...)
	if p.errBudget--; p.errBudget == 0 {
		p.sc.AddErr(pos, "too many errors")
	}
}

func (p *Parser) err(pos token.Position, s string, args ...any) {
	p.err0(pos, s, args...)
	p.shift()
	if p.eof {
		panic(p.sc.Err())
	}
}
