// Code generated by 'egg -o parser.go -start SourceFile -package octogo octogo.ebnf', DO NOT EDIT.

// Parser generated from octogo.ebnf.

package octogo

import (
	"errors"
	"fmt"
	"go/token"
	"strconv"
	"unicode"
	"unicode/utf8"

	"modernc.org/scanner"
)

var _ = unicode.MaxRune

// Symbols
const (
	TOK_EOF        = Symbol(0)  // EOF
	TOK_0021003d   = Symbol(1)  // "!="
	TOK_003c002d   = Symbol(2)  // "<-"
	TOK_003c003c   = Symbol(3)  // "<<"
	TOK_003c003d   = Symbol(4)  // "<="
	TOK_003d003d   = Symbol(5)  // "=="
	TOK_003e003d   = Symbol(6)  // ">="
	TOK_003e003e   = Symbol(7)  // ">>"
	TOK_bool       = Symbol(8)  // "bool"
	TOK_byte       = Symbol(9)  // "byte"
	TOK_case       = Symbol(10) // "case"
	TOK_chan       = Symbol(11) // "chan"
	TOK_const      = Symbol(12) // "const"
	TOK_default    = Symbol(13) // "default"
	TOK_else       = Symbol(14) // "else"
	TOK_false      = Symbol(15) // "false"
	TOK_for        = Symbol(16) // "for"
	TOK_func       = Symbol(17) // "func"
	TOK_go         = Symbol(18) // "go"
	TOK_if         = Symbol(19) // "if"
	TOK_import     = Symbol(20) // "import"
	TOK_int        = Symbol(21) // "int"
	TOK_return     = Symbol(22) // "return"
	TOK_select     = Symbol(23) // "select"
	TOK_switch     = Symbol(24) // "switch"
	TOK_true       = Symbol(25) // "true"
	TOK_var        = Symbol(26) // "var"
	TOK_0026       = Symbol(27) // '&'
	TOK_0028       = Symbol(28) // '('
	TOK_0029       = Symbol(29) // ')'
	TOK_002a       = Symbol(30) // '*'
	TOK_002b       = Symbol(31) // '+'
	TOK_002c       = Symbol(32) // ','
	TOK_002d       = Symbol(33) // '-'
	TOK_002e       = Symbol(34) // '.'
	TOK_002f       = Symbol(35) // '/'
	TOK_003a       = Symbol(36) // ':'
	TOK_003c       = Symbol(37) // '<'
	TOK_003d       = Symbol(38) // '='
	TOK_003e       = Symbol(39) // '>'
	TOK_005b       = Symbol(40) // '['
	TOK_005d       = Symbol(41) // ']'
	TOK_005e       = Symbol(42) // '^'
	TOK_007b       = Symbol(43) // '{'
	TOK_007c       = Symbol(44) // '|'
	TOK_007d       = Symbol(45) // '}'
	identifier     = Symbol(46) // identifier
	number         = Symbol(47) // number
	string_literal = Symbol(48) // string_literal
	white_space    = Symbol(49) // white_space
	SourceFile     = Symbol(50) // SourceFile
	ImportDecl     = Symbol(51) // ImportDecl
	TopLevelDecl   = Symbol(52) // TopLevelDecl
	ConstDecl      = Symbol(53) // ConstDecl
	Type           = Symbol(54) // Type
	VarDecl        = Symbol(55) // VarDecl
	FuncDecl       = Symbol(56) // FuncDecl
	ParameterList  = Symbol(57) // ParameterList
	Block          = Symbol(58) // Block
	Statement      = Symbol(59) // Statement
	Postfix        = Symbol(60) // Postfix
	Selector       = Symbol(61) // Selector
	Index          = Symbol(62) // Index
	CallSuffix     = Symbol(63) // CallSuffix
	ArgumentList   = Symbol(64) // ArgumentList
	SwitchStmt     = Symbol(65) // SwitchStmt
	CaseClause     = Symbol(66) // CaseClause
	CaseHead       = Symbol(67) // CaseHead
	ExpressionList = Symbol(68) // ExpressionList
	SelectStmt     = Symbol(69) // SelectStmt
	CommClause     = Symbol(70) // CommClause
	CommHead       = Symbol(71) // CommHead
	CommOp         = Symbol(72) // CommOp
	PostfixComm    = Symbol(73) // PostfixComm
	Expression     = Symbol(74) // Expression
	SimpleExpr     = Symbol(75) // SimpleExpr
	Term           = Symbol(76) // Term
	Factor         = Symbol(77) // Factor
	FactorSuffix   = Symbol(78) // FactorSuffix
	RelOp          = Symbol(79) // RelOp
	AddOp          = Symbol(80) // AddOp
	MulOp          = Symbol(81) // MulOp
)

const SymbolNames = "EOF\"!=\"\"<-\"\"<<\"\"<=\"\"==\"\">=\"\">>\"\"bool\"\"byte\"\"case\"\"chan\"\"const\"\"default\"\"else\"\"false\"\"for\"\"func\"\"go\"\"if\"\"import\"\"int\"\"return\"\"select\"\"switch\"\"true\"\"var\"'&''('')''*''+'',''-''.''/'':''<''=''>''['']''^''{''|''}'identifiernumberstring_literalwhite_spaceSourceFileImportDeclTopLevelDeclConstDeclTypeVarDeclFuncDeclParameterListBlockStatementPostfixSelectorIndexCallSuffixArgumentListSwitchStmtCaseClauseCaseHeadExpressionListSelectStmtCommClauseCommHeadCommOpPostfixCommExpressionSimpleExprTermFactorFactorSuffixRelOpAddOpMulOp"

var SymbolIndex = [...]uint16{0, 3, 7, 11, 15, 19, 23, 27, 31, 37, 43, 49, 55, 62, 71, 77, 84, 89, 95, 99, 103, 111, 116, 124, 132, 140, 146, 151, 154, 157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 208, 218, 224, 238, 249, 259, 269, 281, 290, 294, 301, 309, 322, 327, 336, 343, 351, 356, 366, 378, 388, 398, 406, 420, 430, 440, 448, 454, 465, 475, 485, 489, 495, 507, 512, 517, 522}

func (s Symbol) String() string {
	idx := int(s) - 0
	if s < 0 || idx >= len(SymbolIndex)-1 {
		return "Symbol(" + strconv.FormatInt(int64(s), 10) + ")"
	}
	return SymbolNames[SymbolIndex[idx]:SymbolIndex[idx+1]]
}

var errorSets = [...][]Symbol{
	{TOK_003e, TOK_003c, TOK_003e003d, TOK_003d003d, TOK_003c003d, TOK_0021003d},
	{CaseHead, TOK_007d, TOK_default, TOK_case},
	{CommHead, TOK_007d, TOK_default, TOK_case},
	{TOK_default, TOK_case},
	{FuncDecl, VarDecl, ConstDecl, TOK_var, TOK_import, TOK_func, TOK_const},
	{FuncDecl, VarDecl, ConstDecl, TOK_var, TOK_func, TOK_const},
	{TOK_var, TOK_func, TOK_const},
	{TOK_const},
	{TOK_else},
	{TOK_func},
	{SelectStmt, SwitchStmt, VarDecl, ConstDecl, identifier, TOK_007d, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{SelectStmt, SwitchStmt, VarDecl, ConstDecl, identifier, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{identifier, TOK_var, TOK_switch, TOK_select, TOK_return, TOK_if, TOK_go, TOK_for, TOK_const, TOK_003c002d},
	{Factor, Term, SimpleExpr, Expression, string_literal, number, identifier, TOK_0029, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_literal, number, identifier, TOK_005d, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_literal, number, identifier, TOK_007b, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, Expression, string_literal, number, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, SimpleExpr, string_literal, number, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, Term, string_literal, number, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{Factor, string_literal, number, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{string_literal, number, identifier, TOK_0028, TOK_true, TOK_false, TOK_003c002d},
	{CallSuffix, Index, Selector, TOK_005b, TOK_003d, TOK_002e, TOK_0028, TOK_003c002d},
	{TOK_005b, TOK_003d, TOK_002e, TOK_0028, TOK_003c002d},
	{Index, Selector, TOK_005b, TOK_003d, TOK_002e, TOK_003c002d},
	{TOK_005b, TOK_003d, TOK_002e, TOK_003c002d},
	{identifier, TOK_003c002d},
	{TOK_import},
	{TOK_select},
	{TOK_switch},
	{TOK_var},
	{CallSuffix, Index, Selector, TOK_005b, TOK_002e, TOK_0028},
	{TOK_005b, TOK_002e, TOK_0028},
	{TOK_0028},
	{identifier, TOK_0029},
	{TOK_0029},
	{TOK_003c002d},
	{TOK_002f, TOK_002a, TOK_0026, TOK_003e003e, TOK_003c003c},
	{TOK_007c, TOK_005e, TOK_002d, TOK_002b},
	{TOK_002c},
	{TOK_002e},
	{TOK_003a},
	{TOK_003d},
	{TOK_005b},
	{TOK_005d},
	{TOK_007b},
	{identifier},
	{string_literal},
	{TOK_007b, TOK_005b, TOK_int, TOK_chan, TOK_byte, TOK_bool},
	{TOK_005b, TOK_int, TOK_chan, TOK_byte, TOK_bool},
}

type Parser struct {
	cache     [][]int32
	eof       bool
	errBudget int
	off       int
	sc        *scanner.RecScanner
	src       []byte
	tok       scanner.Token // current lookahead
	tokIndex  int32         // For scanner.Token(tokIndex)
}

type Symbol int32

// scan recognizes longest UTF-8 lexemes. Lower IDs take precedence on same length.
//
//	id   0: $
//	id   1: !=
//	id   2: <-
//	id   3: <<
//	id   4: <=
//	id   5: ==
//	id   6: >=
//	id   7: >>
//	id   8: bool
//	id   9: byte
//	id  10: case
//	id  11: chan
//	id  12: const
//	id  13: default
//	id  14: else
//	id  15: false
//	id  16: for
//	id  17: func
//	id  18: go
//	id  19: if
//	id  20: import
//	id  21: int
//	id  22: return
//	id  23: select
//	id  24: switch
//	id  25: true
//	id  26: var
//	id  27: &
//	id  28: \(
//	id  29: \)
//	id  30: \*
//	id  31: \+
//	id  32: ,
//	id  33: -
//	id  34: \.
//	id  35: /
//	id  36: :
//	id  37: <
//	id  38: =
//	id  39: >
//	id  40: \[
//	id  41: \]
//	id  42: \^
//	id  43: \{
//	id  44: \|
//	id  45: \}
//	id  46: ([a-zA-Z_][a-zA-Z0-9_]*)
//	id  47: ([0-9]+)
//	id  48: ("(?:[^"\\]|\\.)*")
//	id  49: (/\*([^*]|\*+[^*/])*\*+/|//.*| |\t|\n|\r)
//
// ID == -1 is returned when no lexeme was recognized.
func (*Parser) scan(s []byte) (id, length int) {
	const endOfText = 0x110000
	var pos, pos0, width, width1 int
	id = -1
	var r, r1 rune
	_ = pos0
	_ = r
	_ = r1
	_ = width1
	step := func(pos int) (r rune, n int) {
		if pos < len(s) {
			c := s[pos]
			if c < utf8.RuneSelf {
				return rune(c), 1
			}
			return utf8.DecodeRune(s[pos:])
		}
		return endOfText, 0
	}
	move := func() {
		pos += width
		if r, width = r1, width1; r != endOfText {
			r1, width1 = step(pos + width)
		}
	}
	accept := func(x rune) bool {
		if r == x {
			move()
			return true
		}
		return false
	}
	_ = accept
	accept2 := func(x rune) bool {
		if r <= x {
			move()
			return true
		}
		return false
	}
	_ = accept2
	r, r1 = endOfText, endOfText
	width, width1 = 0, 0
	r, width = step(pos)
	if r != endOfText {
		r1, width1 = step(pos + width)
	}
	if accept('\t') {
		goto l79
	}
	if accept('\n') {
		goto l81
	}
	if accept('\r') {
		goto l83
	}
	if accept(' ') {
		goto l85
	}
	if accept('!') {
		goto l87
	}
	if accept('"') {
		goto l92
	}
	if accept('&') {
		goto l118
	}
	if accept('(') {
		goto l120
	}
	if accept(')') {
		goto l122
	}
	if accept('*') {
		goto l124
	}
	if accept('+') {
		goto l126
	}
	if accept(',') {
		goto l128
	}
	if accept('-') {
		goto l130
	}
	if accept('.') {
		goto l132
	}
	if accept('/') {
		goto l134
	}
	if accept(':') {
		goto l176
	}
	if accept('<') {
		goto l178
	}
	if accept('=') {
		goto l192
	}
	if accept('>') {
		goto l198
	}
	if accept('[') {
		goto l216
	}
	if accept(']') {
		goto l218
	}
	if accept('^') {
		goto l220
	}
	if accept('b') {
		goto l222
	}
	if accept('c') {
		goto l262
	}
	if accept('d') {
		goto l326
	}
	if accept('e') {
		goto l366
	}
	if accept('f') {
		goto l388
	}
	if accept('g') {
		goto l446
	}
	if accept('i') {
		goto l456
	}
	if accept('r') {
		goto l508
	}
	if accept('s') {
		goto l542
	}
	if accept('t') {
		goto l606
	}
	if accept('v') {
		goto l628
	}
	if accept('{') {
		goto l644
	}
	if accept('|') {
		goto l646
	}
	if accept('}') {
		goto l648
	}
	if r < '0' {
		goto l72out
	}
	if accept2('9') {
		goto l172
	}
l72out:
	if r < 'A' {
		goto l74out
	}
	if accept2('Z') {
		goto l208
	}
	if accept('_') {
		goto l208
	}
	if accept('a') {
		goto l208
	}
	if accept('h') {
		goto l208
	}
	if r < 'j' {
		goto l74out
	}
	if accept2('q') {
		goto l208
	}
	if accept('u') {
		goto l208
	}
	if r < 'w' {
		goto l74out
	}
	if accept2('z') {
		goto l208
	}
l74out:
	if r == endOfText {
		goto l650
	}
	return id, length
l79:
	id, length = 49, pos
	return id, length
l81:
	id, length = 49, pos
	return id, length
l83:
	id, length = 49, pos
	return id, length
l85:
	id, length = 49, pos
	return id, length
l87:
	if accept('=') {
		goto l90
	}
	return id, length
l90:
	id, length = 1, pos
	return id, length
l92:
	if accept('"') {
		goto l99
	}
	if accept('\\') {
		goto l101
	}
	if accept2('!') {
		goto l111
	}
	if r < '#' {
		goto l96out
	}
	if accept2('[') {
		goto l111
	}
	if r < ']' {
		goto l96out
	}
	if accept2('\U0010ffff') {
		goto l111
	}
l96out:
	return id, length
l99:
	id, length = 48, pos
	return id, length
l101:
	if accept2('\t') {
		goto l104
	}
	if r < '\v' {
		goto l101out
	}
	if accept2('\U0010ffff') {
		goto l104
	}
l101out:
	return id, length
l104:
	if accept('"') {
		goto l99
	}
	if accept('\\') {
		goto l101
	}
	if accept2('!') {
		goto l111
	}
	if r < '#' {
		goto l108out
	}
	if accept2('[') {
		goto l111
	}
	if r < ']' {
		goto l108out
	}
	if accept2('\U0010ffff') {
		goto l111
	}
l108out:
	return id, length
l111:
	if accept('"') {
		goto l99
	}
	if accept('\\') {
		goto l101
	}
	if accept2('!') {
		goto l111
	}
	if r < '#' {
		goto l115out
	}
	if accept2('[') {
		goto l111
	}
	if r < ']' {
		goto l115out
	}
	if accept2('\U0010ffff') {
		goto l111
	}
l115out:
	return id, length
l118:
	id, length = 27, pos
	return id, length
l120:
	id, length = 28, pos
	return id, length
l122:
	id, length = 29, pos
	return id, length
l124:
	id, length = 30, pos
	return id, length
l126:
	id, length = 31, pos
	return id, length
l128:
	id, length = 32, pos
	return id, length
l130:
	id, length = 33, pos
	return id, length
l132:
	id, length = 34, pos
	return id, length
l134:
	id, length = 35, pos
	if accept('*') {
		goto l140
	}
	if accept('/') {
		goto l164
	}
	return id, length
l140:
	if accept('*') {
		goto l145
	}
	if accept2(')') {
		goto l159
	}
	if r < '+' {
		goto l142out
	}
	if accept2('\U0010ffff') {
		goto l159
	}
l142out:
	return id, length
l145:
	if accept('*') {
		goto l145
	}
	if accept('/') {
		goto l152
	}
	if accept2(')') {
		goto l154
	}
	if r < '+' {
		goto l149out
	}
	if accept2('.') {
		goto l154
	}
	if r < '0' {
		goto l149out
	}
	if accept2('\U0010ffff') {
		goto l154
	}
l149out:
	return id, length
l152:
	id, length = 49, pos
	return id, length
l154:
	if accept('*') {
		goto l145
	}
	if accept2(')') {
		goto l159
	}
	if r < '+' {
		goto l156out
	}
	if accept2('\U0010ffff') {
		goto l159
	}
l156out:
	return id, length
l159:
	if accept('*') {
		goto l145
	}
	if accept2(')') {
		goto l159
	}
	if r < '+' {
		goto l161out
	}
	if accept2('\U0010ffff') {
		goto l159
	}
l161out:
	return id, length
l164:
	id, length = 49, pos
	if accept2('\t') {
		goto l168
	}
	if r < '\v' {
		goto l165out
	}
	if accept2('\U0010ffff') {
		goto l168
	}
l165out:
	return id, length
l168:
	id, length = 49, pos
	if accept2('\t') {
		goto l168
	}
	if r < '\v' {
		goto l169out
	}
	if accept2('\U0010ffff') {
		goto l168
	}
l169out:
	return id, length
l172:
	id, length = 47, pos
	if r < '0' {
		goto l173out
	}
	if accept2('9') {
		goto l172
	}
l173out:
	return id, length
l176:
	id, length = 36, pos
	return id, length
l178:
	id, length = 37, pos
	if accept('-') {
		goto l186
	}
	if accept('<') {
		goto l188
	}
	if accept('=') {
		goto l190
	}
	return id, length
l186:
	id, length = 2, pos
	return id, length
l188:
	id, length = 3, pos
	return id, length
l190:
	id, length = 4, pos
	return id, length
l192:
	id, length = 38, pos
	if accept('=') {
		goto l196
	}
	return id, length
l196:
	id, length = 5, pos
	return id, length
l198:
	id, length = 39, pos
	if accept('=') {
		goto l204
	}
	if accept('>') {
		goto l206
	}
	return id, length
l204:
	id, length = 6, pos
	return id, length
l206:
	id, length = 7, pos
	return id, length
l208:
	id, length = 46, pos
	if r < '0' {
		goto l209out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l209out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l209out
	}
	if accept2('z') {
		goto l212
	}
l209out:
	return id, length
l212:
	id, length = 46, pos
	if r < '0' {
		goto l213out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l213out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l213out
	}
	if accept2('z') {
		goto l212
	}
l213out:
	return id, length
l216:
	id, length = 40, pos
	return id, length
l218:
	id, length = 41, pos
	return id, length
l220:
	id, length = 42, pos
	return id, length
l222:
	id, length = 46, pos
	if accept('o') {
		goto l230
	}
	if accept('y') {
		goto l246
	}
	if r < '0' {
		goto l227out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l227out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l227out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l227out
	}
	if accept2('x') {
		goto l212
	}
	if accept('z') {
		goto l212
	}
l227out:
	return id, length
l230:
	id, length = 46, pos
	if accept('o') {
		goto l236
	}
	if r < '0' {
		goto l233out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l233out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l233out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l233out
	}
	if accept2('z') {
		goto l212
	}
l233out:
	return id, length
l236:
	id, length = 46, pos
	if accept('l') {
		goto l242
	}
	if r < '0' {
		goto l239out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l239out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l239out
	}
	if accept2('k') {
		goto l212
	}
	if r < 'm' {
		goto l239out
	}
	if accept2('z') {
		goto l212
	}
l239out:
	return id, length
l242:
	id, length = 8, pos
	if r < '0' {
		goto l243out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l243out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l243out
	}
	if accept2('z') {
		goto l212
	}
l243out:
	return id, length
l246:
	id, length = 46, pos
	if accept('t') {
		goto l252
	}
	if r < '0' {
		goto l249out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l249out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l249out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l249out
	}
	if accept2('z') {
		goto l212
	}
l249out:
	return id, length
l252:
	id, length = 46, pos
	if accept('e') {
		goto l258
	}
	if r < '0' {
		goto l255out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l255out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l255out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l255out
	}
	if accept2('z') {
		goto l212
	}
l255out:
	return id, length
l258:
	id, length = 9, pos
	if r < '0' {
		goto l259out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l259out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l259out
	}
	if accept2('z') {
		goto l212
	}
l259out:
	return id, length
l262:
	id, length = 46, pos
	if accept('a') {
		goto l272
	}
	if accept('h') {
		goto l288
	}
	if accept('o') {
		goto l304
	}
	if r < '0' {
		goto l269out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l269out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'b' {
		goto l269out
	}
	if accept2('g') {
		goto l212
	}
	if r < 'i' {
		goto l269out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l269out
	}
	if accept2('z') {
		goto l212
	}
l269out:
	return id, length
l272:
	id, length = 46, pos
	if accept('s') {
		goto l278
	}
	if r < '0' {
		goto l275out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l275out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l275out
	}
	if accept2('r') {
		goto l212
	}
	if r < 't' {
		goto l275out
	}
	if accept2('z') {
		goto l212
	}
l275out:
	return id, length
l278:
	id, length = 46, pos
	if accept('e') {
		goto l284
	}
	if r < '0' {
		goto l281out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l281out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l281out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l281out
	}
	if accept2('z') {
		goto l212
	}
l281out:
	return id, length
l284:
	id, length = 10, pos
	if r < '0' {
		goto l285out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l285out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l285out
	}
	if accept2('z') {
		goto l212
	}
l285out:
	return id, length
l288:
	id, length = 46, pos
	if accept('a') {
		goto l294
	}
	if r < '0' {
		goto l291out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l291out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'b' {
		goto l291out
	}
	if accept2('z') {
		goto l212
	}
l291out:
	return id, length
l294:
	id, length = 46, pos
	if accept('n') {
		goto l300
	}
	if r < '0' {
		goto l297out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l297out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l297out
	}
	if accept2('m') {
		goto l212
	}
	if r < 'o' {
		goto l297out
	}
	if accept2('z') {
		goto l212
	}
l297out:
	return id, length
l300:
	id, length = 11, pos
	if r < '0' {
		goto l301out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l301out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l301out
	}
	if accept2('z') {
		goto l212
	}
l301out:
	return id, length
l304:
	id, length = 46, pos
	if accept('n') {
		goto l310
	}
	if r < '0' {
		goto l307out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l307out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l307out
	}
	if accept2('m') {
		goto l212
	}
	if r < 'o' {
		goto l307out
	}
	if accept2('z') {
		goto l212
	}
l307out:
	return id, length
l310:
	id, length = 46, pos
	if accept('s') {
		goto l316
	}
	if r < '0' {
		goto l313out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l313out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l313out
	}
	if accept2('r') {
		goto l212
	}
	if r < 't' {
		goto l313out
	}
	if accept2('z') {
		goto l212
	}
l313out:
	return id, length
l316:
	id, length = 46, pos
	if accept('t') {
		goto l322
	}
	if r < '0' {
		goto l319out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l319out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l319out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l319out
	}
	if accept2('z') {
		goto l212
	}
l319out:
	return id, length
l322:
	id, length = 12, pos
	if r < '0' {
		goto l323out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l323out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l323out
	}
	if accept2('z') {
		goto l212
	}
l323out:
	return id, length
l326:
	id, length = 46, pos
	if accept('e') {
		goto l332
	}
	if r < '0' {
		goto l329out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l329out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l329out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l329out
	}
	if accept2('z') {
		goto l212
	}
l329out:
	return id, length
l332:
	id, length = 46, pos
	if accept('f') {
		goto l338
	}
	if r < '0' {
		goto l335out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l335out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l335out
	}
	if accept2('e') {
		goto l212
	}
	if r < 'g' {
		goto l335out
	}
	if accept2('z') {
		goto l212
	}
l335out:
	return id, length
l338:
	id, length = 46, pos
	if accept('a') {
		goto l344
	}
	if r < '0' {
		goto l341out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l341out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'b' {
		goto l341out
	}
	if accept2('z') {
		goto l212
	}
l341out:
	return id, length
l344:
	id, length = 46, pos
	if accept('u') {
		goto l350
	}
	if r < '0' {
		goto l347out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l347out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l347out
	}
	if accept2('t') {
		goto l212
	}
	if r < 'v' {
		goto l347out
	}
	if accept2('z') {
		goto l212
	}
l347out:
	return id, length
l350:
	id, length = 46, pos
	if accept('l') {
		goto l356
	}
	if r < '0' {
		goto l353out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l353out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l353out
	}
	if accept2('k') {
		goto l212
	}
	if r < 'm' {
		goto l353out
	}
	if accept2('z') {
		goto l212
	}
l353out:
	return id, length
l356:
	id, length = 46, pos
	if accept('t') {
		goto l362
	}
	if r < '0' {
		goto l359out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l359out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l359out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l359out
	}
	if accept2('z') {
		goto l212
	}
l359out:
	return id, length
l362:
	id, length = 13, pos
	if r < '0' {
		goto l363out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l363out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l363out
	}
	if accept2('z') {
		goto l212
	}
l363out:
	return id, length
l366:
	id, length = 46, pos
	if accept('l') {
		goto l372
	}
	if r < '0' {
		goto l369out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l369out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l369out
	}
	if accept2('k') {
		goto l212
	}
	if r < 'm' {
		goto l369out
	}
	if accept2('z') {
		goto l212
	}
l369out:
	return id, length
l372:
	id, length = 46, pos
	if accept('s') {
		goto l378
	}
	if r < '0' {
		goto l375out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l375out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l375out
	}
	if accept2('r') {
		goto l212
	}
	if r < 't' {
		goto l375out
	}
	if accept2('z') {
		goto l212
	}
l375out:
	return id, length
l378:
	id, length = 46, pos
	if accept('e') {
		goto l384
	}
	if r < '0' {
		goto l381out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l381out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l381out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l381out
	}
	if accept2('z') {
		goto l212
	}
l381out:
	return id, length
l384:
	id, length = 14, pos
	if r < '0' {
		goto l385out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l385out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l385out
	}
	if accept2('z') {
		goto l212
	}
l385out:
	return id, length
l388:
	id, length = 46, pos
	if accept('a') {
		goto l398
	}
	if accept('o') {
		goto l420
	}
	if accept('u') {
		goto l430
	}
	if r < '0' {
		goto l395out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l395out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'b' {
		goto l395out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l395out
	}
	if accept2('t') {
		goto l212
	}
	if r < 'v' {
		goto l395out
	}
	if accept2('z') {
		goto l212
	}
l395out:
	return id, length
l398:
	id, length = 46, pos
	if accept('l') {
		goto l404
	}
	if r < '0' {
		goto l401out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l401out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l401out
	}
	if accept2('k') {
		goto l212
	}
	if r < 'm' {
		goto l401out
	}
	if accept2('z') {
		goto l212
	}
l401out:
	return id, length
l404:
	id, length = 46, pos
	if accept('s') {
		goto l410
	}
	if r < '0' {
		goto l407out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l407out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l407out
	}
	if accept2('r') {
		goto l212
	}
	if r < 't' {
		goto l407out
	}
	if accept2('z') {
		goto l212
	}
l407out:
	return id, length
l410:
	id, length = 46, pos
	if accept('e') {
		goto l416
	}
	if r < '0' {
		goto l413out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l413out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l413out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l413out
	}
	if accept2('z') {
		goto l212
	}
l413out:
	return id, length
l416:
	id, length = 15, pos
	if r < '0' {
		goto l417out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l417out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l417out
	}
	if accept2('z') {
		goto l212
	}
l417out:
	return id, length
l420:
	id, length = 46, pos
	if accept('r') {
		goto l426
	}
	if r < '0' {
		goto l423out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l423out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l423out
	}
	if accept2('q') {
		goto l212
	}
	if r < 's' {
		goto l423out
	}
	if accept2('z') {
		goto l212
	}
l423out:
	return id, length
l426:
	id, length = 16, pos
	if r < '0' {
		goto l427out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l427out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l427out
	}
	if accept2('z') {
		goto l212
	}
l427out:
	return id, length
l430:
	id, length = 46, pos
	if accept('n') {
		goto l436
	}
	if r < '0' {
		goto l433out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l433out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l433out
	}
	if accept2('m') {
		goto l212
	}
	if r < 'o' {
		goto l433out
	}
	if accept2('z') {
		goto l212
	}
l433out:
	return id, length
l436:
	id, length = 46, pos
	if accept('c') {
		goto l442
	}
	if r < '0' {
		goto l439out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l439out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l439out
	}
	if accept2('b') {
		goto l212
	}
	if r < 'd' {
		goto l439out
	}
	if accept2('z') {
		goto l212
	}
l439out:
	return id, length
l442:
	id, length = 17, pos
	if r < '0' {
		goto l443out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l443out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l443out
	}
	if accept2('z') {
		goto l212
	}
l443out:
	return id, length
l446:
	id, length = 46, pos
	if accept('o') {
		goto l452
	}
	if r < '0' {
		goto l449out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l449out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l449out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l449out
	}
	if accept2('z') {
		goto l212
	}
l449out:
	return id, length
l452:
	id, length = 18, pos
	if r < '0' {
		goto l453out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l453out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l453out
	}
	if accept2('z') {
		goto l212
	}
l453out:
	return id, length
l456:
	id, length = 46, pos
	if accept('f') {
		goto l466
	}
	if accept('m') {
		goto l470
	}
	if accept('n') {
		goto l498
	}
	if r < '0' {
		goto l463out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l463out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l463out
	}
	if accept2('e') {
		goto l212
	}
	if r < 'g' {
		goto l463out
	}
	if accept2('l') {
		goto l212
	}
	if r < 'o' {
		goto l463out
	}
	if accept2('z') {
		goto l212
	}
l463out:
	return id, length
l466:
	id, length = 19, pos
	if r < '0' {
		goto l467out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l467out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l467out
	}
	if accept2('z') {
		goto l212
	}
l467out:
	return id, length
l470:
	id, length = 46, pos
	if accept('p') {
		goto l476
	}
	if r < '0' {
		goto l473out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l473out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l473out
	}
	if accept2('o') {
		goto l212
	}
	if r < 'q' {
		goto l473out
	}
	if accept2('z') {
		goto l212
	}
l473out:
	return id, length
l476:
	id, length = 46, pos
	if accept('o') {
		goto l482
	}
	if r < '0' {
		goto l479out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l479out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l479out
	}
	if accept2('n') {
		goto l212
	}
	if r < 'p' {
		goto l479out
	}
	if accept2('z') {
		goto l212
	}
l479out:
	return id, length
l482:
	id, length = 46, pos
	if accept('r') {
		goto l488
	}
	if r < '0' {
		goto l485out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l485out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l485out
	}
	if accept2('q') {
		goto l212
	}
	if r < 's' {
		goto l485out
	}
	if accept2('z') {
		goto l212
	}
l485out:
	return id, length
l488:
	id, length = 46, pos
	if accept('t') {
		goto l494
	}
	if r < '0' {
		goto l491out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l491out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l491out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l491out
	}
	if accept2('z') {
		goto l212
	}
l491out:
	return id, length
l494:
	id, length = 20, pos
	if r < '0' {
		goto l495out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l495out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l495out
	}
	if accept2('z') {
		goto l212
	}
l495out:
	return id, length
l498:
	id, length = 46, pos
	if accept('t') {
		goto l504
	}
	if r < '0' {
		goto l501out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l501out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l501out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l501out
	}
	if accept2('z') {
		goto l212
	}
l501out:
	return id, length
l504:
	id, length = 21, pos
	if r < '0' {
		goto l505out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l505out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l505out
	}
	if accept2('z') {
		goto l212
	}
l505out:
	return id, length
l508:
	id, length = 46, pos
	if accept('e') {
		goto l514
	}
	if r < '0' {
		goto l511out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l511out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l511out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l511out
	}
	if accept2('z') {
		goto l212
	}
l511out:
	return id, length
l514:
	id, length = 46, pos
	if accept('t') {
		goto l520
	}
	if r < '0' {
		goto l517out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l517out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l517out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l517out
	}
	if accept2('z') {
		goto l212
	}
l517out:
	return id, length
l520:
	id, length = 46, pos
	if accept('u') {
		goto l526
	}
	if r < '0' {
		goto l523out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l523out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l523out
	}
	if accept2('t') {
		goto l212
	}
	if r < 'v' {
		goto l523out
	}
	if accept2('z') {
		goto l212
	}
l523out:
	return id, length
l526:
	id, length = 46, pos
	if accept('r') {
		goto l532
	}
	if r < '0' {
		goto l529out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l529out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l529out
	}
	if accept2('q') {
		goto l212
	}
	if r < 's' {
		goto l529out
	}
	if accept2('z') {
		goto l212
	}
l529out:
	return id, length
l532:
	id, length = 46, pos
	if accept('n') {
		goto l538
	}
	if r < '0' {
		goto l535out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l535out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l535out
	}
	if accept2('m') {
		goto l212
	}
	if r < 'o' {
		goto l535out
	}
	if accept2('z') {
		goto l212
	}
l535out:
	return id, length
l538:
	id, length = 22, pos
	if r < '0' {
		goto l539out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l539out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l539out
	}
	if accept2('z') {
		goto l212
	}
l539out:
	return id, length
l542:
	id, length = 46, pos
	if accept('e') {
		goto l550
	}
	if accept('w') {
		goto l578
	}
	if r < '0' {
		goto l547out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l547out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l547out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l547out
	}
	if accept2('v') {
		goto l212
	}
	if r < 'x' {
		goto l547out
	}
	if accept2('z') {
		goto l212
	}
l547out:
	return id, length
l550:
	id, length = 46, pos
	if accept('l') {
		goto l556
	}
	if r < '0' {
		goto l553out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l553out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l553out
	}
	if accept2('k') {
		goto l212
	}
	if r < 'm' {
		goto l553out
	}
	if accept2('z') {
		goto l212
	}
l553out:
	return id, length
l556:
	id, length = 46, pos
	if accept('e') {
		goto l562
	}
	if r < '0' {
		goto l559out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l559out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l559out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l559out
	}
	if accept2('z') {
		goto l212
	}
l559out:
	return id, length
l562:
	id, length = 46, pos
	if accept('c') {
		goto l568
	}
	if r < '0' {
		goto l565out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l565out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l565out
	}
	if accept2('b') {
		goto l212
	}
	if r < 'd' {
		goto l565out
	}
	if accept2('z') {
		goto l212
	}
l565out:
	return id, length
l568:
	id, length = 46, pos
	if accept('t') {
		goto l574
	}
	if r < '0' {
		goto l571out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l571out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l571out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l571out
	}
	if accept2('z') {
		goto l212
	}
l571out:
	return id, length
l574:
	id, length = 23, pos
	if r < '0' {
		goto l575out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l575out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l575out
	}
	if accept2('z') {
		goto l212
	}
l575out:
	return id, length
l578:
	id, length = 46, pos
	if accept('i') {
		goto l584
	}
	if r < '0' {
		goto l581out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l581out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l581out
	}
	if accept2('h') {
		goto l212
	}
	if r < 'j' {
		goto l581out
	}
	if accept2('z') {
		goto l212
	}
l581out:
	return id, length
l584:
	id, length = 46, pos
	if accept('t') {
		goto l590
	}
	if r < '0' {
		goto l587out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l587out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l587out
	}
	if accept2('s') {
		goto l212
	}
	if r < 'u' {
		goto l587out
	}
	if accept2('z') {
		goto l212
	}
l587out:
	return id, length
l590:
	id, length = 46, pos
	if accept('c') {
		goto l596
	}
	if r < '0' {
		goto l593out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l593out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l593out
	}
	if accept2('b') {
		goto l212
	}
	if r < 'd' {
		goto l593out
	}
	if accept2('z') {
		goto l212
	}
l593out:
	return id, length
l596:
	id, length = 46, pos
	if accept('h') {
		goto l602
	}
	if r < '0' {
		goto l599out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l599out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l599out
	}
	if accept2('g') {
		goto l212
	}
	if r < 'i' {
		goto l599out
	}
	if accept2('z') {
		goto l212
	}
l599out:
	return id, length
l602:
	id, length = 24, pos
	if r < '0' {
		goto l603out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l603out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l603out
	}
	if accept2('z') {
		goto l212
	}
l603out:
	return id, length
l606:
	id, length = 46, pos
	if accept('r') {
		goto l612
	}
	if r < '0' {
		goto l609out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l609out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l609out
	}
	if accept2('q') {
		goto l212
	}
	if r < 's' {
		goto l609out
	}
	if accept2('z') {
		goto l212
	}
l609out:
	return id, length
l612:
	id, length = 46, pos
	if accept('u') {
		goto l618
	}
	if r < '0' {
		goto l615out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l615out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l615out
	}
	if accept2('t') {
		goto l212
	}
	if r < 'v' {
		goto l615out
	}
	if accept2('z') {
		goto l212
	}
l615out:
	return id, length
l618:
	id, length = 46, pos
	if accept('e') {
		goto l624
	}
	if r < '0' {
		goto l621out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l621out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l621out
	}
	if accept2('d') {
		goto l212
	}
	if r < 'f' {
		goto l621out
	}
	if accept2('z') {
		goto l212
	}
l621out:
	return id, length
l624:
	id, length = 25, pos
	if r < '0' {
		goto l625out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l625out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l625out
	}
	if accept2('z') {
		goto l212
	}
l625out:
	return id, length
l628:
	id, length = 46, pos
	if accept('a') {
		goto l634
	}
	if r < '0' {
		goto l631out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l631out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'b' {
		goto l631out
	}
	if accept2('z') {
		goto l212
	}
l631out:
	return id, length
l634:
	id, length = 46, pos
	if accept('r') {
		goto l640
	}
	if r < '0' {
		goto l637out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l637out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l637out
	}
	if accept2('q') {
		goto l212
	}
	if r < 's' {
		goto l637out
	}
	if accept2('z') {
		goto l212
	}
l637out:
	return id, length
l640:
	id, length = 26, pos
	if r < '0' {
		goto l641out
	}
	if accept2('9') {
		goto l212
	}
	if r < 'A' {
		goto l641out
	}
	if accept2('Z') {
		goto l212
	}
	if accept('_') {
		goto l212
	}
	if r < 'a' {
		goto l641out
	}
	if accept2('z') {
		goto l212
	}
l641out:
	return id, length
l644:
	id, length = 43, pos
	return id, length
l646:
	id, length = 44, pos
	return id, length
l648:
	id, length = 45, pos
	return id, length
l650:
	id, length = 0, pos
	return id, length
}

// Scan is used internally from Parse.
func (p *Parser) Scan() (r scanner.Token) {
	return p.sc.Scan()
}

// init initalizes 'p' with content in 'src', assuming it comes from 'name'.
// 'src' becomes "owned" by 'p'. init invalidates any pre-existing ASTs produced by 'p'. Mutating
// 'src' invalidates the current AST returned from any parsing function called after init.
func (p *Parser) init(name string, src []byte) (err error) {
	p.eof = false
	p.errBudget = 10
	p.off = 0
	p.src = src
	p.tok = scanner.Token{}
	p.tokIndex = 0
	p.sc = scanner.NewRecScanner(name, p.src, p.scan, int(white_space))
	return nil
}

// AddOp grammar:
//
//	AddOp = "+" | "-" | "|" | "^" .
//
//	State 0
//		on  '+', '-', '^', '|'
//			shift and goto state 1
//	State 1
//		Accept
//
// AddOp is used internally from Parse.
func (p *Parser) AddOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(AddOp), 0)
	// state0:
	accept, errorSet = false, 37
	switch Symbol(p.tok.Ch) {
	case TOK_002b, TOK_002d, TOK_005e, TOK_007c:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ArgumentList grammar:
//
//	ArgumentList = Expression { "," Expression } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 1
//	State 1
//		Accept
//		on  ','
//			shift and goto state 0
//
// ArgumentList is used internally from Parse.
func (p *Parser) ArgumentList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ArgumentList), 0)
state0:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 38
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Block grammar:
//
//	Block = "{" { Statement } "}" .
//
//	State 0
//		on  '{'
//			shift and goto state 1
//	State 1
//		on  '}'
//			shift and goto state 2
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 1
//	State 2
//		Accept
//
// Block is used internally from Parse.
func (p *Parser) Block() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Block), 0)
	// state0:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 10
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CallSuffix grammar:
//
//	CallSuffix = "(" [ ArgumentList ] ")" .
//
//	State 0
//		on  '('
//			shift and goto state 1
//	State 1
//		on  ')'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call ArgumentList and goto state 3
//	State 2
//		Accept
//	State 3
//		on  ')'
//			shift and goto state 2
//
// CallSuffix is used internally from Parse.
func (p *Parser) CallSuffix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CallSuffix), 0)
	// state0:
	accept, errorSet = false, 32
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 13
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.ArgumentList())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 34
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CaseClause grammar:
//
//	CaseClause = CaseHead ":" { Statement } .
//
//	State 0
//		on  "case", "default"
//			call CaseHead and goto state 1
//	State 1
//		on  ':'
//			shift and goto state 2
//	State 2
//		Accept
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 2
//
// CaseClause is used internally from Parse.
func (p *Parser) CaseClause() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CaseClause), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case, TOK_default:
		r = p.add(r, p.CaseHead())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 40
	switch Symbol(p.tok.Ch) {
	case TOK_003a:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 11
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CaseHead grammar:
//
//	CaseHead   = "case" ExpressionList | "default" .
//
//	State 0
//		on  "case"
//			shift and goto state 1
//		on  "default"
//			shift and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call ExpressionList and goto state 2
//	State 2
//		Accept
//
// CaseHead is used internally from Parse.
func (p *Parser) CaseHead() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CaseHead), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case:
		r = append(r, p.shift())
		goto state1
	case TOK_default:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 16
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.ExpressionList())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CommClause grammar:
//
//	CommClause = CommHead ":" { Statement } .
//
//	State 0
//		on  "case", "default"
//			call CommHead and goto state 1
//	State 1
//		on  ':'
//			shift and goto state 2
//	State 2
//		Accept
//		on  "<-", "const", "for", "go", "if", "return", "select", "switch", "var", identifier
//			call Statement and goto state 2
//
// CommClause is used internally from Parse.
func (p *Parser) CommClause() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommClause), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case, TOK_default:
		r = p.add(r, p.CommHead())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 40
	switch Symbol(p.tok.Ch) {
	case TOK_003a:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 11
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_const, TOK_for, TOK_go, TOK_if, TOK_return, TOK_select, TOK_switch, TOK_var, identifier:
		r = p.add(r, p.Statement())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// CommHead grammar:
//
//	CommHead   = "case" CommOp | "default" .
//
//	State 0
//		on  "case"
//			shift and goto state 1
//		on  "default"
//			shift and goto state 2
//	State 1
//		on  "<-", identifier
//			call CommOp and goto state 2
//	State 2
//		Accept
//
// CommHead is used internally from Parse.
func (p *Parser) CommHead() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommHead), 0)
	// state0:
	accept, errorSet = false, 3
	switch Symbol(p.tok.Ch) {
	case TOK_case:
		r = append(r, p.shift())
		goto state1
	case TOK_default:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 25
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, identifier:
		r = p.add(r, p.CommOp())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// CommOp grammar:
//
//	CommOp = "<-" Expression
//	       | identifier PostfixComm .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  identifier
//			shift and goto state 3
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", '.', '=', '['
//			call PostfixComm and goto state 2
//
// CommOp is used internally from Parse.
func (p *Parser) CommOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(CommOp), 0)
	// state0:
	accept, errorSet = false, 25
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case identifier:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 23
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_002e, TOK_003d, TOK_005b:
		r = p.add(r, p.PostfixComm())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// ConstDecl grammar:
//
//	ConstDecl = "const" identifier "=" Expression .
//
//	State 0
//		on  "const"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  '='
//			shift and goto state 3
//	State 3
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 4
//	State 4
//		Accept
//
// ConstDecl is used internally from Parse.
func (p *Parser) ConstDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ConstDecl), 0)
	// state0:
	accept, errorSet = false, 7
	switch Symbol(p.tok.Ch) {
	case TOK_const:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 41
	switch Symbol(p.tok.Ch) {
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Expression grammar:
//
//	Expression = SimpleExpr [ RelOp SimpleExpr ] .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call SimpleExpr and goto state 1
//	State 1
//		Accept
//		on  "!=", "<=", "==", ">=", '<', '>'
//			call RelOp and goto state 2
//	State 2
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call SimpleExpr and goto state 3
//	State 3
//		Accept
//
// Expression is used internally from Parse.
func (p *Parser) Expression() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Expression), 0)
	// state0:
	accept, errorSet = false, 18
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.SimpleExpr())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	switch Symbol(p.tok.Ch) {
	case TOK_0021003d, TOK_003c003d, TOK_003d003d, TOK_003e003d, TOK_003c, TOK_003e:
		r = p.add(r, p.RelOp())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 18
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.SimpleExpr())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ExpressionList grammar:
//
//	ExpressionList = Expression { "," Expression } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 1
//	State 1
//		Accept
//		on  ','
//			shift and goto state 0
//
// ExpressionList is used internally from Parse.
func (p *Parser) ExpressionList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ExpressionList), 0)
state0:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 38
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Factor grammar:
//
//	Factor = identifier [ FactorSuffix ]
//	       | number
//	       | string_literal
//	       | "true"
//	       | "false"
//	       | "<-" Expression
//	       | "(" Expression ")" .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  "false", "true", number, string_literal
//			shift and goto state 2
//		on  '('
//			shift and goto state 3
//		on  identifier
//			shift and goto state 5
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 4
//	State 4
//		on  ')'
//			shift and goto state 2
//	State 5
//		Accept
//		on  '(', '.', '['
//			call FactorSuffix and goto state 2
//
// Factor is used internally from Parse.
func (p *Parser) Factor() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Factor), 0)
	// state0:
	accept, errorSet = false, 20
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_false, TOK_true, number, string_literal:
		r = append(r, p.shift())
		goto state2
	case TOK_0028:
		r = append(r, p.shift())
		goto state3
	case identifier:
		r = append(r, p.shift())
		goto state5
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 34
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = true, 30
	switch Symbol(p.tok.Ch) {
	case TOK_0028, TOK_002e, TOK_005b:
		r = p.add(r, p.FactorSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// FactorSuffix grammar:
//
//	FactorSuffix = { Selector | Index } [ CallSuffix ] .
//
//	State 0
//		Accept
//		on  '.'
//			call Selector and goto state 1
//		on  '['
//			call Index and goto state 1
//		on  '('
//			call CallSuffix and goto state 2
//	State 1
//		Accept
//		on  '.'
//			call Selector and goto state 1
//		on  '['
//			call Index and goto state 1
//		on  '('
//			call CallSuffix and goto state 2
//	State 2
//		Accept
//
// FactorSuffix is used internally from Parse.
func (p *Parser) FactorSuffix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(FactorSuffix), 0)
	// state0:
	accept, errorSet = true, 31
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state1
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state1
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 31
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state1
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state1
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// FuncDecl grammar:
//
//	FuncDecl = "func" identifier "(" [ ParameterList ] ")" [ Type ] Block .
//
//	State 0
//		on  "func"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  '('
//			shift and goto state 3
//	State 3
//		on  ')'
//			shift and goto state 4
//		on  identifier
//			call ParameterList and goto state 7
//	State 4
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 5
//		on  '{'
//			call Block and goto state 6
//	State 5
//		on  '{'
//			call Block and goto state 6
//	State 6
//		Accept
//	State 7
//		on  ')'
//			shift and goto state 4
//
// FuncDecl is used internally from Parse.
func (p *Parser) FuncDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(FuncDecl), 0)
	// state0:
	accept, errorSet = false, 9
	switch Symbol(p.tok.Ch) {
	case TOK_func:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 32
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 33
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state4
	case identifier:
		r = p.add(r, p.ParameterList())
		goto state7
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 47
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state5
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state6:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state7:
	accept, errorSet = false, 34
	switch Symbol(p.tok.Ch) {
	case TOK_0029:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
}

// ImportDecl grammar:
//
//	ImportDecl = "import" string_literal .
//
//	State 0
//		on  "import"
//			shift and goto state 1
//	State 1
//		on  string_literal
//			shift and goto state 2
//	State 2
//		Accept
//
// ImportDecl is used internally from Parse.
func (p *Parser) ImportDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ImportDecl), 0)
	// state0:
	accept, errorSet = false, 26
	switch Symbol(p.tok.Ch) {
	case TOK_import:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 46
	switch Symbol(p.tok.Ch) {
	case string_literal:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Index grammar:
//
//	Index = "[" Expression "]" .
//
//	State 0
//		on  '['
//			shift and goto state 1
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		on  ']'
//			shift and goto state 3
//	State 3
//		Accept
//
// Index is used internally from Parse.
func (p *Parser) Index() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Index), 0)
	// state0:
	accept, errorSet = false, 42
	switch Symbol(p.tok.Ch) {
	case TOK_005b:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 43
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// MulOp grammar:
//
//	MulOp = "*" | "/" | "<<" | ">>" | "&" .
//
//	State 0
//		on  "<<", ">>", '&', '*', '/'
//			shift and goto state 1
//	State 1
//		Accept
//
// MulOp is used internally from Parse.
func (p *Parser) MulOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(MulOp), 0)
	// state0:
	accept, errorSet = false, 36
	switch Symbol(p.tok.Ch) {
	case TOK_003c003c, TOK_003e003e, TOK_0026, TOK_002a, TOK_002f:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// ParameterList grammar:
//
//	ParameterList = identifier Type { "," identifier Type } .
//
//	State 0
//		on  identifier
//			shift and goto state 1
//	State 1
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 2
//	State 2
//		Accept
//		on  ','
//			shift and goto state 0
//
// ParameterList is used internally from Parse.
func (p *Parser) ParameterList() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(ParameterList), 0)
state0:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 48
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 38
	switch Symbol(p.tok.Ch) {
	case TOK_002c:
		r = append(r, p.shift())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// Postfix grammar:
//
//	Postfix = { Selector | Index } ( "=" Expression | "<-" Expression | CallSuffix ) .
//
//	State 0
//		on  "<-", '='
//			shift and goto state 1
//		on  '.'
//			call Selector and goto state 3
//		on  '['
//			call Index and goto state 3
//		on  '('
//			call CallSuffix and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-", '='
//			shift and goto state 1
//		on  '.'
//			call Selector and goto state 3
//		on  '['
//			call Index and goto state 3
//		on  '('
//			call CallSuffix and goto state 2
//
// Postfix is used internally from Parse.
func (p *Parser) Postfix() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Postfix), 0)
	// state0:
	accept, errorSet = false, 22
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_003d:
		r = append(r, p.shift())
		goto state1
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state3
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state3
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 22
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_003d:
		r = append(r, p.shift())
		goto state1
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state3
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state3
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// PostfixComm grammar:
//
//	PostfixComm = { Selector | Index } ( "=" "<-" Expression | "<-" Expression ) .
//
//	State 0
//		on  "<-"
//			shift and goto state 1
//		on  '='
//			shift and goto state 3
//		on  '.'
//			call Selector and goto state 4
//		on  '['
//			call Index and goto state 4
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  "<-"
//			shift and goto state 1
//	State 4
//		on  "<-"
//			shift and goto state 1
//		on  '='
//			shift and goto state 3
//		on  '.'
//			call Selector and goto state 4
//		on  '['
//			call Index and goto state 4
//
// PostfixComm is used internally from Parse.
func (p *Parser) PostfixComm() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(PostfixComm), 0)
	// state0:
	accept, errorSet = false, 24
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state4
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 35
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 24
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_003d:
		r = append(r, p.shift())
		goto state3
	case TOK_002e:
		r = p.add(r, p.Selector())
		goto state4
	case TOK_005b:
		r = p.add(r, p.Index())
		goto state4
	}
	return p.stop(r, accept, errorSet)
}

// RelOp grammar:
//
//	RelOp = "==" | "!=" | "<" | "<=" | ">" | ">=" .
//
//	State 0
//		on  "!=", "<=", "==", ">=", '<', '>'
//			shift and goto state 1
//	State 1
//		Accept
//
// RelOp is used internally from Parse.
func (p *Parser) RelOp() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(RelOp), 0)
	// state0:
	accept, errorSet = false, 0
	switch Symbol(p.tok.Ch) {
	case TOK_0021003d, TOK_003c003d, TOK_003d003d, TOK_003e003d, TOK_003c, TOK_003e:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// SelectStmt grammar:
//
//	SelectStmt = "select" "{" { CommClause } "}" .
//
//	State 0
//		on  "select"
//			shift and goto state 1
//	State 1
//		on  '{'
//			shift and goto state 2
//	State 2
//		on  '}'
//			shift and goto state 3
//		on  "case", "default"
//			call CommClause and goto state 2
//	State 3
//		Accept
//
// SelectStmt is used internally from Parse.
func (p *Parser) SelectStmt() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SelectStmt), 0)
	// state0:
	accept, errorSet = false, 27
	switch Symbol(p.tok.Ch) {
	case TOK_select:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 2
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state3
	case TOK_case, TOK_default:
		r = p.add(r, p.CommClause())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Selector grammar:
//
//	Selector = "." identifier .
//
//	State 0
//		on  '.'
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		Accept
//
// Selector is used internally from Parse.
func (p *Parser) Selector() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Selector), 0)
	// state0:
	accept, errorSet = false, 39
	switch Symbol(p.tok.Ch) {
	case TOK_002e:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// SimpleExpr grammar:
//
//	SimpleExpr = Term { AddOp Term } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Term and goto state 1
//	State 1
//		Accept
//		on  '+', '-', '^', '|'
//			call AddOp and goto state 0
//
// SimpleExpr is used internally from Parse.
func (p *Parser) SimpleExpr() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SimpleExpr), 0)
state0:
	accept, errorSet = false, 19
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Term())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 37
	switch Symbol(p.tok.Ch) {
	case TOK_002b, TOK_002d, TOK_005e, TOK_007c:
		r = p.add(r, p.AddOp())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// SourceFile grammar:
//
//	SourceFile = { ImportDecl } { TopLevelDecl } .
//
//	State 0
//		Accept
//		on  "import"
//			call ImportDecl and goto state 1
//		on  "const", "func", "var"
//			call TopLevelDecl and goto state 2
//	State 1
//		Accept
//		on  "import"
//			call ImportDecl and goto state 1
//		on  "const", "func", "var"
//			call TopLevelDecl and goto state 2
//	State 2
//		Accept
//		on  "const", "func", "var"
//			call TopLevelDecl and goto state 2
//
// SourceFile is used internally from Parse.
func (p *Parser) SourceFile() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SourceFile), 0)
	// state0:
	accept, errorSet = true, 4
	switch Symbol(p.tok.Ch) {
	case TOK_import:
		r = p.add(r, p.ImportDecl())
		goto state1
	case TOK_const, TOK_func, TOK_var:
		r = p.add(r, p.TopLevelDecl())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 4
	switch Symbol(p.tok.Ch) {
	case TOK_import:
		r = p.add(r, p.ImportDecl())
		goto state1
	case TOK_const, TOK_func, TOK_var:
		r = p.add(r, p.TopLevelDecl())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 5
	switch Symbol(p.tok.Ch) {
	case TOK_const, TOK_func, TOK_var:
		r = p.add(r, p.TopLevelDecl())
		goto state2
	}
	if accept = accept && p.eof; accept {
		r = append(r, p.shift())
	}
	r[1] = int32(len(r) - 2)
	if !accept {
		p.err(p.tok.Position(), "%q [%s]: expected %v", p.tok.Src(), Symbol(p.tok.Ch), errorSets[errorSet])
	}
	return r
}

// Statement grammar:
//
//	Statement = VarDecl
//	          | ConstDecl
//	          | "if" Expression Block [ "else" Block ]
//	          | "for" [ Expression ] Block
//	          | "return" [ Expression ]
//	          | "go" identifier CallSuffix
//	          | SwitchStmt
//	          | SelectStmt
//	          | "<-" Expression
//	          | identifier Postfix .
//
//	State 0
//		on  "return"
//			shift and goto state 10
//		on  identifier
//			shift and goto state 11
//		on  "<-"
//			shift and goto state 1
//		on  "for"
//			shift and goto state 3
//		on  "go"
//			shift and goto state 5
//		on  "if"
//			shift and goto state 7
//		on  "const"
//			call ConstDecl and goto state 2
//		on  "var"
//			call VarDecl and goto state 2
//		on  "switch"
//			call SwitchStmt and goto state 2
//		on  "select"
//			call SelectStmt and goto state 2
//	State 1
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 2
//		Accept
//	State 3
//		on  '{'
//			call Block and goto state 2
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 4
//	State 4
//		on  '{'
//			call Block and goto state 2
//	State 5
//		on  identifier
//			shift and goto state 6
//	State 6
//		on  '('
//			call CallSuffix and goto state 2
//	State 7
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 8
//	State 8
//		on  '{'
//			call Block and goto state 9
//	State 9
//		Accept
//		on  "else"
//			shift and goto state 4
//	State 10
//		Accept
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 2
//	State 11
//		on  "<-", '(', '.', '=', '['
//			call Postfix and goto state 2
//
// Statement is used internally from Parse.
func (p *Parser) Statement() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Statement), 0)
	// state0:
	accept, errorSet = false, 12
	switch Symbol(p.tok.Ch) {
	case TOK_return:
		r = append(r, p.shift())
		goto state10
	case identifier:
		r = append(r, p.shift())
		goto state11
	case TOK_003c002d:
		r = append(r, p.shift())
		goto state1
	case TOK_for:
		r = append(r, p.shift())
		goto state3
	case TOK_go:
		r = append(r, p.shift())
		goto state5
	case TOK_if:
		r = append(r, p.shift())
		goto state7
	case TOK_const:
		r = p.add(r, p.ConstDecl())
		goto state2
	case TOK_var:
		r = p.add(r, p.VarDecl())
		goto state2
	case TOK_switch:
		r = p.add(r, p.SwitchStmt())
		goto state2
	case TOK_select:
		r = p.add(r, p.SelectStmt())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 15
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state6
	}
	return p.stop(r, accept, errorSet)
state6:
	accept, errorSet = false, 32
	switch Symbol(p.tok.Ch) {
	case TOK_0028:
		r = p.add(r, p.CallSuffix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state7:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state8
	}
	return p.stop(r, accept, errorSet)
state8:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = p.add(r, p.Block())
		goto state9
	}
	return p.stop(r, accept, errorSet)
state9:
	accept, errorSet = true, 8
	switch Symbol(p.tok.Ch) {
	case TOK_else:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state10:
	accept, errorSet = true, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state11:
	accept, errorSet = false, 21
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_0028, TOK_002e, TOK_003d, TOK_005b:
		r = p.add(r, p.Postfix())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// SwitchStmt grammar:
//
//	SwitchStmt = "switch" [ Expression ] "{" { CaseClause } "}" .
//
//	State 0
//		on  "switch"
//			shift and goto state 1
//	State 1
//		on  '{'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 4
//	State 2
//		on  '}'
//			shift and goto state 3
//		on  "case", "default"
//			call CaseClause and goto state 2
//	State 3
//		Accept
//	State 4
//		on  '{'
//			shift and goto state 2
//
// SwitchStmt is used internally from Parse.
func (p *Parser) SwitchStmt() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(SwitchStmt), 0)
	// state0:
	accept, errorSet = false, 28
	switch Symbol(p.tok.Ch) {
	case TOK_switch:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 15
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 1
	switch Symbol(p.tok.Ch) {
	case TOK_007d:
		r = append(r, p.shift())
		goto state3
	case TOK_case, TOK_default:
		r = p.add(r, p.CaseClause())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 44
	switch Symbol(p.tok.Ch) {
	case TOK_007b:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// Term grammar:
//
//	Term       = Factor { MulOp Factor } .
//
//	State 0
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Factor and goto state 1
//	State 1
//		Accept
//		on  "<<", ">>", '&', '*', '/'
//			call MulOp and goto state 0
//
// Term is used internally from Parse.
func (p *Parser) Term() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Term), 0)
state0:
	accept, errorSet = false, 20
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Factor())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 36
	switch Symbol(p.tok.Ch) {
	case TOK_003c003c, TOK_003e003e, TOK_0026, TOK_002a, TOK_002f:
		r = p.add(r, p.MulOp())
		goto state0
	}
	return p.stop(r, accept, errorSet)
}

// TopLevelDecl grammar:
//
//	TopLevelDecl = FuncDecl | VarDecl | ConstDecl .
//
//	State 0
//		on  "const"
//			call ConstDecl and goto state 1
//		on  "var"
//			call VarDecl and goto state 1
//		on  "func"
//			call FuncDecl and goto state 1
//	State 1
//		Accept
//
// TopLevelDecl is used internally from Parse.
func (p *Parser) TopLevelDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(TopLevelDecl), 0)
	// state0:
	accept, errorSet = false, 6
	switch Symbol(p.tok.Ch) {
	case TOK_const:
		r = p.add(r, p.ConstDecl())
		goto state1
	case TOK_var:
		r = p.add(r, p.VarDecl())
		goto state1
	case TOK_func:
		r = p.add(r, p.FuncDecl())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

// Type grammar:
//
//	Type = "int" | "bool" | "byte" | "chan" Type | "[" [ Expression ] "]" Type .
//
//	State 0
//		on  "bool", "byte", "int"
//			shift and goto state 1
//		on  "chan"
//			shift and goto state 2
//		on  '['
//			shift and goto state 3
//	State 1
//		Accept
//	State 2
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 1
//	State 3
//		on  ']'
//			shift and goto state 2
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 4
//	State 4
//		on  ']'
//			shift and goto state 2
//
// Type is used internally from Parse.
func (p *Parser) Type() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(Type), 0)
	// state0:
	accept, errorSet = false, 48
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_int:
		r = append(r, p.shift())
		goto state1
	case TOK_chan:
		r = append(r, p.shift())
		goto state2
	case TOK_005b:
		r = append(r, p.shift())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 48
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = false, 14
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state2
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 43
	switch Symbol(p.tok.Ch) {
	case TOK_005d:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
}

// VarDecl grammar:
//
//	VarDecl = "var" identifier Type [ "=" Expression ] .
//
//	State 0
//		on  "var"
//			shift and goto state 1
//	State 1
//		on  identifier
//			shift and goto state 2
//	State 2
//		on  "bool", "byte", "chan", "int", '['
//			call Type and goto state 3
//	State 3
//		Accept
//		on  '='
//			shift and goto state 4
//	State 4
//		on  "<-", "false", "true", '(', identifier, number, string_literal
//			call Expression and goto state 5
//	State 5
//		Accept
//
// VarDecl is used internally from Parse.
func (p *Parser) VarDecl() (r []int32) {
	accept, errorSet := false, 0
	r = append(p.get(), -int32(VarDecl), 0)
	// state0:
	accept, errorSet = false, 29
	switch Symbol(p.tok.Ch) {
	case TOK_var:
		r = append(r, p.shift())
		goto state1
	}
	return p.stop(r, accept, errorSet)
state1:
	accept, errorSet = false, 45
	switch Symbol(p.tok.Ch) {
	case identifier:
		r = append(r, p.shift())
		goto state2
	}
	return p.stop(r, accept, errorSet)
state2:
	accept, errorSet = false, 48
	switch Symbol(p.tok.Ch) {
	case TOK_bool, TOK_byte, TOK_chan, TOK_int, TOK_005b:
		r = p.add(r, p.Type())
		goto state3
	}
	return p.stop(r, accept, errorSet)
state3:
	accept, errorSet = true, 41
	switch Symbol(p.tok.Ch) {
	case TOK_003d:
		r = append(r, p.shift())
		goto state4
	}
	return p.stop(r, accept, errorSet)
state4:
	accept, errorSet = false, 17
	switch Symbol(p.tok.Ch) {
	case TOK_003c002d, TOK_false, TOK_true, TOK_0028, identifier, number, string_literal:
		r = p.add(r, p.Expression())
		goto state5
	}
	return p.stop(r, accept, errorSet)
state5:
	accept, errorSet = true, 0
	return p.stop(r, accept, errorSet)
}

func (p *Parser) shift() (r int32) {
	r = p.tokIndex
	if !p.eof {
		p.tok = p.Scan()
		p.tokIndex++
		p.eof = p.tok.Ch == rune(TOK_EOF)
	}
	return r
}

func (p *Parser) get() (r []int32) {
	if n := len(p.cache); n != 0 {
		r = p.cache[n-1][:0]
		p.cache = p.cache[:n-1]
	}
	return r
}

func (p *Parser) add(r, s []int32) (t []int32) {
	p.cache = append(p.cache, s)
	return append(r, s...)
}

func (p *Parser) stop(r []int32, accept bool, errorSet int) []int32 {
	r[1] = int32(len(r) - 2)
	if !accept {
		p.err(p.tok.Position(), "%q [%s]: expected %v", p.tok.Src(), Symbol(p.tok.Ch), errorSets[errorSet])
	}
	return r
}

// EOF reports whether the parser lookahead token is EOF.
func (p *Parser) EOF() bool {
	return p.eof
}

// Token returns the n-th token in 'p'. Token panics if 'n' is out of range.
func (p *Parser) Token(n int32) (r scanner.Token) {
	return p.sc.Token(int(n))
}

// Parse parses 'src'. 'src' becomes "owned" by the parser and must not be
// mutated afterwards.
func (p *Parser) Parse(name string, src []byte) (ast []int32, err error) {
	if err = p.init(name, src); err != nil {
		return nil, err
	}

	defer func() {
		switch e := recover(); x := e.(type) {
		case nil:
			// ok
		case scanner.ErrList:
			err = x
		case error:
			err = errors.Join(err, x)
		default:
			err = errors.Join(err, fmt.Errorf("%v", x))
		}
	}()

	p.tok = p.Scan()
	ast = p.SourceFile()
	return ast, p.sc.Err()
}

func (p *Parser) err0(pos token.Position, s string, args ...any) {
	p.sc.AddErr(pos, s, args...)
	if p.errBudget--; p.errBudget == 0 {
		p.sc.AddErr(pos, "too many errors")
	}
}

func (p *Parser) err(pos token.Position, s string, args ...any) {
	p.err0(pos, s, args...)
	p.shift()
	if p.eof {
		panic(p.sc.Err())
	}
}
