// Copyright 2026 The OctoGo Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package octogo

import (
	"bytes"
	"testing"
	"testing/fstest"
)

// TestEmitCMain pins the walking-skeleton emitter: an empty `func main()` must
// produce the equivalent C translation unit.
func TestEmitCMain(t *testing.T) {
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte("func main() {\n}\n")}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	const want = "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"int main(void) {\n\treturn 0;\n}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCBlink pins the emitter's first useful subset: imports -> #include,
// `for {}` -> `for (;;)`, and p2 calls -> P2 intrinsics.
func TestEmitCBlink(t *testing.T) {
	src := `import "p2"

func main() {
	for {
		p2.PinHigh(56)
		p2.WaitMs(200)
		p2.PinLow(56)
		p2.WaitMs(200)
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	const want = `// Code generated by ogo. DO NOT EDIT.

#include <propeller2.h>

int main(void) {
	for (;;) {
		_pinh(56);
		_waitms(200);
		_pinl(56);
		_waitms(200);
	}
	return 0;
}
`
	if got := buf.String(); got != want {
		t.Errorf("EmitC blink:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCCounter pins the computational subset: local var, assignment,
// arithmetic (parenthesized), and println -> printf over serial.
func TestEmitCCounter(t *testing.T) {
	src := `import "p2"

func main() {
	var i int
	for {
		println(i)
		i = i + 1
		p2.WaitMs(500)
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <propeller2.h>\n" +
		"#include <stdio.h>\n\n" +
		"int main(void) {\n" +
		"\tint i = 0;\n" +
		"\tfor (;;) {\n" +
		"\t\tprintf(\"%d\\n\", i);\n" +
		"\t\ti = (i + 1);\n" +
		"\t\t_waitms(500);\n" +
		"\t}\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC counter:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCControl pins control flow: conditional for -> while, if, and
// single-parenthesized conditions.
func TestEmitCControl(t *testing.T) {
	src := `func main() {
	var i int
	for i < 20 {
		if i < 10 {
			println(i)
		}
		i = i + 1
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <stdio.h>\n\n" +
		"int main(void) {\n" +
		"\tint i = 0;\n" +
		"\twhile (i < 20) {\n" +
		"\t\tif (i < 10) {\n" +
		"\t\t\tprintf(\"%d\\n\", i);\n" +
		"\t\t}\n" +
		"\t\ti = (i + 1);\n" +
		"\t}\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC control:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCFunc pins user-defined functions: a void function with named
// parameters, a forward prototype, and a call to it from main.
func TestEmitCFunc(t *testing.T) {
	src := `import "p2"

func flash(pin, ms int) {
	p2.PinHigh(pin)
	p2.WaitMs(ms)
	p2.PinLow(pin)
	p2.WaitMs(ms)
}

func main() {
	for {
		flash(56, 200)
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <propeller2.h>\n\n" +
		"void flash(int pin, int ms);\n\n" +
		"void flash(int pin, int ms) {\n" +
		"\t_pinh(pin);\n" +
		"\t_waitms(ms);\n" +
		"\t_pinl(pin);\n" +
		"\t_waitms(ms);\n" +
		"}\n\n" +
		"int main(void) {\n" +
		"\tfor (;;) {\n" +
		"\t\tflash(56, 200);\n" +
		"\t}\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC func:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCFuncForward pins order independence (main calls a function defined
// after it, resolved via the forward prototype) and a bare `return` in a void
// function.
func TestEmitCFuncForward(t *testing.T) {
	src := `func main() {
	greet()
}

func greet() {
	println(1)
	return
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <stdio.h>\n\n" +
		"void greet(void);\n\n" +
		"int main(void) {\n" +
		"\tgreet();\n" +
		"\treturn 0;\n" +
		"}\n\n" +
		"void greet(void) {\n" +
		"\tprintf(\"%d\\n\", 1);\n" +
		"\treturn;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC func forward:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCFuncResult pins a value-returning function: a single result type in
// the signature, `return expr`, and the call used as a value (a println arg).
func TestEmitCFuncResult(t *testing.T) {
	src := `func add(a, b int) int {
	return a + b
}

func main() {
	println(add(2, 3))
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <stdio.h>\n\n" +
		"int add(int a, int b);\n\n" +
		"int add(int a, int b) {\n" +
		"\treturn (a + b);\n" +
		"}\n\n" +
		"int main(void) {\n" +
		"\tprintf(\"%d\\n\", add(2, 3));\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC func result:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCFuncCallExpr pins a value-returning function called in expression
// position — here as the right-hand side of an assignment inside a loop.
func TestEmitCFuncCallExpr(t *testing.T) {
	src := `import "p2"

func inc(i int) int {
	return i + 1
}

func main() {
	var i int
	for {
		println(i)
		i = inc(i)
		p2.WaitMs(500)
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <propeller2.h>\n" +
		"#include <stdio.h>\n\n" +
		"int inc(int i);\n\n" +
		"int inc(int i) {\n" +
		"\treturn (i + 1);\n" +
		"}\n\n" +
		"int main(void) {\n" +
		"\tint i = 0;\n" +
		"\tfor (;;) {\n" +
		"\t\tprintf(\"%d\\n\", i);\n" +
		"\t\ti = inc(i);\n" +
		"\t\t_waitms(500);\n" +
		"\t}\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC func call expr:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCShortDecl pins short variable declarations (`x := expr`): the C type
// is inferred from the initializer — a call result (int add(...)) and, for a
// second declaration, an arithmetic expression over an existing local.
func TestEmitCShortDecl(t *testing.T) {
	src := `func add(a, b int) int {
	return a + b
}

func main() {
	x := add(2, 3)
	y := x + 1
	println(y)
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <stdio.h>\n\n" +
		"int add(int a, int b);\n\n" +
		"int add(int a, int b) {\n" +
		"\treturn (a + b);\n" +
		"}\n\n" +
		"int main(void) {\n" +
		"\tint x = add(2, 3);\n" +
		"\tint y = (x + 1);\n" +
		"\tprintf(\"%d\\n\", y);\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC short decl:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCVarInit pins `var name Type = expr` — the initializer form of a var
// declaration (the bare `var name Type` form is covered by TestEmitCCounter).
func TestEmitCVarInit(t *testing.T) {
	src := `func main() {
	var i int = 5
	println(i)
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	want := "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"#include <stdio.h>\n\n" +
		"int main(void) {\n" +
		"\tint i = 5;\n" +
		"\tprintf(\"%d\\n\", i);\n" +
		"\treturn 0;\n" +
		"}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC var init:\n got %q\nwant %q", got, want)
	}
}
