// Copyright 2026 The OctoGo Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package octogo // import "modernc.org/ogo/internal/ogo"

import (
	"fmt"
	"io"
)

// EmitC writes C source for the built package pkg to w. It is the walking
// skeleton of the OctoGo C backend: today it handles a single `func main()`
// with an empty body, emitting the equivalent C translation unit that the
// embedded flexcc compiles to a P2 binary. Anything it does not yet understand
// produces an "emit:" error rather than wrong C, so the surface grows honestly.
//
// The traversal mirrors the checker (see it()/sourceFile/funcDecl in check.go):
// dispatch non-terminals on Node.sym, read terminals via File.tok/File.ch.
func EmitC(pkg *Package, w io.Writer) error {
	e := &emitter{w: w}
	e.pr("// Code generated by ogo. DO NOT EDIT.\n\n")
	for _, f := range pkg.Files {
		e.f = f
		e.emitSourceFile(f.AST)
	}
	return e.err
}

type emitter struct {
	w   io.Writer
	f   *File // file currently being emitted, for token access
	err error
}

// pr writes formatted C, latching the first write error.
func (e *emitter) pr(format string, args ...any) {
	if e.err != nil {
		return
	}
	_, e.err = fmt.Fprintf(e.w, format, args...)
}

// fail latches the first "not yet implemented / unsupported" emit error.
func (e *emitter) fail(format string, args ...any) {
	if e.err == nil {
		e.err = fmt.Errorf("emit: "+format, args...)
	}
}

func (e *emitter) emitSourceFile(ast []int32) {
	for n := range it(ast) {
		if n.sym != SourceFile {
			continue
		}
		for c := range it(n.ast) {
			switch c.sym {
			case TopLevelDecl:
				e.emitTopLevelDecl(c.ast)
			case ImportDecl:
				// Imports carry no emitted code yet; the p2 intrinsic mapping
				// (and its <propeller2.h> include) lands with call statements.
			case 0:
				// SEMICOLON / EOF separators.
			default:
				e.fail("unsupported source-file element %v", c.sym)
			}
		}
	}
}

func (e *emitter) emitTopLevelDecl(ast []int32) {
	for n := range it(ast) {
		switch n.sym {
		case FuncDecl:
			e.emitFuncDecl(n.ast)
		default:
			e.fail("unsupported top-level declaration %v", n.sym)
		}
	}
}

func (e *emitter) emitFuncDecl(ast []int32) {
	var name string
	var body []int32
	hasBody := false
	for n := range it(ast) {
		switch n.sym {
		case 0:
			if e.f.ch(n.tok) == IDENT {
				name = e.f.tok(n.tok).Src()
			}
		case Receiver:
			e.fail("methods are not supported yet")
		case Signature:
			e.emitSignatureIsEmpty(n.ast)
		case Block:
			hasBody = true
			body = n.ast
		default:
			e.fail("unsupported in function declaration: %v", n.sym)
		}
	}

	// Walking skeleton: only `func main()` with an empty body.
	if name != "main" {
		e.fail("only func main is supported yet, got func %q", name)
		return
	}
	if !hasBody {
		e.fail("func main must have a body")
		return
	}
	e.pr("int main(void) {\n")
	e.emitBlock(body)
	e.pr("\treturn 0;\n}\n")
}

// emitSignatureIsEmpty asserts the signature has no parameters or results, the
// only shape supported by the skeleton (i.e. `func main()`).
func (e *emitter) emitSignatureIsEmpty(ast []int32) {
	for n := range it(ast) {
		switch n.sym {
		case 0:
			// LPAREN / RPAREN.
		case ParameterList:
			e.fail("function parameters are not supported yet")
		default:
			e.fail("function results are not supported yet (%v)", n.sym)
		}
	}
}

func (e *emitter) emitBlock(ast []int32) {
	for n := range it(ast) {
		switch n.sym {
		case 0:
			// LBRACE / RBRACE / SEMICOLON.
		case Statement:
			e.fail("statement emission is not implemented yet")
		default:
			e.fail("unsupported block element %v", n.sym)
		}
	}
}
