// Copyright 2026 The OctoGo Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package octogo

import (
	"bytes"
	"testing"
	"testing/fstest"
)

// TestEmitCMain pins the walking-skeleton emitter: an empty `func main()` must
// produce the equivalent C translation unit.
func TestEmitCMain(t *testing.T) {
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte("func main() {\n}\n")}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	const want = "// Code generated by ogo. DO NOT EDIT.\n\n" +
		"int main(void) {\n\treturn 0;\n}\n"
	if got := buf.String(); got != want {
		t.Errorf("EmitC:\n got %q\nwant %q", got, want)
	}
}

// TestEmitCBlink pins the emitter's first useful subset: imports -> #include,
// `for {}` -> `for (;;)`, and p2 calls -> P2 intrinsics.
func TestEmitCBlink(t *testing.T) {
	src := `import "p2"

func main() {
	for {
		p2.PinHigh(56)
		p2.WaitMs(200)
		p2.PinLow(56)
		p2.WaitMs(200)
	}
}
`
	fsys := fstest.MapFS{"main.ogo": &fstest.MapFile{Data: []byte(src)}}
	pkg, err := Build(-1, []string{"main.ogo"}, fsys)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}

	var buf bytes.Buffer
	if err := EmitC(pkg, &buf); err != nil {
		t.Fatalf("EmitC: %v", err)
	}

	const want = `// Code generated by ogo. DO NOT EDIT.

#include <propeller2.h>

int main(void) {
	for (;;) {
		_pinh(56);
		_waitms(200);
		_pinl(56);
		_waitms(200);
	}
	return 0;
}
`
	if got := buf.String(); got != want {
		t.Errorf("EmitC blink:\n got %q\nwant %q", got, want)
	}
}
