// Copyright 2026 The OctoGo Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package octogo // import "modernc.org/ogo/internal/ogo"

import (
	"bytes"
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"
)

// p2Intrinsics maps exported functions of the builtin "p2" package to the
// flexcc / propeller2.h C intrinsics they wrap (the p2 mapping documented in
// CLAUDE.md's appendix). The call `p2.PinHigh(56)` emits `_pinh(56)`.
var p2Intrinsics = map[string]string{
	"PinHigh":      "_pinh",
	"PinLow":       "_pinl",
	"PinIn":        "_pinr",
	"WaitMs":       "_waitms",
	"AckPin":       "_akpin",
	"ReadPin":      "_rdpin",
	"WritePinMode": "_wrpin",
	"WritePinX":    "_wxpin",
	"WritePinY":    "_wypin",
}

// importIncludes maps an OctoGo import path to the C header it pulls in.
var importIncludes = map[string]string{
	"p2": "propeller2.h",
}

// cTypes maps predeclared OctoGo type names to C types. int is int32 in OctoGo
// and the P2's C int is 32-bit, so int maps to plain int. Fixed-width names use
// <stdint.h> (see stdintType).
var cTypes = map[string]string{
	"int": "int", "uint": "unsigned", "bool": "int",
	"int8": "int8_t", "int16": "int16_t", "int32": "int32_t",
	"uint8": "uint8_t", "uint16": "uint16_t", "uint32": "uint32_t",
	"byte": "uint8_t", "rune": "int32_t", "uintptr": "uintptr_t",
}

// EmitC writes C source for the built package pkg to w. It is the walking
// skeleton of the OctoGo C backend, grown to a first computational subset: a
// `func main()` with local int variables, `for {}` loops, assignments and
// arithmetic, calls to the builtin p2 package (mapped to P2 intrinsics), and
// print/println (mapped to printf over the P2 serial line). Anything it does not
// yet understand produces an "emit:" error rather than wrong C, so the surface
// grows honestly.
//
// The traversal mirrors the checker (see it()/sourceFile/funcDecl in check.go):
// dispatch non-terminals on Node.sym, read terminals via File.tok/File.ch.
func EmitC(pkg *Package, w io.Writer) error {
	e := &emitter{includes: map[string]bool{}}

	// Pass 1: forward prototypes for user functions. C requires a declaration
	// before use, but OctoGo (like Go) does not order top-level declarations, so
	// a call may precede its definition; the prototypes make emission order
	// independent of source order.
	var protos bytes.Buffer
	e.w = &protos
	for _, f := range pkg.Files {
		e.f = f
		e.emitPrototypes(f.AST)
	}

	// Pass 2: the function definitions themselves.
	var body bytes.Buffer
	e.w = &body
	e.wroteDecl = false
	for _, f := range pkg.Files {
		e.f = f
		e.emitFileDecls(f.AST)
	}
	if e.err != nil {
		return e.err
	}

	// Assemble: header, sorted #includes, prototypes, then the definitions.
	incs := make([]string, 0, len(e.includes))
	for inc := range e.includes {
		incs = append(incs, inc)
	}
	slices.Sort(incs)

	var out bytes.Buffer
	out.WriteString("// Code generated by ogo. DO NOT EDIT.\n\n")
	for _, inc := range incs {
		fmt.Fprintf(&out, "#include <%s>\n", inc)
	}
	if len(incs) != 0 {
		out.WriteByte('\n')
	}
	if protos.Len() != 0 {
		out.Write(protos.Bytes())
		out.WriteByte('\n')
	}
	out.Write(body.Bytes())
	_, err := w.Write(out.Bytes())
	return err
}

type emitter struct {
	w         io.Writer // body buffer during the walk
	f         *File     // file currently being emitted, for token access
	indent    int
	includes  map[string]bool
	wroteDecl bool // a top-level definition has been emitted (drives blank-line separators)
	mainRet   bool // currently emitting main's body: a bare `return` yields `return 0;`
	err       error
}

// emit writes verbatim C text, latching the first write error. All C is written
// through emit so no source text is ever interpreted as a printf verb.
func (e *emitter) emit(s string) {
	if e.err != nil {
		return
	}
	_, e.err = io.WriteString(e.w, s)
}

// fail latches the first "not yet implemented / unsupported" emit error.
func (e *emitter) fail(format string, args ...any) {
	if e.err == nil {
		e.err = fmt.Errorf("emit: "+format, args...)
	}
}

func (e *emitter) ind() {
	for i := 0; i < e.indent; i++ {
		e.emit("\t")
	}
}

// src returns a terminal token's source text.
func (e *emitter) src(tok int32) string { return e.f.tok(tok).Src() }

func (e *emitter) emitFileDecls(ast []int32) {
	for n := range it(ast) {
		if n.sym != SourceFile {
			continue
		}
		for c := range it(n.ast) {
			switch c.sym {
			case ImportDecl:
				e.addImportIncludes(c.ast)
			case TopLevelDecl:
				e.emitTopLevelDecl(c.ast)
			case 0:
				// SEMICOLON / EOF separators.
			default:
				e.fail("unsupported source-file element %v", c.sym)
			}
		}
	}
}

func (e *emitter) addImportIncludes(ast []int32) {
	for n := range it(ast) {
		if n.sym != ImportSpec {
			continue
		}
		for c := range it(n.ast) {
			if c.sym != 0 || e.f.ch(c.tok) != STRING {
				continue
			}
			path, err := strconv.Unquote(e.src(c.tok))
			if err != nil {
				continue
			}
			if inc, ok := importIncludes[path]; ok {
				e.includes[inc] = true
			} else {
				e.fail("no C header mapping for import %q", path)
			}
		}
	}
}

func (e *emitter) emitTopLevelDecl(ast []int32) {
	for n := range it(ast) {
		switch n.sym {
		case FuncDecl:
			e.emitFuncDecl(n.ast)
		default:
			e.fail("unsupported top-level declaration %v", n.sym)
		}
	}
}

// emitPrototypes emits a forward prototype for every user function in a file
// (all but main, which C declares implicitly). Run before the definitions so a
// call need not follow its callee's definition.
func (e *emitter) emitPrototypes(ast []int32) {
	for n := range it(ast) {
		if n.sym != SourceFile {
			continue
		}
		for c := range it(n.ast) {
			if c.sym != TopLevelDecl {
				continue
			}
			for d := range it(c.ast) {
				if d.sym != FuncDecl {
					continue
				}
				if name, sig, _, isMethod, ok := e.funcParts(d.ast); ok && !isMethod && name != "main" {
					if proto := e.funcSignatureC(name, sig); proto != "" {
						e.emit(proto + ";\n")
					}
				}
			}
		}
	}
}

func (e *emitter) emitFuncDecl(ast []int32) {
	name, sig, body, isMethod, ok := e.funcParts(ast)
	if !ok {
		return
	}
	if isMethod {
		e.fail("methods are not supported yet")
		return
	}
	if body == nil {
		e.fail("func %q must have a body", name)
		return
	}

	if e.wroteDecl {
		e.emit("\n")
	}
	e.wroteDecl = true

	if name == "main" {
		e.emitMain(sig, body)
		return
	}
	proto := e.funcSignatureC(name, sig)
	if proto == "" {
		return
	}
	e.emit(proto + " {\n")
	e.indent++
	e.emitBlockStmts(body)
	e.indent--
	e.emit("}\n")
}

// funcParts pulls the name, signature subtree and body subtree from a FuncDecl
// AST. isMethod is set when a Receiver is present; body is nil for a bodyless
// declaration. ok is false only if the walk hit an unexpected element.
func (e *emitter) funcParts(ast []int32) (name string, sig, body []int32, isMethod, ok bool) {
	ok = true
	for n := range it(ast) {
		switch n.sym {
		case 0:
			if e.f.ch(n.tok) == IDENT {
				name = e.src(n.tok)
			}
		case Receiver:
			isMethod = true
		case Signature:
			sig = n.ast
		case Block:
			body = n.ast
		default:
			e.fail("unsupported in function declaration: %v", n.sym)
			ok = false
		}
	}
	return name, sig, body, isMethod, ok
}

// emitMain emits `func main()` as `int main(void)`; main takes no parameters or
// results.
func (e *emitter) emitMain(sig, body []int32) {
	if params, hasResult := e.cParams(sig); params != "" || hasResult {
		e.fail("func main must have no parameters or results")
		return
	}
	e.emit("int main(void) {\n")
	e.indent++
	e.mainRet = true
	e.emitBlockStmts(body)
	e.mainRet = false
	e.ind()
	e.emit("return 0;\n")
	e.indent--
	e.emit("}\n")
}

// funcSignatureC builds the C signature `void name(params)` for a user function.
// Results are not modelled yet, so a function with a result list fails honestly.
func (e *emitter) funcSignatureC(name string, sig []int32) string {
	params, hasResult := e.cParams(sig)
	if hasResult {
		e.fail("function results are not supported yet")
		return ""
	}
	if params == "" {
		params = "void"
	}
	return "void " + name + "(" + params + ")"
}

// cParams renders a Signature's parameters as a C parameter list ("int a, int b")
// and reports whether the signature declares any results. Parameters are always
// named (the grammar requires it), so each maps to a `<ctype> <name>` C parameter.
func (e *emitter) cParams(sig []int32) (params string, hasResult bool) {
	var parts []string
	seenRPar := false
	for n := range it(sig) {
		switch n.sym {
		case ParameterList:
			if seenRPar {
				hasResult = true // a result list: "(" ParameterList ")"
				continue
			}
			parts = e.cParamList(n.ast)
		case Type:
			hasResult = true // a single unnamed result appears as a bare Type
		case 0:
			if e.f.ch(n.tok) == RPAREN {
				seenRPar = true
			}
		default:
			e.fail("unsupported signature element %v", n.sym)
		}
	}
	return strings.Join(parts, ", "), hasResult
}

// cParamList renders one ParameterList's `IdentifierList Type` groups to C
// parameters, expanding a shared type ("a, b int" -> "int a, int b").
func (e *emitter) cParamList(ast []int32) []string {
	var out []string
	var names []string
	for n := range it(ast) {
		switch n.sym {
		case IdentifierList:
			names = names[:0]
			for id := range it(n.ast) {
				if id.sym == 0 && e.f.ch(id.tok) == IDENT {
					names = append(names, e.src(id.tok))
				}
			}
		case Type:
			ct := e.cType(n.ast)
			for _, nm := range names {
				out = append(out, ct+" "+nm)
			}
			names = names[:0]
		}
	}
	return out
}

// emitBlockStmts emits the statements of a Block (skipping its braces).
func (e *emitter) emitBlockStmts(ast []int32) {
	for n := range it(ast) {
		switch n.sym {
		case 0:
			// LBRACE / RBRACE / SEMICOLON.
		case Statement:
			e.emitStatement(n.ast)
		default:
			e.fail("unsupported block element %v", n.sym)
		}
	}
}

func (e *emitter) emitStatement(ast []int32) {
	nodes := slices.Collect(it(ast))
	if len(nodes) == 0 {
		return // EmptyStatement
	}
	switch first := nodes[0]; {
	case first.sym == VarDecl:
		e.emitVarDecl(first.ast)
	case first.sym == 0 && e.f.ch(first.tok) == FOR:
		e.emitFor(nodes)
	case first.sym == 0 && e.f.ch(first.tok) == IF:
		e.emitIf(nodes)
	case first.sym == 0 && e.f.ch(first.tok) == RETURN:
		e.emitReturn(nodes)
	case first.sym == AssignHead:
		e.emitAssignHeadStmt(nodes)
	case first.sym == 0:
		e.fail("%v statement is not supported yet", e.f.ch(first.tok))
	default:
		e.fail("statement %v is not supported yet", first.sym)
	}
}

// emitVarDecl handles `var name Type` (zero-initialized; P2 stack locals are not
// auto-zeroed, so the `= 0` is required) and `var name Type = expr`.
func (e *emitter) emitVarDecl(ast []int32) {
	for n := range it(ast) {
		if n.sym != VarSpec {
			continue
		}
		var names []string
		ctype := ""
		var initExpr []int32
		for s := range it(n.ast) {
			switch s.sym {
			case IdentifierList:
				for id := range it(s.ast) {
					if id.sym == 0 && e.f.ch(id.tok) == IDENT {
						names = append(names, e.src(id.tok))
					}
				}
			case Type:
				ctype = e.cType(s.ast)
			case Expression:
				initExpr = s.ast
			default:
				e.fail("unsupported var-spec element %v", s.sym)
			}
		}
		if ctype == "" {
			e.fail("var declaration needs an explicit type (inference not supported yet)")
			return
		}
		if len(names) != 1 && initExpr != nil {
			e.fail("multi-name var with initializer is not supported yet")
			return
		}
		for _, nm := range names {
			e.ind()
			e.emit(ctype + " " + nm + " = ")
			if initExpr != nil {
				e.emitExpr(initExpr)
			} else {
				e.emit("0")
			}
			e.emit(";\n")
		}
	}
}

// cType maps a Type subtree that names a single predeclared type to its C type,
// recording any needed <stdint.h> include.
func (e *emitter) cType(ast []int32) string {
	name := ""
	for n := range it(ast) {
		if n.sym == 0 && e.f.ch(n.tok) == IDENT {
			name = e.src(n.tok)
		}
	}
	ct, ok := cTypes[name]
	if !ok {
		e.fail("unsupported type %q", name)
		return ""
	}
	if strings.HasSuffix(ct, "_t") {
		e.includes["stdint.h"] = true
	}
	return ct
}

// emitFor handles `for {}` (infinite -> for(;;)) and `for cond {}` (conditional
// -> while(cond)). Init/post clauses and range are not supported yet.
func (e *emitter) emitFor(nodes []Node) {
	var cond, body []int32
	for _, n := range nodes[1:] {
		switch n.sym {
		case Expression:
			cond = n.ast
		case Block:
			body = n.ast
		default:
			e.fail("for-loop clause %v is not supported yet", n.sym)
			return
		}
	}
	if body == nil {
		e.fail("for-loop without a body")
		return
	}
	e.ind()
	if cond == nil {
		e.emit("for (;;) {\n")
	} else {
		e.emit("while ")
		e.emitCondition(cond)
		e.emit(" {\n")
	}
	e.indent++
	e.emitBlockStmts(body)
	e.indent--
	e.ind()
	e.emit("}\n")
}

// emitIf handles `if cond { ... }` with an optional `else { ... }`. `else if`
// chains and if-init clauses are not supported yet.
func (e *emitter) emitIf(nodes []Node) {
	var cond, thenBody, elseBody []int32
	for _, n := range nodes[1:] {
		switch n.sym {
		case Expression:
			cond = n.ast
		case Block:
			if thenBody == nil {
				thenBody = n.ast
			} else {
				elseBody = n.ast
			}
		case 0:
			// ELSE terminal.
		default:
			e.fail("if clause %v is not supported yet", n.sym)
			return
		}
	}
	if cond == nil || thenBody == nil {
		e.fail("malformed if statement")
		return
	}
	e.ind()
	e.emit("if ")
	e.emitCondition(cond)
	e.emit(" {\n")
	e.indent++
	e.emitBlockStmts(thenBody)
	e.indent--
	e.ind()
	e.emit("}")
	if elseBody != nil {
		e.emit(" else {\n")
		e.indent++
		e.emitBlockStmts(elseBody)
		e.indent--
		e.ind()
		e.emit("}")
	}
	e.emit("\n")
}

// emitCondition emits an if/for condition wrapped in exactly one set of
// parentheses. It emits the Expression's children directly (rather than the
// Expression node, which would add its own binary-operator parens) so a simple
// `i < 20` becomes `(i < 20)`, not `((i < 20))`.
func (e *emitter) emitCondition(exprChildren []int32) {
	e.emit("(")
	for n := range it(exprChildren) {
		e.emitExprNode(n)
	}
	e.emit(")")
}

// emitReturn handles `return` and (only in a value-returning function that is
// not yet supported) `return expr`. A bare return in main yields `return 0;` to
// satisfy C's int main; in a void function it yields `return;`.
func (e *emitter) emitReturn(nodes []Node) {
	for _, n := range nodes[1:] {
		if n.sym == ExpressionList {
			e.fail("return with a value is not supported yet")
			return
		}
	}
	e.ind()
	if e.mainRet {
		e.emit("return 0;\n")
	} else {
		e.emit("return;\n")
	}
}

// emitAssignHeadStmt handles the `AssignHead Postfix` statement family: a call
// (Postfix ends in CallSuffix) or an assignment (Postfix carries a PostfixOp).
func (e *emitter) emitAssignHeadStmt(nodes []Node) {
	if len(nodes) != 2 || nodes[1].sym != Postfix {
		e.fail("unsupported statement form")
		return
	}
	head := nodes[0]
	postfix := slices.Collect(it(nodes[1].ast))
	switch {
	case containsSym(postfix, PostfixOp):
		e.emitAssignment(head, postfix)
	case containsSym(postfix, CallSuffix):
		e.emitCall(head, postfix)
	default:
		e.fail("unsupported statement form")
	}
}

// emitCall handles a direct builtin call (`println(x)`) or a qualified
// package-function call (`p2.PinHigh(56)`).
func (e *emitter) emitCall(head Node, postfix []Node) {
	recv := e.soleIdent(head.ast)
	if recv == "" {
		e.fail("unsupported call target")
		return
	}
	switch {
	case len(postfix) == 1 && postfix[0].sym == CallSuffix:
		e.emitDirectCall(recv, postfix[0].ast)
	case len(postfix) == 2 && postfix[0].sym == Selector && postfix[1].sym == CallSuffix:
		e.emitQualifiedCall(recv, e.soleIdent(postfix[0].ast), postfix[1].ast)
	default:
		e.fail("only <pkg>.<Func>(args) or builtin(args) call statements are supported yet")
	}
}

func (e *emitter) emitDirectCall(name string, callSuffix []int32) {
	switch name {
	case "println", "print":
		e.emitPrint(name == "println", callSuffix)
	default:
		// A user-defined function call as a statement; the checker has already
		// verified the name resolves to a function and the arguments match.
		e.ind()
		e.emit(name + "(")
		e.emitCallArgs(callSuffix)
		e.emit(");\n")
	}
}

func (e *emitter) emitQualifiedCall(pkg, method string, callSuffix []int32) {
	if pkg != "p2" {
		e.fail("unknown package %q (only p2 is supported yet)", pkg)
		return
	}
	intr, ok := p2Intrinsics[method]
	if !ok {
		e.fail("unsupported p2 function %q", method)
		return
	}
	e.ind()
	e.emit(intr + "(")
	e.emitCallArgs(callSuffix)
	e.emit(");\n")
}

// emitPrint maps print/println of a single integer to printf over the P2 serial
// line. println appends a newline.
func (e *emitter) emitPrint(newline bool, callSuffix []int32) {
	args := e.callArgExprs(callSuffix)
	e.includes["stdio.h"] = true
	e.ind()
	switch len(args) {
	case 0:
		if newline {
			e.emit("printf(\"\\n\");\n")
		} else {
			e.emit("(void)0;\n")
		}
	case 1:
		if newline {
			e.emit("printf(\"%d\\n\", ")
		} else {
			e.emit("printf(\"%d\", ")
		}
		e.emitExpr(args[0].ast)
		e.emit(");\n")
	default:
		e.fail("print/println with multiple arguments is not supported yet")
	}
}

// emitAssignment handles `lhs = expr` (single target, `=` only).
func (e *emitter) emitAssignment(head Node, postfix []Node) {
	if len(postfix) != 1 {
		e.fail("unsupported assignment target")
		return
	}
	lhs := e.soleIdent(head.ast)
	if lhs == "" {
		e.fail("only assignment to a simple variable is supported yet")
		return
	}
	op := slices.Collect(it(postfix[0].ast)) // PostfixOp = "=" Expression
	if len(op) != 2 || op[0].sym != 0 || e.f.ch(op[0].tok) != ASSIGN || op[1].sym != Expression {
		e.fail("only `name = expr` assignments are supported yet")
		return
	}
	e.ind()
	e.emit(lhs + " = ")
	e.emitExpr(op[1].ast)
	e.emit(";\n")
}

func (e *emitter) emitCallArgs(callSuffix []int32) {
	first := true
	for _, arg := range e.callArgExprs(callSuffix) {
		if !first {
			e.emit(", ")
		}
		first = false
		e.emitExpr(arg.ast)
	}
}

// callArgExprs returns the argument Expression nodes of a CallSuffix.
func (e *emitter) callArgExprs(callSuffix []int32) []Node {
	var args []Node
	for n := range it(callSuffix) {
		if n.sym != ArgumentList {
			continue
		}
		for a := range it(n.ast) {
			if a.sym == Expression {
				args = append(args, a)
			}
		}
	}
	return args
}

// soleIdent returns the single identifier of a subtree (an AssignHead bare name
// or a Selector's field), or "" if the shape is richer.
func (e *emitter) soleIdent(ast []int32) string {
	name := ""
	for n := range it(ast) {
		if n.sym != 0 || e.f.ch(n.tok) != IDENT {
			continue
		}
		if name != "" {
			return ""
		}
		name = e.src(n.tok)
	}
	return name
}

// emitExpr emits a value expression. Binary operators (Expression/SimpleExpr/
// Term) are parenthesized so the OctoGo parse grouping is preserved even where C
// operator precedence differs (notably Go binds << tighter than C does).
//
// TODO: normalize Go literal syntax that C rejects (digit separators `1_000`,
// `0b`/`0o` prefixes) — currently INT text is emitted verbatim, correct only for
// plain decimal integers.
func (e *emitter) emitExpr(ast []int32) {
	for n := range it(ast) {
		e.emitExprNode(n)
	}
}

func (e *emitter) emitExprNode(n Node) {
	switch n.sym {
	case Expression, SimpleExpr, Term:
		kids := slices.Collect(it(n.ast))
		if len(kids) == 1 {
			e.emitExprNode(kids[0])
			return
		}
		e.emit("(")
		for _, c := range kids {
			e.emitExprNode(c)
		}
		e.emit(")")
	case UnaryExpr, Factor:
		kids := slices.Collect(it(n.ast))
		if len(kids) == 3 && kids[0].sym == 0 && e.f.ch(kids[0].tok) == LPAREN {
			e.emit("(")
			e.emitExprNode(kids[1])
			e.emit(")")
			return
		}
		for _, c := range kids {
			e.emitExprNode(c)
		}
	case AddOp, MulOp, RelOp:
		e.emit(" " + e.opText(n.ast) + " ")
	case 0:
		e.emitOperandToken(n.tok)
	default:
		e.fail("unsupported expression node %v", n.sym)
	}
}

// opText returns the operator terminal's text from an AddOp/MulOp/RelOp node.
// The OctoGo operators here all coincide with their C spellings.
func (e *emitter) opText(ast []int32) string {
	for n := range it(ast) {
		if n.sym == 0 {
			return e.src(n.tok)
		}
	}
	return ""
}

func (e *emitter) emitOperandToken(tok int32) {
	switch ch := e.f.ch(tok); ch {
	case INT, IDENT:
		e.emit(e.src(tok))
	case SUB, ADD, NOT:
		e.emit(e.src(tok)) // unary -, +, ! (prefix)
	case XOR:
		e.emit("~") // Go unary ^ is bitwise complement
	default:
		e.fail("unsupported operand %v", ch)
	}
}

func containsSym(nodes []Node, sym Symbol) bool {
	for _, n := range nodes {
		if n.sym == sym {
			return true
		}
	}
	return false
}
