unicode_digit  = `\p{Nd}` .
unicode_letter = `\pL` .
letter        = unicode_letter | "_" .
decimal_digit = `[0-9]` .
binary_digit  = "0" | "1" .
octal_digit   = `[0-7]` .
hex_digit     = `[0-9A-Fa-f]` .
white_space            = `/\*([^*]|\*+[^*/])*\*+/|//.*| |\t|\n|\r` .
identifier = letter { letter | unicode_digit } .
int_lit        = decimal_lit | binary_lit | octal_lit | hex_lit .
decimal_lit    = "0" | ( `[1-9]` ) [ [ "_" ] decimal_digits ] .
binary_lit     = "0" ( "b" | "B" ) [ "_" ] binary_digits .
octal_lit      = "0" [ "o" | "O" ] [ "_" ] octal_digits .
hex_lit        = "0" ( "x" | "X" ) [ "_" ] hex_digits .
decimal_digits = decimal_digit { [ "_" ] decimal_digit } .
binary_digits  = binary_digit { [ "_" ] binary_digit } .
octal_digits   = octal_digit { [ "_" ] octal_digit } .
hex_digits     = hex_digit { [ "_" ] hex_digit } .
float_lit = decimal_digits "." decimal_digits .
rune_lit         = '\'' ( `[^'\\\n\r]` | unicode_value | byte_value ) '\'' .
unicode_value    = little_u_value | big_u_value | escaped_char .
byte_value       = octal_byte_value | hex_byte_value .
octal_byte_value = "\\" octal_digit octal_digit octal_digit .
hex_byte_value   = "\\" "x" hex_digit hex_digit .
little_u_value   = "\\" "u" hex_digit hex_digit hex_digit hex_digit .
big_u_value      = "\\" "U" hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit hex_digit .
escaped_char     = "\\" ( "a" | "b" | "f" | "n" | "r" | "t" | "v" | "\\" | "'" | "\"" ) .
string_lit             = raw_string_lit | interpreted_string_lit .
raw_string_lit         = '`' { `[^\x60]` } '`' .
interpreted_string_lit = '"' { `[^"\\\n\r]` | unicode_value | byte_value } '"' .
Type = [ identifier "." ] identifier
	| "chan" Type
	| "[" [ Expression ] "]" Type
	| "*" Type
	| InterfaceType
	| StructType
	| "func" Signature .
StructType = "struct" "{" { FieldDecl ";" } [ FieldDecl ] "}" .
FieldDecl = "*" [ identifier "." ] identifier
	| identifier [ "." identifier | { "," identifier } Type ] .
InterfaceType = "interface" "{" { MethodSpec ";" } [ MethodSpec ] "}" .
MethodSpec = identifier "(" [ ParameterList ] ")" [ Type | "(" ResultList ")" ] .
Block = "{" { Statement ";" } [ Statement ] "}" .
TopLevelDecl = FuncDecl | VarDecl | ConstDecl | TypeDecl .
VarDecl = "var" ( VarSpec | "(" { VarSpec ";" } [ VarSpec ] ")" ) .
VarSpec = IdentifierList ( Type [ "=" Expression ] | "=" Expression ) .
ConstDecl = "const" ( ConstSpec | "(" { ConstSpec ";" } [ ConstSpec ] ")" ) .
ConstSpec = identifier [ Type ] [ "=" Expression ] .
TypeDecl = "type" ( TypeSpec | "(" { TypeSpec ";" } [ TypeSpec ] ")" ) .
TypeSpec = identifier [ "=" ] Type .
FuncDecl       = "func" [ Receiver ] identifier Signature [ Block ] .
Signature      = "(" [ ParameterList ] ")" [ Type | "(" ResultList ")" ] .
Receiver       = "(" identifier Type ")" .
ParameterList  = ParamDecl { "," ParamDecl } .
ResultList     = ParamDecl { "," ParamDecl } .
ParamDecl      = Type [ Type ] .
IdentifierList = identifier { "," identifier } .
ExpressionList = Expression { "," Expression } .
Expression     = SimpleExpr { RelOp SimpleExpr } .
SimpleExpr     = Term { AddOp Term } .
Term           = UnaryExpr { MulOp UnaryExpr } .
UnaryExpr  = { UnaryOp } Factor .
Factor     = identifier [ FactorSuffix ]
	| int_lit
	| float_lit
	| string_lit
	| rune_lit
	| "(" Expression ")"
	| "[" [ Expression ] "]" Type
	| FuncLiteral .
FactorSuffix = { Selector | Index | CallSuffix } .
Selector     = "." ( identifier | "(" "type" ")" ) .
Index        = "[" ( Expression [ ":" [ Expression ] ] | ":" [ Expression ] ) "]" .
FuncLiteral = "func" Signature Block .
UnaryOp    = "+" | "-" | "!" | "^" | "*" | "&" | "<-" | "~" .
RelOp = "==" | "!=" | "<" | "<=" | ">" | ">=" | "&&" | "||" .
AddOp = "+" | "-" | "|" | "^" .
MulOp = "*" | "/" | "%" | "<<" | ">>" | "&" .
CallSuffix = "(" [ ArgumentList ] ")" .
ArgumentList = Expression { "," Expression } .
Statement = VarDecl
	| ConstDecl
	| TypeDecl
	| IfStmt
	| "for" [ ForHeader ] Block
	| "break"
	| "continue"
	| "return" [ ExpressionList ]
	| "go" AssignHead { Selector | Index | CallSuffix }
	| SwitchStmt
	| SelectStmt
	| "<-" Expression
	| AssignHead Postfix
	| "defer" AssignHead { Selector | Index | CallSuffix }
	| Block
	| EmptyStatement .
EmptyStatement = .
AssignHead = { "*" } ( identifier | "(" Expression ")" ) .
Postfix    = { Selector | Index | CallSuffix } [ PostfixOp ] .
PostfixOp  = "<-" Expression
	| "++"
	| "--"
	| AssignOp Expression
	| { "," LhsItem } ( "=" | ":=" ) ExpressionList .
AssignOp   = "+=" | "-=" | "*=" | "/=" | "%="
	| "&=" | "|=" | "^=" | "&^="
	| "<<=" | ">>=" .
LhsItem    = AssignHead { Selector | Index } .
ForHeader  = ";" [ Expression ] ";" [ ForPost ]
	| "range" Expression
	| Expression [ ForRest ] .
ForRest    = ";" [ Expression ] ";" [ ForPost ]
	| ( "=" | ":=" ) ForAssignRest
	| "," Expression ( "=" | ":=" ) "range" Expression .
ForAssignRest = "range" Expression
	| Expression ";" [ Expression ] ";" [ ForPost ] .
ForPost    = Expression [ ( "=" | ":=" ) Expression | "++" | "--" ] .
IfStmt = "if" Expression Block [ "else" ( IfStmt | Block ) ] .
SwitchStmt = "switch" [ SwitchGuard ] "{" { CaseClause } "}" .
SwitchGuard = Expression [ ":=" Expression ] .
CaseClause = CaseHead ":" { Statement ";" } [ Statement ] .
CaseHead   = "case" ExpressionList | "default" .
SelectStmt  = "select" "{" { CommClause } "}" .
CommClause  = CommHead ":" { Statement ";" } .
CommHead    = "case" CommOp | "default" .
CommOp      = "<-" Expression
	| AssignHead PostfixComm .
PostfixComm = { Selector | Index } ( ( "=" | ":=" ) "<-" Expression | "<-" Expression ) .
SourceFile = { ImportDecl ";" } { TopLevelDecl ";" } .
ImportDecl = "import" ( ImportSpec | "(" { ImportSpec ";" } [ ImportSpec ] ")" ) .
ImportSpec = [ "." | identifier ] string_lit .
