// Code generated by "stringer -output stringer.go -type Kind,ScopeKind,gate"; DO NOT EDIT.

package octogo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PredeclaredBool-0]
	_ = x[PredeclaredInt8-1]
	_ = x[PredeclaredUint8-2]
	_ = x[PredeclaredInt16-3]
	_ = x[PredeclaredUint16-4]
	_ = x[PredeclaredInt32-5]
	_ = x[PredeclaredUint32-6]
	_ = x[PredeclaredUintptr-7]
	_ = x[UntypedBool-8]
	_ = x[UntypedFloat-9]
	_ = x[UntypedInt-10]
	_ = x[UntypedNil-11]
	_ = x[UntypedString-12]
	_ = x[Alias-13]
}

const _Kind_name = "PredeclaredBoolPredeclaredInt8PredeclaredUint8PredeclaredInt16PredeclaredUint16PredeclaredInt32PredeclaredUint32PredeclaredUintptrUntypedBoolUntypedFloatUntypedIntUntypedNilUntypedStringAlias"

var _Kind_index = [...]uint8{0, 15, 30, 46, 62, 79, 95, 112, 130, 141, 153, 163, 173, 186, 191}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UniverseScope-0]
	_ = x[FileScope-1]
	_ = x[PackageScope-2]
	_ = x[BlockScope-3]
}

const _ScopeKind_name = "UniverseScopeFileScopePackageScopeBlockScope"

var _ScopeKind_index = [...]uint8{0, 13, 22, 34, 44}

func (i ScopeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ScopeKind_index)-1 {
		return "ScopeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScopeKind_name[_ScopeKind_index[idx]:_ScopeKind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unvisited-0]
	_ = x[resolving-1]
	_ = x[resolved-2]
}

const _gate_name = "unvisitedresolvingresolved"

var _gate_index = [...]uint8{0, 9, 18, 26}

func (i gate) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_gate_index)-1 {
		return "gate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gate_name[_gate_index[idx]:_gate_index[idx+1]]
}
